### ISSUE TITLE
Is there a "track/lane" option?

### ISSUE THREAD

**Issue by jonnymaceachern** [NUKnightLab/TimelineJS3#100]
Imagine a festival where each stage has it's own lineup. Or swimlanes in a flowchart.

From what I can tell, additional tracks are only added to reduced clutter / overlapping dates. Is that right? What I'd like is the option to specify and label my own tracks, and assign date objects to those tracks.

**Comment by JoeGermuska** [comment]
This is done by setting a "group" property on the JSON for any given event object. The value for "group" should just be any text, and that text will be used to label the "lane"

This is not yet properly documented, so I'm going to keep this open until we do that.

**Comment by JoeGermuska** [comment]
will be fixed in next website deployment
