### ISSUE TITLE
Title slide not first and default date

### ISSUE THREAD

**Issue by thejordan** [NUKnightLab/TimelineJS3#108]
The title slide is not showing up first and a default date is added to it as January 1, 1900
Link to my sheet:
https://docs.google.com/spreadsheets/d/1Q3qQzRQSCBPsf9x46aVjMX2SGCTkSRABlQd7xprqynM/edit?usp=sharing

**Comment by JoeGermuska** [comment]
I think this is fixed. @thejordan can you test it out on the test server?

**Comment by thejordan** [comment]
works now!
