### ISSUE TITLE
Test Google Maps types to ensure they flow through properly

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/TimelineJS3#110]
The following Google Maps base layers should automatically be interpreted as the correct type when they are put into the spreadsheet:
- Roadmap (default)
- Earth [was Satellite]
- Streetview
- Terrain
- Hybrid [Earth with labels]

**Comment by thejordan** [comment]
Using this to test: https://docs.google.com/spreadsheets/d/1Q3qQzRQSCBPsf9x46aVjMX2SGCTkSRABlQd7xprqynM/pubhtml
working fine:
normal map (title slide): https://www.google.com/maps/place/Achill+Archaeological+Field+School/@53.974863,-10.128385,17z/data=!4m2!3m1!1s0x485997bd4e48550f:0x31fb5a34c1a4dfde!6m1!1e1
Earth map (Iron Age Ireland): https://www.google.com/maps/place/Slievemore,+Co.+Mayo,+Ireland/@54.0088805,-10.0594444,7863m/data=!3m1!1e3!4m2!3m1!1s0x48599879ff44585f:0xd4b013b662c34d3d!6m1!1e1
Streetview (Achill Field School established): <iframe src="https://www.google.com/maps/embed?pb=!1m0!3m2!1sen!2sus!4v1434661397277!6m8!1m7!1stY0u9PIidNh3YW6x5nRAVw!2m2!1d53.975061!2d-10.12828!3f270!4f0!5f0.7820865974627469" width="600" height="450" frameborder="0" style="border:0"></iframe>

Not working:
Streetview (Achill Field School established): https://docs.google.com/spreadsheets/d/1Q3qQzRQSCBPsf9x46aVjMX2SGCTkSRABlQd7xprqynM/pubhtml
Gives me this
![screen shot 2015-06-18 at 4 08 07 pm](https://cloud.githubusercontent.com/assets/2432672/8242342/4af19b84-15d4-11e5-992e-52c7361f577a.png)

Not even sure how you make those other maps to test them.

**Comment by hbillings** [comment]
For the streetview iframe embed, does that mean you copied the entire iframe embed into the Google doc? Not just the embed URL? Iframe embeds should work fine because they aren't parsed as maps, AFAIK.

The other kinds of maps are made by toggling overlays. "Terrain" is under "Getting around" options. It looks like "Satellite" has been replaced with "Earth", and that "Hybrid" has been replaced by "Terrain".

**Comment by hbillings** [comment]
https://docs.google.com/spreadsheets/d/1zCpvtRdftlR5fBPppmy_-SkGIo7RMwoPUiGFZDAXbTc/pubhtml should have all of the map types on it, self who will come into work on Monday and have no idea how to start on this.

**Comment by hbillings** [comment]
All working except Streetview. Filing a separate issue for that.
