### ISSUE TITLE
Investigate implementing "start at end" option

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/TimelineJS3#112]
Joe says this shouldn't be too hard to hook up. Let's see if that's the case.

**Comment by hbillings** [comment]
After half an hour, I still have literally no idea where this option is hiding. Is it the same as `start_at_end` in `options` just set to the last slide? Should it be? Who told me I could write JavaScript, anyway?

**Comment by zachwise** [comment]
There is no option for that in Timeline3 yet. The best you could do is set the `start_at_slide` option and figure out how many slides there are.

**Comment by JoeGermuska** [comment]
You forgot https://github.com/NUKnightLab/TimelineJS3/blob/master/source/js/VCO.Timeline.js#L259-L262

**Comment by zachwise** [comment]
Oh yeah
