### ISSUE TITLE
Firefox BCE dates not showing

### ISSUE THREAD

**Issue by thejordan** [NUKnightLab/TimelineJS3#114]
When I preview my timeline in Firefox it shoes the title slide as NAN and then no dates along the bottom until CE.

Link to spreadsheet: https://docs.google.com/spreadsheets/d/1Q3qQzRQSCBPsf9x46aVjMX2SGCTkSRABlQd7xprqynM/pubhtml
![screen shot 2015-06-11 at 4 39 53 pm](https://cloud.githubusercontent.com/assets/2432672/8119131/e6e02ad2-1058-11e5-927a-c130a4316591.png)

**Comment by JoeGermuska** [comment]
Test case connecting this to #129:
`isNaN(new VCO.Date(-661039293600000).floor('millennium').getTime())` is `true` on Firefox but `false` on Chrome

**Comment by JoeGermuska** [comment]
fixed with 520b3de2db7e7434f8ec4035bf9c04b6d5140d70
