### ISSUE TITLE
Optional settings need design love

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#121]
![options design](https://cloud.githubusercontent.com/assets/741789/8169333/77549068-136e-11e5-8699-e63dd47dc021.png)

**Comment by hbillings** [comment]
Mostly will be fixed by this: https://github.com/NUKnightLab/purpleline/issues/16

**Comment by JoeGermuska** [comment]
closing because some has been fixed and this component will be evolving through other work, and will be continually 'design loved'.
