### ISSUE TITLE
JPG file media being loaded as a webpage

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#123]
`"url": "http://2.bp.blogspot.com/-dxJbW0CG8Zs/TmkoMA5-cPI/AAAAAAAAAqw/fQpsz9GpFdo/s1600/voyage-dans-la-lune-1902-02-g.jpg"` ended up loading as a webpage
![bug](https://cloud.githubusercontent.com/assets/741789/8169593/23d63ec6-1370-11e5-803f-3b15c334f1a4.png)

**Comment by zachwise** [comment]
This is also getting loaded as a wikipedia article:
`"url": "http://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/1867._The_Celebrated_Jumping_Frog_of_Calaveras_County%2C_and_Other_Sketches.djvu/page1-395px-1867._The_Celebrated_Jumping_Frog_of_Calaveras_County%2C_and_Other_Sketches.djvu.jpg"`
![bug2](https://cloud.githubusercontent.com/assets/741789/8169644/7f57ce72-1370-11e5-8499-0c7f817402e8.png)

**Comment by JoeGermuska** [comment]
fixed in ce3d825dcc9ba8d9141fe6422cb824648569a97d
