### ISSUE TITLE
Add spreadsheet option for background image or color

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#124]

**Comment by zachwise** [comment]
I added a column to the template https://docs.google.com/spreadsheets/d/1vdtiaZY1g6MADXZgoMa3pKsqg-Hz8h7JFPO3OUfDIX0/edit#gid=0

**Comment by zachwise** [comment]
It doesn't seem to show up in the template link from the website though

**Comment by zachwise** [comment]
Are we still using the template I created? https://drive.google.com/previewtemplate?id=0AppSVxABhnltdDg0WWJ0TzRPZXZRTVBwSEt6cE9GNlE&mode=public

**Comment by zachwise** [comment]
Added `Background` column in the spreadsheet template. It can contain either a color (`#333333`) or an image (`http://knightlab.northwestern.edu/wp-content/uploads/2015/03/front-page-image.jpg`) .
The spreadsheet parser should figure out which one.

**Comment by JoeGermuska** [comment]
fixed in 019cbe8
