### ISSUE TITLE
BC not showing up

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#125]
BC is not appended to dates
![bc](https://cloud.githubusercontent.com/assets/741789/8169740/2a7bc204-1371-11e5-9a32-970182cee3f0.png)

**Comment by zachwise** [comment]
Cramped text with BCE text
![bce](https://cloud.githubusercontent.com/assets/741789/8194197/9ad7dce4-143f-11e5-937c-3c5d3895c692.png)

**Comment by JoeGermuska** [comment]
maybe for minor ticks we suppress prefix/suffix? hard to think of how to express that systematically, but it makes sense to me

**Comment by zachwise** [comment]
The cramped display is now tracked on issue #130

**Comment by JoeGermuska** [comment]
ok, thanks. will close this
