### ISSUE TITLE
example timelines cut off at bottom

### ISSUE THREAD

**Issue by jywsn** [NUKnightLab/TimelineJS3#128]
The example timelines at the bottom of the timeline main webpage are cut off at the bottom in the latest version of Safari.   

For example, this:
http://timeline3.knilab.com/examples/user-interface/index.html

Looks like this:

![safari](https://cloud.githubusercontent.com/assets/1178533/8170636/c4243d54-1377-11e5-808c-efa24528076e.png)

**Comment by hbillings** [comment]
Looks like a problem caused by migrating to purpleline & its different padding/margin settings. The tabs are messed up, too.
