### ISSUE TITLE
Cramped Time Display

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#130]
Need more space when text is long
![cramped time](https://cloud.githubusercontent.com/assets/741789/8194336/a9e015de-1440-11e5-8a88-d97cd3075f69.png)

**Comment by zachwise** [comment]
Issue now is:
![google chrome](https://cloud.githubusercontent.com/assets/741789/8213725/9a95be86-14e9-11e5-85ff-32f025ff35f9.png)

**Comment by JoeGermuska** [comment]
hm. PM is definitely superfluous there. the seconds are kind of critical, and there's no sensible format for time that goes down to seconds and omits anything except the AM/PM part. Ideas?

**Comment by zachwise** [comment]
This happens with BCE too:
![google chrome](https://cloud.githubusercontent.com/assets/741789/8235104/9c9252a0-15a5-11e5-8492-66386b7b30c9.png)

**Comment by JoeGermuska** [comment]
As mentioned in #125 my proposal for that is to omit the "era" prefix/suffix (BC/BCE/AD/CE) from the minor ticks, and I'm happy to implement that piece.
