### ISSUE TITLE
Loading timeline json data as object fails

### ISSUE THREAD

**Issue by fmaturel** [NUKnightLab/TimelineJS3#134]
Loading data from a javascript object ends up with a javascript error.

`Uncaught TypeError: Cannot read property 'length' of undefinedVCO.TimeNav.VCO.Class.extend._createMarkers @ timeline.js:9200`

I've used json data coming from the official demo (http://timeline3.knightlab.com/examples/republican/index.html)

I created a plunker for this one : http://plnkr.co/edit/fEltGIwq6f53DGdwLRbr?p=preview

**Comment by JoeGermuska** [comment]
This is not yet adequately documented, but you can't pass a raw JSON object to the Timeline constructor. It should be a URL or a VCO.TimelineConfig object.

see http://plnkr.co/edit/t1IMWP?p=preview

We're working on better documentation!

**Comment by fmaturel** [comment]
Nice! Thanks for your time
