### ISSUE TITLE
Timeline fails silently on JFK assassination timeline

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#135]
I made a timeline of events at a "minute" resolution to see how formatting and other things worked.

https://docs.google.com/spreadsheets/d/1bcWDF3VCJRQ0PKQV5s2TPSxhialNi80JmtAC9zVOOCQ/pubhtml

When using this, there's an error in the [TimeScale code](https://github.com/NUKnightLab/TimelineJS3/blob/master/source/js/timenav/VCO.TimeScale.js#L166) because `pos_info` is undefined.

**Comment by zachwise** [comment]
I get `Uncaught TypeError: Cannot read property 'end' of undefined`

**Comment by JoeGermuska** [comment]
Yep. `pos_info` is undefined. it ultimately goes back to the `ConfigFactory` [handling time strings incorrectly](https://github.com/NUKnightLab/TimelineJS3/blob/master/source/js/core/VCO.ConfigFactory.js#L71). Working on that now.

**Comment by JoeGermuska** [comment]
closed in 7827910
