### ISSUE TITLE
Add `is_embed:true` to options for timeline embeds 

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#136]
This will allow me to add the border etc for embeds ref issue #116

**Comment by zachwise** [comment]
BTW this should not be a user option, but rather it should be set by the embed javascript to true

**Comment by zachwise** [comment]
If the width is set to `100%` it should also set `is_full_embed:true`

**Comment by JoeGermuska** [comment]
it already had `embed: true`. Is that obsolete? There's also a lot of carryover code from the storyjs-embed stuff that sets classes which relate to this. Is any of that critical? I'm actually hoping to totally get rid of the story-embed.js stuff and put all of the intelligence directly in the embed page, so we don't have to worry about supporting 3rd-party use of the embed JS.

**Comment by zachwise** [comment]
I don't know why we carried over any storyjs-embed stuff. There was no `embed` option in TimelineJS3.
