### ISSUE TITLE
VCO.Util.mergeData redundant with VCO.Util.extends?

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#138]
from a readthrough, it seems that [VCO.Util.mergeData](https://github.com/NUKnightLab/TimelineJS3/blob/6e6384a511bacdf080cfd5289a613986f0a81b02/source/js/core/VCO.Util.js#L80-L88) and [VCO.Util.extend](https://github.com/NUKnightLab/TimelineJS3/blob/6e6384a511bacdf080cfd5289a613986f0a81b02/source/js/core/VCO.Util.js#L7-L18) do the same thing, except that `extend` takes an arbitrary number of sources to merge into the destination while `mergeData` only takes one.

For the sake of simplifying the code, if this is true, we should eliminate `mergeData` and replace uses of it with calls to `extend`

**Comment by zachwise** [comment]
mergeData is in just about every class. I would suggest the opposite.

**Comment by JoeGermuska** [comment]
closing. not worth the trouble/risk of destabilizing something
