### ISSUE TITLE
Instrument embed page for Google Analytics including events

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#14]

**Comment by zachwise** [comment]
Events for:
* slide impressions
* complete (last slide viewed)
* left/right arrow clicks
* navigation clicks
* zoom clicks
* back to start clicks

**Comment by scott2b** [comment]
I don't think I quite know what "instrument embed page" means. Analytics should be working now by passing a ga_property_id into the properties when creating the Timeline object. There is also a track_events option which defaults to all supported events.

Currently supported events are: back_to_start, nav_next, nav_previous, zoom_in, zoom_out.

Afaik, there are not Timeline object-level propagated events for slide impressions, timeline-complete, or navigation clicks.

**Comment by thejordan** [comment]
@JoeGermuska if this looks good to you can you close?

**Comment by JoeGermuska** [comment]
Google Analytics wasn't tracking anything. This may be because no one tested embeds -- we have a dedicated "property" intended for Timeline3 embeds.

On a related note, that property was issuing a warning because of a mismatch between the tracking code on timeline3.knightlab.com and the dedicated property ID. This is because we actually want to track traffic on timeline3.knightlab.com under the common Knightlab property id (as verified f2f with Ryan Graff). I changed the "default" domain for the Timeline 3 property to cdn.knightlab.com and verified that regular traffic is being logged to the common account.

I also generated a modest amount of traffic on an embed page and will check this again tomorrow.

**Comment by JoeGermuska** [comment]
I see activity in the Chrome add-on for Analytics debugging, but I'm not seeing anything get logged. I clicked around this "embedded" timeline yesterday http://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1cWqQBZCkX9GpzFtxCWHoqFXCHg-ylTVUWlnrdYMzKUI&font=Default&lang=en&height=650&debug=true and again just now

Scott, can you pick this up again? I wish I had more to point you in the right direction.
(Also, we should be tracking a basic analytics "pageview" when the Timeline is initialized or ready. I didn't see that in the tracking, although I may have missed it.)

**Comment by JoeGermuska** [comment]
verified
