### ISSUE TITLE
Can we make docs page zendesk button say something other than "leave us a message"?

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/TimelineJS3#140]
Kinda feels like it should be more specific and less solicitous. (Working with Joe is good for my everyday vocabulary.)

**Comment by JoeGermuska** [comment]
Just FWIW it's on all pages right now -- the code is in [base.html](https://github.com/NUKnightLab/TimelineJS3/blob/master/website/templates/base.html#L43-L45)

**Comment by JoeGermuska** [comment]
More about configuring the widget https://support.zendesk.com/hc/en-us/articles/203908456

**Comment by JoeGermuska** [comment]
As best I can tell, the answer is "no, we can't." The customization of the "web widget" is a lot less than the earlier "feedback tab."
