### ISSUE TITLE
Example page problems and has scrolling

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#145]
http://timeline3.knightlab.com/examples/houston/index.html

**Comment by zachwise** [comment]
Also, old timeline embed is constrained to 600px height instead of 100%

**Comment by zachwise** [comment]
Is this really the example we're going to use?!

**Comment by zachwise** [comment]
And clicking on return to timeline 3 main page sends you to http://timeline3.knilab.com/examples/houston/timeline3.knightlab.com

**Comment by zachwise** [comment]
Also this thumbnail is not the same timeline as the one you get when you click on it:
![timeline3_intro_image](https://cloud.githubusercontent.com/assets/741789/8258422/51968070-167a-11e5-8e16-e8e7498f80dd.png)

**Comment by hbillings** [comment]
That's been the example that we've used since the beginning. Happy to change it if someone specifies what we should use. (The thumbnail is from that timeline, but it is not the title slide.)

Also, it would be helpful if issues were ticketed separately so I can keep track of what's going on where.

**Comment by JoeGermuska** [comment]
We'll have some of the Summer student fellows make new examples.

**Comment by JoeGermuska** [comment]
Also, I would be ok with taking out the old v. new comparison if that is any part of what is complicating the computation of the size the timeline should take.

**Comment by hbillings** [comment]
@JoeGermuska I could be misremembering, but I think it's making assumptions about the height of the navbar that aren't necessarily true. Removing the tabs would fix that.
