### ISSUE TITLE
Document options usable in third argument to VCO.Timeline constructor

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#147]

**Comment by zachwise** [comment]
Do you mean this? https://github.com/NUKnightLab/TimelineJS3#options

**Comment by JoeGermuska** [comment]
Yes, but I believe we should have more of that documentation on the main website. I know that's not your preference.

**Comment by zachwise** [comment]
That's what GitHub is for. With TimelineJS there are two very distinct audiences. I strongly believe we should not bog down normal people with code stuff.
