### ISSUE TITLE
Swap out default Timeline example for something else

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/TimelineJS3#149]
Summer fellows will be creating examples, so we can pick one of those to feature instead of what's there currently.

**Comment by JoeGermuska** [comment]
we never did push them all to make examples, but we can. Or you can make one, which could actually be good anyway. Traditionally we've used the first timeline people see as a hybrid of "this is an example" and "this is specifically some of its features" but we might be able to do something like we do for StoryMapJs to separate the "look, it does X" from something which feels more narrative.
