### ISSUE TITLE
If label text is already visible, don't change the size of the marker on hover

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/TimelineJS3#154]
![screen shot 2015-06-22 at 5 05 50 pm](https://cloud.githubusercontent.com/assets/509309/8294390/f811bdbe-1901-11e5-9003-c44375ebc3b1.png)

**Comment by zachwise** [comment]
Forgot to push this before I left on Monday. It would of negated the creation of the issue fd50d7bbc454a385acae962d52237b7ed4edf824
