### ISSUE TITLE
updateDisplay() doesn't seem to work on Chrome.

### ISSUE THREAD

**Issue by oragorn** [NUKnightLab/TimelineJS3#163]
Browse the demo page with chrome: http://timeline3.knightlab.com/examples/houston/index.html
Resize the browser to iphone size, and maximize back.

**Comment by zachwise** [comment]
@hbillings the solution is just to embed it at 100% height

**Comment by zachwise** [comment]
This should be an easy fix

**Comment by JoeGermuska** [comment]
I didn't realize that this ticket was here, but this should be fixed anyway.
