### ISSUE TITLE
Support for timelines with one event

### ISSUE THREAD

**Issue by RyanDale** [NUKnightLab/TimelineJS3#165]
I'm using TimelineJS3 in a web application that often initially displays the timeline with a single event and supports dynamically added events. In the original TimelineJS this worked fine, but in TimelineJS3 I get this exception ```Uncaught Error: earliest event time is before or same as latest.```

The error is triggered by the first and last event having the same start time which is unavoidable when you only have one event. Is this the desired behavior when there is only one event? I believe it would be beneficial to support timelines of all sizes. I've changed the exception conditional locally and everything seems to be working correctly. I'm including a Plunker, you can see that ```one_event.json``` fails while ```two_event.json``` works as desired.

Plunker: http://plnkr.co/edit/WwI3kaKT3Hlpjh3H4vfk?p=preview

**Comment by JoeGermuska** [comment]
You're one of the only people we've directly heard from who dynamically manipulates timelines. Given your use case, it's clear that you've identified a bug, and while I'd not imagined one-date timelines before, I get it.

**Comment by RyanDale** [comment]
I pulled the latest version of TimelineJS3 last night and made the necessary changes. Do you want me to submit a pull request?

**Comment by JoeGermuska** [comment]
Do you intend to have title slides with no actual events? The date on a title slide is disregarded, so Timeline has no reference point to create the time axis. (Also there's no marker for the title slide at this time, so all kinds of assumptions are at risk in that scenario.)

No need for a pull; the fix to support a single real event (with or without a title) was straightforward.

**Comment by RyanDale** [comment]
Each of our timelines load with at least one event in addition to the title slide. In our use case it will never be necessary to create a timeline without any events. That being said, it would be helpful if creating a timeline with no events returned a more useful error message. I believe the error returned is ```Uncaught TypeError: Cannot read property 'start_date' of undefined```. If an exception has to be thrown in that situation, one that indicated at least one event is required would be much more helpful.

**Comment by JoeGermuska** [comment]
Opening a new ticket to document/track better initialization messaging.

**Comment by JoeGermuska** [comment]
CDN has been updated with this fix
