### ISSUE TITLE
Display date column is ignored in embedded timeline.

### ISSUE THREAD

**Issue by oragorn** [NUKnightLab/TimelineJS3#167]
In the default embedded timeline [example](http://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1cWqQBZCkX9GpzFtxCWHoqFXCHg-ylTVUWlnrdYMzKUI), under the headline A Flicker Example, the display date should be "January — February", but it ignores the display date entry and instead shows "January 1, 2012 — February 1, 2012" which is the start and end date.

**Comment by JoeGermuska** [comment]
Thanks for finding this bug. Fixed in bd8a89e35c26439e000ccd8fb1189779220a447e. Should be pushed into the CDN pretty soon.
