### ISSUE TITLE
mobile styling for iOS

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#179]
using this URL http://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1cWqQBZCkX9GpzFtxCWHoqFXCHg-ylTVUWlnrdYMzKUI&font=Default&lang=en&height=650

gets this in the iOS simulator on initial load
![image](https://cloud.githubusercontent.com/assets/46313/8889427/2f2bc9a4-32a0-11e5-97db-277ecaddab47.png)

![image](https://cloud.githubusercontent.com/assets/46313/8889431/396a65e2-32a0-11e5-8b30-f1e6a797d76e.png)

**Comment by zachwise** [comment]
This is the byproduct of the change we made yesterday to fix the font issue.

**Comment by luokebi** [comment]
I wonder wether it is because IOS safari doesn't support `flex-direction`, should use `-webkit-flex-direction`.

**Comment by zachwise** [comment]
Seems to be fine:
iOS Chrome: 
![img_7369](https://cloud.githubusercontent.com/assets/741789/8909211/d8c0bf14-3445-11e5-9ab2-bfdd9e7dbfa9.PNG)

iOS Safari:
![img_7370](https://cloud.githubusercontent.com/assets/741789/8909221/dfe7a2c6-3445-11e5-946b-f97eeb5bd227.PNG)

**Comment by espressodaily** [comment]
still having problem with embed code.
I created a timeline and tried it out using the link preview and it works fine. It also works fine on iPhone and iPad.
I then used the embed code on my page but the result is no longer responsive on mobile devices. I gather I need supporting code in the hosting page

![sdo-demo-main-14e989d9b88_force_com_ignite_kufnerignites](https://cloud.githubusercontent.com/assets/5421662/8938425/7745251c-3513-11e5-9a26-75bd0af9f3be.png)
![timelinejs_embed2](https://cloud.githubusercontent.com/assets/5421662/8938426/79ee9898-3513-11e5-88e6-3079f8ae5913.png)
Google Spreadsheet
https://docs.google.com/spreadsheets/d/1YPZU7RylFPvky0k2KXOEaBILWyxjPmKJXBeAL3EeN2k/edit#gid=0

Attached screenshots. I used google chrome developer tools to show you as it works the same on actual device.

LINK PREVIEW FROM YOUR SITE
http://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1YPZU7RylFPvky0k2KXOEaBILWyxjPmKJXBeAL3EeN2k&font=Default&lang=en&height=650

LINK TO MY SITE
http://sdo-demo-main-14e989d9b88.force.com/ignite/kufnerignites

**Comment by zachwise** [comment]
@espressodaily you need to set the embed to 100% and adjust your own css appropriately.

**Comment by zachwise** [comment]
@espressodaily you should probably set the viewport also:
`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">`

**Comment by espressodaily** [comment]
Thanks.
Can you provide proper style code so I can insert?

**Comment by zachwise** [comment]
@espressodaily just take a look at any of our example pages https://github.com/NUKnightLab/TimelineJS3/tree/master/compiled/examples

**Comment by espressodaily** [comment]
Thanks. I have that. Is there other code I should be using to properly handle iOS devices? Sorry, not really much experience with responsive sites.

**Comment by espressodaily** [comment]
that styling alone doesn't make a difference.

**Comment by luokebi** [comment]
@zachwise  I think the mobile style doesn't look good. The portrait style on mobile seems to be better.
![image](https://cloud.githubusercontent.com/assets/1712033/8948825/2dc0f15c-35de-11e5-9408-9f5f682ed8eb.png)

**Comment by hbillings** [comment]
On my 5S and my iOS simulator, this is how the mobile styles look:
![screen shot 2015-07-31 at 11 21 14 am](https://cloud.githubusercontent.com/assets/509309/9011977/d7fcd75a-3776-11e5-8ffc-11a6e15c7d4c.png)

Not sure if that layout is supposed to be that way, or if the arrows are supposed to disappear. Either way, the headlines definitely need help. (Related: #78)

**Comment by zachwise** [comment]
The side by side layout is the result of flex styles on mobile safari not being obeyed. It will be fixed soon

**Comment by hbillings** [comment]
Awesome, thanks. (Also rendering that way on mobile Chrome, though I'm using an old version. I'll try updating and see what happens.)

**Comment by zachwise** [comment]
Chrome uses safari rendering.

**Comment by hbillings** [comment]
Ah, it's a mobile webkit issue. Gotcha.

**Comment by espressodaily** [comment]
So the embed code won't work properly on it's own on a mobile device?
Can you guys give me the styling I should use on the embedding site for this to work?
I  tried zachwise suggestion and it did nothing.

html, body {
        height:100%;
        width:100%;
        padding: 0px;
        margin: 0px;
      }

**Comment by espressodaily** [comment]
@zachwise just to be clear. it looks fine on your linkpreview with URL to http://cdn.knightlab.com/....
but still not when I embed on my site. I understand that I may need to add more style to support - just want to make sure you know what I see.

**Comment by hbillings** [comment]
@espressodaily Make sure your iframe uses `width="100%"`. If that doesn't do it, please post to our help forum at https://knightlab.zendesk.com/ instead of here on GitHub (which we use mostly for bug tracking). Thanks!
