### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'removeChild'...

### ISSUE THREAD

**Issue by brettshumaker** [NUKnightLab/TimelineJS3#193]
TimelineJS3 is throwing the following error when a URL used for a Flickr image 404s:

```
Uncaught NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

VCO.Media.VCO.Class.extend.loadErrorDisplay @ timeline.js:6847
(anonymous function) @ timeline.js:7200
ajaxSuccess @ timeline.js:1845
(anonymous function) @ timeline.js:1892
events.split.forEach.handler.proxy @ timeline.js:1591
```

You can see an example of this [here](http://nhcctimeline.wpengine.com/) - until the client fixes the URLs.

**Comment by JoeGermuska** [comment]
That URL requires a login.

**Comment by JoeGermuska** [comment]
@brettshumaker if you can provide a publicly accessible demonstration of this issue we'd appreciate it

**Comment by brettshumaker** [comment]
@JoeGermuska Sorry about that, I forgot there was a un/pw on that server. My client, however, has fixed their Flickr links (some of their photos were marked private). I'll get another instance of this up this weekend with some private images from Flickr and post the info here.

Thanks!

**Comment by brettshumaker** [comment]
@JoeGermuska Here's updated info where you can see this behavior.
http://timeline2015.wpengine.com/
User: Demo
Pass: timelinejs3

Let me know if you'd like to see anything else on this. Thanks!

**Comment by JoeGermuska** [comment]
Thanks, @brettshumaker that was perfect. Fix will be out soon.

**Comment by Allenivesix** [comment]
i have the same issue

**Comment by JoeGermuska** [comment]
@Allenivesix as we believe we fixed this issue in August, we would need a demonstration case to come back and do anything. Please provide a URL or a description of how someone could recreate the issue you're experiencing.

**Comment by Allenivesix** [comment]
@JoeGermuska  hello!

yes this is the link : http://www.speedythemes.net/people_tab/index.html     On Milestones TAB

**Comment by JoeGermuska** [comment]
Now that I see it, let's keep the discussion on #319
