### ISSUE TITLE
No YouTube image before playing video

### ISSUE THREAD

**Issue by keunes** [NUKnightLab/TimelineJS3#196]
Don't know if it has sth to do with the new YouTube player that Google introduced, but now the areas where the video will appear are black with a grey play button. That makes the timeline a lot less attractive compared to the TimelineJS2, where it showed the 'miniature image' of the clip. Would be nice if this background image could be re-introduced somehow.

**Comment by JoeGermuska** [comment]
See also NUKnightLab/StoryMapJS#253

**Comment by jywsn** [comment]
f41dd637f42fe45c81a664e13c9d83d9a5f21583
