### ISSUE TITLE
50% of screen

### ISSUE THREAD

**Issue by dr-martin** [NUKnightLab/TimelineJS3#203]
I want to the timeline occupy only 50% of screen, align to the left or right but the plugin take control of that.

**Comment by JoeGermuska** [comment]
I'm not sure I understand what you're asking for here.  Regarding occupying only 50% of the screen (horizontally), that is easily handled with the "width" property, which is editable in the authoring tool.
![image](https://cloud.githubusercontent.com/assets/46313/9444456/89490258-4a4c-11e5-8a0d-52a8cd57cad0.png)

Regarding aligning to the left or right, while we could in principle add that to the authoring tool, we try to limit the number of choices people are presented with in favor of making TimelineJS streamlined and straightforward. We believe that styling how the timeline appears in the page is mostly something best left to each user to tailor to his or her needs.
