### ISSUE TITLE
Media: restore Google Docs viewer for arbitrary file embeds

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#205]
[a Zendesk user](https://knightlab.zendesk.com/agent/tickets/1755) observed the loss of support for arbitrary PDF embeds via the `http://docs.google.com/viewer?url=…` mechanism.

This still works, although the web page Google used to show when no URL was passed is gone, so the long term future for this feature is not clear. Nevertheless, it wouldn't be too hard to use it as a last resort.

@zachwise any strong opinion about whether to add this back in on a similar basis as before -- late in the media type checking, if the URL hasn't been matched and it has a "good" extension, then use the viewer?

Putting in `cutover` milestone for now because it would bring closer feature parity to the current version of Timeline.

**Comment by zachwise** [comment]
SOunds good.

**Comment by JoeGermuska** [comment]
OK, it looks like `http://docs.google.com/viewer?url` sets  'X-Frame-Options' to 'SAMEORIGIN' so this strategy won't work.

Simply using an iframe to load the PDF works on all Mac OS browsers. It works on Google Chrome and Firefox on Windows. However, it does not work on IE10 or IE11.

Apparently this JS library can help? I'm thinking that we create a new PDF media type and do direct iframe embeds, and deploy that sooner than later. Then we can look at using https://mozilla.github.io/pdf.js/ for MSIE.

**Comment by JoeGermuska** [comment]
ok, i don't know what i was doing before, but i just looked at the old Timeline code and built in a branch that uses that for IE 10 & 11. So this works for PDFs.

**Comment by JoeGermuska** [comment]
this probably just needs some testing, or maybe also some assessment of the other media types
