### ISSUE TITLE
Docs: Improve formatting for JSON Format 

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#207]
http://timeline3.knightlab.com/docs/json-format.html

It's very hard to read. We should probably have something more tabular, with columns like 'key', 'required', 'type', 'notes'. It may be that 'type' and 'notes' work as well in one field since it's as much about the nature of values as their strict data type.

**Comment by hbillings** [comment]
We should probably also use the same formatting (whatever it ends up being) on this page: http://timeline3.knightlab.com/docs/options.html

**Comment by JoeGermuska** [comment]
:+1:
