### ISSUE TITLE
Option default_bg_color does not work

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#208]
There is an option, `default_bg_color`, defined (with sometimes different values) in a few places.

The only place this seems to be consulted is [VCO.StorySlider.changeBackground()](https://github.com/NUKnightLab/TimelineJS3/blob/master/source/js/slider/VCO.StorySlider.js#L303-L338), but the value isn't actually taken into account.  Also, at least some of that code suggests that 'transparent' is a good default value.

How is this intended to work? If there's a `default_bg_color` then it seems like it would always trump `transparent`. @zachwise if you can explain what you think is the right behavior, I'm happy to implement it.

**Comment by JoeGermuska** [comment]
It still doesn't seem that actually setting the value of `default_bg_color` has any effect. What am I missing?

**Comment by zachwise** [comment]
I just tested, was working fine. Did you change the value at the top class level?

**Comment by JoeGermuska** [comment]
No, I was trying to change it as an option. Is it not meant to be user configurable?

**Comment by zachwise** [comment]
option passed through when you init, right?

**Comment by JoeGermuska** [comment]
yes, as in

`new VCO.Timeline('timeline-embed', 'timeline3.json', {timenav_height_percentage: 50, default_bg_color: { r: 255, g: 0, b: 0}});`

The `timenav_height_percentage` was just there so I could see that some option was being honored. It was, and in fact, in the console, `timeline.options.default_bg_color` was the value I specified.  But slides which have no defined background come up white, not red as I'd expect.

**Comment by JoeGermuska** [comment]
user error. Sorry. Was building the JS for TimelineJS not TimelineJS3
