### ISSUE TITLE
Verify effectiveness of 'timenav_height' option

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#211]
In responding to a Zendesk question, I tried to present an example of using the `timenav_height` option: 

http://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1cWqQBZCkX9GpzFtxCWHoqFXCHg-ylTVUWlnrdYMzKUI&font=Default&lang=en&height=1200&timenav_height=600

Using the debugger, I can see that the option is passed into the constructor, but it ultimately isn't honored.

Contrariwise, the percentage can be specified as an option:
http://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1cWqQBZCkX9GpzFtxCWHoqFXCHg-ylTVUWlnrdYMzKUI&font=Default&lang=en&height=650&timenav_height_percentage=50

**Comment by hbillings** [comment]
Preliminary inspection seems to show that when passed via query string, the argument is parsed as a string instead of an integer.

**Comment by hbillings** [comment]
closed by `9e41bca27dfd8612f298274d7cca87df413d5c8a`
