### ISSUE TITLE
Possible to show multiple items

### ISSUE THREAD

**Issue by coreyworrell** [NUKnightLab/TimelineJS3#212]
How difficult do you think it would be to show multiple items at a time in the timeline. So you could have 6 items show (small image and short description) side by side in the top section, and then the bottom would behave the same as it does now.

And possibly when dragging left or right it would scroll the top as well, but at a speed that matches what the bottom timeline shows, if that makes sense (so a small scroll on the bottom timeline might make a bigger change in the top items).

Thank you.

**Comment by JoeGermuska** [comment]
This sounds like a substantial break from the design of the current Timeline. I'm sure it could be done, but I don't think we'll be the ones to do it. Sorry.
