### ISSUE TITLE
default_bg_colour undefined error when using Javascript

### ISSUE THREAD

**Issue by hazuremon** [NUKnightLab/TimelineJS3#214]
Integrate Timeline using Javascript error stopped working recently and is returning a JS error of "Uncaught TypeError: Cannot read property 'default_bg_color'" on timeline.js:11776 

The same error can be replicate when putting the sample code from Docs site into jsfiddle.
https://jsfiddle.net/dLu93y45/

**Comment by JoeGermuska** [comment]
Sorry for the inconvenience. This is fixed.
