### ISSUE TITLE
Change VCO namespace to co-exist peacefully with StoryMapJS

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#215]
It has been raised that code in the VCO javascript namespace for TimelineJS3 does not play nicely with the VCO namespace for StoryMap -- in fact, one clobbers the other.

If we are going to change this, now before we're out of beta is the time. It's a sizeable change, although more tedious with regard to file naming than actual handling inside the javascript.

@zachwise I definitely don't want to do this if you object. What do you think?

**Comment by zachwise** [comment]
I propose one of two namespaces.
KL if we want to namespace to Knight Lab or
TL if we want to namespace to the project

**Comment by JoeGermuska** [comment]
KL just kicks the same problem down the road, so I'm inclined to go with TL. If anyone with opinions is watching, now is the time to speak up.

**Comment by jywsn** [comment]
Do we still want some sort of global grouping (under KnightLab), e.g. KLTL, KL-TL, KL.TL  ?

**Comment by JoeGermuska** [comment]
As we discussed this morning, we'll stick with `TL` in place of `VCO` in filenames and in Javascript, and we'll change `vco-` to `tl-` as a prefix to all of the CSS classes.

**Comment by jywsn** [comment]
https://github.com/NUKnightLab/TimelineJS3/tree/rename

**Comment by JoeGermuska** [comment]
OK, this seems good. Let's not deploy this until next week at the soonest. We don't have a great way to spread the word about this ahead of time, but we can tweet about it again when the day comes. If anyone has other good ideas about how to help people know about it, I welcome input. In the big picture, it won't affect too many people, but it is evident from Zendesk that this is something people are doing...

**Comment by JoeGermuska** [comment]
I'm going to deploy this today. If you are an early TimelineJS3 user who is working directly with the javascript, such as instantiating a timeline with `new VCO.Timeline(...)`, or if you've customized any CSS (referring to classes with the `vco-` prefix) then you must change all references from `VCO` to `TL` and `vco-` to `tl-`.

Alternatively, you can load the last version of TimelineJS3, which still has the VCO namespace, by changing references from `latest` to `3.2.6` in the URL, such as:

`http://cdn.knightlab.com/libs/timeline3/latest/js/timeline-min.js` to
`http://cdn.knightlab.com/libs/timeline3/3.2.6/js/timeline-min.js`
and
`http://cdn.knightlab.com/libs/timeline3/latest/css/timeline.css` to
`http://cdn.knightlab.com/libs/timeline3/3.2.6/css/timeline.css`
