### ISSUE TITLE
The timeline is loaded double (double loading)

### ISSUE THREAD

**Issue by LeMagio** [NUKnightLab/TimelineJS3#216]
When using custom iframe and page with javascript implementation:

```html
<iframe src="CalendarioIntegral.html" style="width:100%; height:321px" frameborder="0"></iframe>
```

and in the `CalendatioIntegral.html`:
```html
<div id="timeline-embed" style="width:100%; height:300px"></div>
```
```javascript
var indice=0;
$.get("/MJ/calendario/procesarPeticion.aspx?t=indice_calendario", function (data) {
	indice = parseInt(data);
	var timeline = new VCO.Timeline('timeline-embed',
	'https://docs.google.com/spreadsheets/d/1XUFTrnn3o0rhkq9luxzj5Z9E3fjB1IhlGdJiZXRetW4/pubhtml',
	{
		language: "es",
		start_at_slide: indice,
		scale_factor: 1,
		timenav_height: 200,
		timenav_height_min: 200,
		marker_height_min: 30,
		marker_width_min: 250,
		marker_padding: 2,
		menubar_height: 0,
		slide_padding_lr: 70,
		initial_zoom: 3
	});
});

```
Additional information:
In the _Firebug console_ shows that effectively the get loaded two times 
![timeline double load](https://cloud.githubusercontent.com/assets/14127930/9688135/0747f782-52f3-11e5-9abe-cea4203ab3d2.png)

If you open directly `CalendatioIntegral.html` there's no double load.

**Comment by JoeGermuska** [comment]
In this simple reconstruction, I can't reproduce this error:

http://embed.plnkr.co/zlMRsYdBtVV1eiVKYP38/preview

Without access to the rest of the code which is involved, I don't know how we can conclude that this is a bug in TimelineJS3 and not something to do with the specifics of your installation. 

Is all of this JSON just a strategy to deal with #75?

**Comment by LeMagio** [comment]
Yes, the JSON code is justly for deal with issue #75. And yes I have reviewed the code outside the page that it's gonna have it and I found out that the problem is with another script running inside that page.
And reviewing the issue #75, I would like to see it in a future version of timeline.

**Comment by JoeGermuska** [comment]
@LeMagio note that we are still looking for people who want that feature to help articulate the details. Since no one at Knight Lab has a use case for it, it doesn't make sense for us to guess at what people mean. If you care to contribute to a good definition of the system behavior, it might contribute to it being added sooner than later.

**Comment by LeMagio** [comment]
My approach to achieve it is that i ordered the dates in a hard code, file, or from the JSON provided by google docs, then the timeline read those very same dates and order them likewise, and then when called the ```$.get``` a number with the index where ```server_date >= array_dates[current_index]``` is returned and provided to the option ```start_at_slide``` thats the main idea and what i needed.
