### ISSUE TITLE
Configuration option to disable auto link generation

### ISSUE THREAD

**Issue by thelinuxlich** [NUKnightLab/TimelineJS3#219]
Sometimes we don't want things like email strings turning into ```<a class="vco-makelink">``` elements

**Comment by JoeGermuska** [comment]
Would this be a global option? or a per-event option?

**Comment by thelinuxlich** [comment]
per-event would be better

**Comment by JoeGermuska** [comment]
OK. Let's make it `autolink`, default to `true`, event-only for now. I can see merit in having a global option, but then you get into precedence questions. Simpler to start with event-level now and kick the rest down the road until there's a champion.
