### ISSUE TITLE
Assume multiple 'title' types is an accident, and warn instead of interpreting literally

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#221]
Today another Zendesk user had a problem because every slide was marked as type `title`.

I seems like having multiple title slides is always going to be an accident. I would propose that after encountering the first, we treat subsequent slides as regular events, but add messages to the TimelineConfig.messages.warnings array.

In some cases it might be worth treating warnings as fatal and showing them like we do errors, instead of showing the Timeline. We could do it when `debug` is `true`. However, this involves a certain discipline over how serious a warning is, so maybe a different option, like `warnings_fatal`, or more thought about  how to handle debugging and warning...  `warnings_fatal` is probably expedient, and clear, although it does contribute to option bloat.

(once we decide how to handle warnings, we might also want to do that for events with no date -- right now it's "fatal" but we could skip them and warn about them. Some people have used rows as separators with text in the headline but no date and no expectation that anything would be shown.)

**Comment by zachwise** [comment]
We could also highlight the row in the spreadsheet template to possibly make it look different from the other rows. This might help cut down on accidents.

**Comment by JoeGermuska** [comment]
not a bad idea, although I don't know if we can give them information about why the row is colored -- and if the person does it for all rows, many of them will just skate past it with a ¯\ _(ツ)_/¯

If we pursue the Google Add-ons idea referenced in #198 we would have lots of opportunity to give feedback.

**Comment by hbillings** [comment]
The timeline now adds a warning if multiple title slides are detected and then renders the first title row as the title slide with the others as regular slides. However, warnings don't seem to surface anywhere. I originally pushed it as an error, but since errors are fatal, that obviously didn't actually render a timeline. 

(The convo about how to surface warnings and if/when they're fatal should prolly be its own ticket.).
