### ISSUE TITLE
`tl-storyslider` class gets added twice

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/TimelineJS3#223]
<img width="454" alt="screen shot 2015-09-15 at 11 38 40 am" src="https://cloud.githubusercontent.com/assets/509309/9883208/5f2f5900-5b9e-11e5-89b4-4e32cb605391.png">

**Comment by JoeGermuska** [comment]
This traces back to https://github.com/NUKnightLab/TimelineJS3/blob/master/source/js/slider/TL.StorySlider.js#L406

We could probably start using `element.classList.add(...)` now that we don't support IE9, but we also have a method in [`TL.DomUtil`](https://github.com/NUKnightLab/TimelineJS3/blob/master/source/js/dom/TL.DomUtil.js#L86) which handles this but must have been forgotten here. I fixed it here and in a few other places.
