### ISSUE TITLE
Old spreadsheet dates are acting weird

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#230]
Might have something to do with eras being interpreted as events?

![image](https://cloud.githubusercontent.com/assets/741789/9963346/77806da6-5df0-11e5-9cd4-fb4d920333ae.png)

Original
https://cdn.knightlab.com/libs/timeline/latest/embed/index.html?source=0AssbCmNZsEBZdEtrVk8zY3dTX2tqZHRYckcwZ21UeHc&font=Bevan-PotanoSans&maptype=SATELLITE&lang=en&height=800

TL3:
http://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=0AssbCmNZsEBZdEtrVk8zY3dTX2tqZHRYckcwZ21UeHc&font=Default&lang=en&initial_zoom=2&height=650#event-timeline-movie-theater-shooting

**Comment by zachwise** [comment]
Seems to happen when there is a start_date and end_date that are exactly the same

**Comment by zachwise** [comment]
Here's the spreadsheet: https://docs.google.com/spreadsheets/d/18kvrl-EKcuWo4i5FM36erS04fiEDuU8g4pmQaixp6c8/edit#gid=0

**Comment by JoeGermuska** [comment]
this is what I get running locally:

![image](https://cloud.githubusercontent.com/assets/46313/9963473/0f1ce608-5df1-11e5-8fc9-6e250458936a.png)

so your analysis is right. I have merged the era tag and I'm going to push it to master and deploy an update to TimelineJS3

**Comment by zachwise** [comment]
Seems to happen when there is a start_date and end_date that are exactly the same and not related to eras

**Comment by zachwise** [comment]
That event is 85,568px wide!

**Comment by zachwise** [comment]
Nevermind, spreadsheet had a typo: 4/23/2102
