### ISSUE TITLE
Soundcloud example in spreadsheet template no longer exists

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#234]
We need to replace it with another soundcloud link. 
![google chrome](https://cloud.githubusercontent.com/assets/741789/10023455/de37e748-6117-11e5-8ecb-8e32f817ec26.png)

**Comment by JoeGermuska** [comment]
fixed with https://soundcloud.com/conferenceofthebirds/tuesday-02-11-pm

**Comment by zachwise** [comment]
Is that the one used on the landing page too? http://timeline3.knightlab.com/

**Comment by JoeGermuska** [comment]
ah, no, but I updated that also.
