### ISSUE TITLE
Icons in examples from Compiled Directory don't show.

### ISSUE THREAD

**Issue by curiculla** [NUKnightLab/TimelineJS3#237]
Recently downloaded a zip of TimelineJS 3.  When I try to run examples in the examples subdirectory of the 'compiled' directory the icons don't show.  I'm using Ubuntu (Bodhi) for my experimenting with TimelineJS.

Error output from web console is:
downloadable font: download failed (font-family: "tl-icons" style:normal weight:normal stretch:normal src index:1): status=2147500037
source: file:///home/username/experiments/TimelineJS3/compiled/css/icons/tl-icons.ttf timeline.css:19
downloadable font: download failed (font-family: "tl-icons" style:normal weight:normal stretch:normal src index:2): status=2147500037
source: file:///home/username/experiments/TimelineJS3/compiled/css/icons/tl-icons.woff timeline.css:19
downloadable font: no supported format found (font-family: "tl-icons" style:normal weight:normal stretch:normal src index:4)
source: (end of source list)

**Comment by JoeGermuska** [comment]
Timeline is not developed for use on a local filesystem. A number of features, most importantly including loading data from an external URL, depend on Timeline being loaded through an HTTP server. 

You can run a simple web server with node, or python, or the commercial web development tool CodeKit, which is the preferred tool of TimelineJS's primary architect, @zachwise.

**Comment by curiculla** [comment]
Thank you.Joe.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Virgin Mobile network.                                                                                                                                                                                                                From: Joe GermuskaSent: Tuesday, September 22, 2015 12:38 PMTo: NUKnightLab/TimelineJS3Reply To: NUKnightLab/TimelineJS3Cc: curicullaSubject: Re: [TimelineJS3] Icons in examples from Compiled Directory don't show. (#237)Timeline is not developed for use on a local filesystem. A number of features, most importantly including loading data from an external URL, depend on Timeline being loaded through an HTTP server. 

You can run a simple web server with node, or python, or the commercial web development tool CodeKit, which is the preferred tool of TimelineJS's primary architect, @zachwise. 

—Reply to this email directly or view it on GitHub.
