### ISSUE TITLE
Typography problems with Romanian Diacriticals

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#244]
A user submitted a [Zendesk support ticket](https://knightlab.zendesk.com/agent/tickets/1905) regarding problems with [this timeline](http://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1m0a6nbeT-zaENR5UIhJgoa-qx0HftUBpLyUccFblAnM&font=Default&lang=ro&initial_zoom=0&height=400)

This is the image he provided:
![image](https://cloud.githubusercontent.com/assets/46313/10054196/7d904e1a-61f5-11e5-90b0-660bee95fb0f.png)

When I load it on Google Chrome (Mac OS, 45.0.2454.93), there is no issue:
![image](https://cloud.githubusercontent.com/assets/46313/10054217/9f970f3a-61f5-11e5-8f69-a62c83952888.png)

When I load it in Safari 8.0.8, there is no issue:
![image](https://cloud.githubusercontent.com/assets/46313/10054252/d31c1efe-61f5-11e5-9b7d-858f747462ac.png)

When I load it in Firefox (40.0.3, Mac OS), the problem is more aggravated that the original example:

![image](https://cloud.githubusercontent.com/assets/46313/10054288/fbd6bdb8-61f5-11e5-87b3-29e6f96f82e2.png)

Not really sure what next steps are, but wanted to log it.

**Comment by mazhang2718** [comment]
This seems like a problem with Google Fonts, but [there doesn't seem to be any updates on this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1122290) from Mozilla...

**Comment by thehandsomepanther** [comment]
Should we close out this issue, @JoeGermuska ?

**Comment by JoeGermuska** [comment]
Since this problem is specific to Firefox and seems to relate to an [open Firefox bug](there doesn't seem to be any updates on this bug), closing this as WONTFIX. 

From reports, this seems to be common to Google Fonts, which means that all Timeline font options will manifest this problem. Working around this would require [instantiating a timeline](http://timeline.knightlab.com/docs/instantiate-a-timeline.html) in a page directly (it's not currently possible to selectively override CSS using iframe embeds) and then to override the font definitions. See the `[less](https://github.com/NUKnightLab/TimelineJS3/tree/master/source/less)` directory in the Git repository or modify one of the [font files](https://github.com/NUKnightLab/TimelineJS3/blob/master/compiled/css/fonts/font.abril-droidsans.css) generated from those LESS files.
