### ISSUE TITLE
Presentation of Timeline on site

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#246]
If we're not going to have the timeline on the homepage go 100%, we should add a border to it and some margin at the top of it. I had no idea that we were doing a cutover yesterday and this is the first time I'm seeing this!

![google chrome](https://cloud.githubusercontent.com/assets/741789/10075011/1e8db41c-6299-11e5-9880-14a66c9c884d.png)

**Comment by zachwise** [comment]
![issues](https://cloud.githubusercontent.com/assets/741789/10075102/949b101e-6299-11e5-9cbf-73b2c031324d.png)

**Comment by JoeGermuska** [comment]
sorry for the surprise. we talked about it at scrum, but I could have made it more clear.

**Comment by zachwise** [comment]
On the old site and on StoryMap, we made the height based on window vh and ran it 100% wide. I think if we run it 100%w and not quite 100vh so we can see some of the text above or below we'd have a pretty good presentation across browser sizes / devices.

**Comment by hbillings** [comment]
The timeline runs full width at 1200px. It needs a max width at some point, or it's just ridiculous.

**Comment by zachwise** [comment]
Depending on the width height ratio, something above 1200px would probably still look pretty good. It's a matter of opinion.

**Comment by hbillings** [comment]
I bumped it to 1600px and evened out the margins. I'll push so you can take a look.

**Comment by zachwise** [comment]
What about the vh issue?

**Comment by zachwise** [comment]
Here's what we used for storymap
```
var e = $(window).height(),
  t = $("#homepage-storymap");
  t.height(e - 20);

  $(window).resize(function() {
     e = $(window).height();
     t.height(e - 20);
    storymap.updateDisplay();
  })
```

**Comment by zachwise** [comment]
I rewrote the one from storymap to be a little better and ready for timeline
```
	var win_height = $(window).height(),
		demo_timeline = $("#demo iframe"),
		timeline_height = (win_height/4) *3;

	if (timeline_height < 650) {
		timeline_height = win_height;
	}
	demo_timeline.height(timeline_height);
	

	$(window).resize(function() {
		
		win_height = $(window).height();
		timeline_height = (win_height/4) *3;
		if (timeline_height < 650) {
			timeline_height = win_height;
		}
		demo_timeline.height(timeline_height);
		
	})
```

**Comment by scott2b** [comment]
pre-orangeline website issue. closing
