### ISSUE TITLE
Section breaks need to be more clear

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#247]
![section breaks](https://cloud.githubusercontent.com/assets/741789/10075136/c6e1f510-6299-11e5-9518-f118d8e0f797.png)

**Comment by zachwise** [comment]
More margin and a slight shift in background tone would probably do wonders here.

**Comment by scott2b** [comment]
Given this seems to have gone unaddressed for a year and we will be starting Orange Line based updates this week, closing this out with the expectation that there will be a full review of the new style changes
