### ISSUE TITLE
Anchor links: Page jumps

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#249]
I thought we agreed to have smooth scrolling to sections from the navigation. Right now it jumps.
![image](https://cloud.githubusercontent.com/assets/741789/10075210/2bea976e-629a-11e5-83b3-2486f02d917f.png)

**Comment by hbillings** [comment]
So I factored the scrolling out of `main.js` into `smoothscroll.js` to include it on docs pages, and it doesn't seem like the secondary file is being included on prod. It's in `base.html` here https://github.com/NUKnightLab/TimelineJS3/blob/master/website/templates/base.html#L78 and works locally for me. @JoeGermuska, any idea what I need to do to get this to propagate?
