### ISSUE TITLE
Add timeline version to optional embed settings?

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#251]
Might be useful for many in transition.
![timeline version](https://cloud.githubusercontent.com/assets/741789/10076810/f9ddf29e-62a2-11e5-93ec-b72af8e0156b.png)

**Comment by JoeGermuska** [comment]
I'm not really persuaded that anyone making a new timeline needs the old one, and if they're using the new spreadsheet template it won't work anyway.

I'd like to verify that there are transitional problems between getting tangled up in serving the old stuff...

**Comment by zachwise** [comment]
Closing this. If we see problems in transition we can reopen.
