### ISSUE TITLE
Add back examples from old site?

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#252]
I think the breadth of examples we had on the old site really helped tell people how timeline is used across different types of organizations. I'd hate to see that totally lost just because they're using an older version of Timeline.

**Comment by JoeGermuska** [comment]
I'd be OK with adding a few of them, but I'd also like to just prioritize finding new ones, which @rcgraff can help with when he's back with ONA.

But yeah, we could add maybe two rows of our favorites in the meantime...

**Comment by zachwise** [comment]
It's not so much the actual examples, but the brands associated with those examples being displayed that I think is significant. Similar to how many other products communicate how widely used their services/tools are used. For example: 
![image](https://cloud.githubusercontent.com/assets/741789/10078229/647b03ca-62a9-11e5-9f88-1626a20794c2.png)

**Comment by JoeGermuska** [comment]
agreed. but for example the tutorial about how to style a timeline is probably just confusing.

**Comment by hbillings** [comment]
Could we maybe do something under the examples with logos of orgs that have used Timeline in the past? Then as new examples roll in, we can phase that out. Just an idea.

**Comment by zachwise** [comment]
That's sorta what I was getting at. I think a collection of logos of the organizations that use Timeline below examples would be perfect.

**Comment by JoeGermuska** [comment]
I've asked @thehandsomepanther to copy over examples from the old version of TimelineJS (but, to document f2f conversations, we won't bother with making a logo panel as above -- we'll just add interesting examples, mostly with inline logos.

**Comment by zachwise** [comment]
Let's add one of the big China ones from sina too:
This one had 30,978,599 views! http://news.sina.com.cn/iframe/timeline/2014/0311/1.html It would be great to mention that somehow

**Comment by zachwise** [comment]
This one had around 16 million: http://news.sina.com.cn/iframe/268/2014/0219/iframetl.html

**Comment by zachwise** [comment]
Here's a logo:
![image](https://cloud.githubusercontent.com/assets/741789/10146382/31ca19b4-65ee-11e5-98c0-7a7357c6e2d0.png)

**Comment by JoeGermuska** [comment]
I like the idea of a little visual marker like ">30M views" if we could make something that looked good. we might want to get counts for others. or we could have a space for a generic message... like this, so be improved by those of you who make things look good. I don't know if it would look weird to have those tags only for some, but I don't know what we'd say about some of them too...

![image](https://cloud.githubusercontent.com/assets/46313/10202152/291b9ac6-6775-11e5-9262-edcead6d70f0.png)

**Comment by JoeGermuska** [comment]
Oh, also, @thehandsomepanther while you're in there, can you improve the spacing between the logo and the title/link?

**Comment by thehandsomepanther** [comment]
resolved by cd50f74df8b8f4f072d5308b0656b9a9b9c08d8b
