### ISSUE TITLE
IE9: Ajax doesn't work

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#258]
No Timelines loading external data work with IE 9. (That is, most of them.) There are known issues with how IE9 deals with CORS requests

Timeline's Ajax functionality comes from Zepto, whose Ajax tools are copied into `TL.Data` and ultimately exposed as `TL.getJSON` and `TL.ajax`

At the root, our AJAX request throws an exception with the message "Access is Denied"

http://stackoverflow.com/questions/10232017/ie9-jquery-ajax-with-cors-returns-access-is-denied

**Comment by zachwise** [comment]
In the old timeline I handled this:
https://github.com/NUKnightLab/TimelineJS/blob/master/source/js/Core/Core/VMM.Library.js#L127
```
VMM.getJSON = function(url, data, callback) {
		if( typeof( jQuery ) != 'undefined' ){
			jQuery.ajaxSetup({
			     timeout: 3000
			});
			/* CHECK FOR IE
			================================================== */
			if ( VMM.Browser.browser == "Explorer" && 
				 parseInt(VMM.Browser.version, 10) >= 7 && 
				 window.XDomainRequest && 
				 url.match('^https?://')) {
				trace("old IE JSON doesn't like retrieving from different protocol");
					var colon = url.indexOf(':');
					url = url.substr(colon+1); 
			}
			return jQuery.getJSON(url, data, callback);

		}
	}
```

**Comment by zachwise** [comment]
Whoops, no I didn't

**Comment by zachwise** [comment]
Weird, because I tested IE9 awhile back and it worked fine. IE9 in compatibility mode though would fail.

**Comment by JoeGermuska** [comment]
I thought something like that might be the trick, but I don't think it's possible to read Google Spreadsheets via `http` so...

**Comment by JoeGermuska** [comment]
Might be we have to use JSONP, which seems like a serious pain

http://stackoverflow.com/questions/15792107/google-spreadsheet-ie-error-using-ajax

**Comment by JoeGermuska** [comment]
In the last year, IE 9 traffic has accounted for less than 1% of sessions on our embeds. We can't expend the energy required to continue to support it. Closing this and #257.
