### ISSUE TITLE
Automatically increase timenav height when groups demand many rows

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#259]
When people use more than about 4 groups, the allocation of at least one row per-group can lead to crowding in the timenav section.

We should take the number of rows into account and make more space available.

**Comment by JoeGermuska** [comment]
I'm also seeing some surprising interactions when I set some of the options which could otherwise address this.

[This example timeline](http://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1OQCXIQoeMUbeIE3KdKijQhFvgit37m6Sy6S07gAE6fU&font=Default&lang=en&initial_zoom=2&height=650) has 8 groups (including one 'blank') 

[This is the same timeline, with timenav_height=300](http://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1OQCXIQoeMUbeIE3KdKijQhFvgit37m6Sy6S07gAE6fU&font=Default&lang=en&initial_zoom=2&height=650&timenav_height=300) Only four group labels are displayed. The markers are displayed as they are otherwise, so some end up in the "wrong" row.

[This is the same, with timenav_height_percentage=50](http://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1OQCXIQoeMUbeIE3KdKijQhFvgit37m6Sy6S07gAE6fU&font=Default&lang=en&initial_zoom=2&height=650&timenav_height_percentage=50)  It doesn't seem to take up 50%, and it seems like what extra space is available is allocated to the "blank" group

Adjustments to `marker_height_min` change the display of the markers, but not the rows they sit in.

**Comment by zachwise** [comment]
We should test this with an example that has < 8 groups

**Comment by JoeGermuska** [comment]
I tried this with a test timeline and it seemed OK, but when I tried the example from above, I see a few cases where markers overflow group "lanes." Is that something we can control?

![image](https://cloud.githubusercontent.com/assets/46313/10177035/9b649564-66bd-11e5-9337-2f5522ff43fa.png)

**Comment by zachwise** [comment]
Thanks, probably an error in my height calculation.
