### ISSUE TITLE
IE8 Message for incompatability needs created: IE8 Doesn't like `VCO.Language.default` for some reason

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#26]
![ie8 timelinejs3](https://cloud.githubusercontent.com/assets/741789/4188262/cb2f92b2-3770-11e4-8e23-62fa82529072.png)
Amazing debug tools, amiright

and I think we need to support IE8 because:
![ie versions](https://cloud.githubusercontent.com/assets/741789/4188333/7eb97564-3771-11e4-8e9f-ce7f0f501319.png)

This is gonna be fun. This is probably the first of many chasing ie8 down the rabbit hole.

**Comment by JoeGermuska** [comment]
I'm calling it. We're not supporting IE8 for TimelineJS 3. Time to move on. Folks who need Timeline on IE8 can use the old version.
