### ISSUE TITLE
Add notes to example timeline

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#260]
Similar to StoryMap using 'tl-note' class
`<span class="tl-note">The note</span>`

**Comment by JoeGermuska** [comment]
Looks kinda rough on top of backgrounds:
![image](https://cloud.githubusercontent.com/assets/46313/10147742/83b383d0-65f5-11e5-890f-243ebd6c6583.png)

**Comment by scott2b** [comment]
There seem to be notes now. Is this done?

**Comment by JoeGermuska** [comment]
yep
