### ISSUE TITLE
Re-introduce Bevan-PontanoSans font combo

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#261]
A [Zendesk user](https://knightlab.zendesk.com/agent/tickets/1926) requested the return of Bevan & Potano Sans for the new TimelineJS.

![image](https://cloud.githubusercontent.com/assets/46313/10145943/c4900112-65eb-11e5-86f3-706cdd19a5fd.png)

**Comment by zachwise** [comment]
Added via: d94a03ac2202b9519cfbffc967596699f811dfc4
We need to add it to the website.
