### ISSUE TITLE
Support the same image URLs for background images that are supported by media types

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#268]
It's far from obvious to users that URLs for the background must be direct image links, while URLs in the media column get "interpreted".

It seems like we could probably handle that for people. Worth a look.

**Comment by jywsn** [comment]
The background on the slides are set using css, so the value has to be an image URL. I'm assuming any media type that ultimately resolves to an `<img>` should be allowed?

This seems to be the list:

TL.Media.Flickr.js
TL.Media.Image.js
TL.Media.Instagram.js

**Comment by JoeGermuska** [comment]
yeah, that was my idea. There's also `TL.Util.transformImageURL` which handles dropbox URLs (and which may turn out to be a bad hack that should be handled some other way...)

**Comment by jywsn** [comment]
So this issue with using an image from Flickr or Instagram is... what... picking the right size (since images can have multiple sizes)?  And then you'd want to potential reload a different size if the size of the slide area changes?

**Comment by jywsn** [comment]
ref: https://github.com/NUKnightLab/TimelineJS3/tree/media-background

**Comment by JoeGermuska** [comment]
looks good. thanks!

**Comment by scott2b** [comment]
@JoeGermuska can you clarify the above conversation? Was there a PR to review for this? was this issue resolved?

**Comment by JoeGermuska** [comment]
There was no PR, but yes, these features have been in place since the issue was closed, in c0ff038daeb2d9aebd0ac5994ba623dd750aac9b possibly among others.   [Here is where it is being applied](https://github.com/NUKnightLab/TimelineJS3/blob/master/source/js/slider/TL.Slide.js#L201) to supporting `TL.MediaType` resolving a special URL into something which can be used for a background. 

[This suggests](https://github.com/NUKnightLab/TimelineJS3/blob/master/CHANGELOG#L30) that #332 should have been closed already. But also, easy enough to experimentally verify that a Flickr or Instagram URL "works" for a thumbnail, or if not, then #332 isn't done.

**Comment by thehandsomepanther** [comment]
@JoeGermuska closing this since you said it's been resolved
