### ISSUE TITLE
Have TimelineConfig validate date parts as integers

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#269]
Someone filed a support ticket because she was using month names. Timeline was using parseInt and ended up treating them all as January.

We should verify that month, date, and year are integers and log an error otherwise.

**Comment by jywsn** [comment]
Is this the problem?  

https://github.com/NUKnightLab/TimelineJS3/blob/media-background/source/js/date/TL.Date.js#L115-L117

Basically, we should be distinguishing between an invalid input string and an empty input string?

**Comment by JoeGermuska** [comment]
yeah, i think instead of isNaN it could be something like

    var x = TL.Util.trim(_date[DATE_PARTS[ix]]);
    if (!x.match(/^\d*$/)) { //error else parse it and store it

**Comment by jywsn** [comment]
db4bcbcc45cf47b4d0ed9d83724218ad70523726

**Comment by JoeGermuska** [comment]
this was made live in 3.3.9 but the issue wasn't closed
