### ISSUE TITLE
No visible difference when landscape mode is used

### ISSUE THREAD

**Issue by jacalata** [NUKnightLab/TimelineJS3#271]
I have been playing with a timeline and found that setting the layout: landscape  or layout: portrait option does not seem to change anything about the display. I could repro this using the url options on one of your example links. The below image is a side-by-side view of these two urls, one with landscape and one with portrait.

https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1cWqQBZCkX9GpzFtxCWHoqFXCHg-ylTVUWlnrdYMzKUI&font=Default&lang=en&initial_zoom=3&height=650&hash_bookmark=false&layout=landscape#event-google-spreadsheet-example

https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1cWqQBZCkX9GpzFtxCWHoqFXCHg-ylTVUWlnrdYMzKUI&font=Default&lang=en&initial_zoom=3&height=650&hash_bookmark=false&layout=portrait#event-google-spreadsheet-example

![image](https://cloud.githubusercontent.com/assets/2009720/10359655/5764e7d0-6de6-11e5-8721-d8c9a5e91e54.png)

**Comment by zachwise** [comment]
`Layout` is not meant to be a user configurable option. It is a way of tracking the state and context of the timeline's layout. We will take a look at separating those from options.
