### ISSUE TITLE
Large timelines crash Chrome?

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#274]
A user reported that [this timeline](https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1ntHP4sWS_ZhPYRw17aL_OvuhfXvN4xH_fHewHcqKCVA&font=Default&lang=en&initial_zoom=2&height=650) resulted in "oh snap" messages from Chrome, leading the publisher to scrap the Timeline from the story.

We should try to reproduce. I haven't seen it yet.

**Comment by zachwise** [comment]
Just went thru most of it. Not problems.

**Comment by zachwise** [comment]
Part of the problem could be the SUPER LARGE IMAGES they're sometimes using: http://i.imgur.com/y3yYOTb.jpg 
Do people not size things for the web anymore?

**Comment by ashwu** [comment]
I've reproduced it a few times on Chrome (on incognito too in case things were cached) and Safari; no crashes. Could possibly be the Windows 7 Pro vs Mac OS?

**Comment by JoeGermuska** [comment]
closing as unreproducible. we'll see if it comes back.
