### ISSUE TITLE
1px white border on timeline

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#275]
[Zendesk ticket 2050](https://knightlab.zendesk.com/agent/tickets/2050) reported a 1 pixel line where the Timeline's background is visible in an `iframe` embed. @zachwise found that "storyslider has a position of 1px top that is causing the line"

He'll tidy that up when he can.

**Comment by scott2b** [comment]
This was fixed by 6616ad21e14cb2ce48a894c8d46f48d56dce24f8
