### ISSUE TITLE
Enable I18N on StorySlider, migrate 'swipe to navigate' message to L10N files

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#276]
The "swipe to navigate" message is [hardcoded in English in TL.StorySlider](https://github.com/NUKnightLab/TimelineJS3/blob/master/source/js/slider/TL.StorySlider.js#L444)

We should migrate that to the JSON L10N files. It looks like TL.StorySlider doesn't use the I18N mixins yet, but hopefully that's straightforward.

It's OK to put the entire string (markup and all) into the messages file as it is. I don't think it's worth the trouble right now to break it down and have a mechanism for building up the markup later.

**Comment by jywsn** [comment]
46270d1166d80d391d509357fe21437cdd5c6fb8
