### ISSUE TITLE
Tweet not loading

### ISSUE THREAD

**Issue by cemrich** [NUKnightLab/TimelineJS3#282]
I want to embed a tweet with following url: "https://twitter.com/miracula_de/statuses/387575437267722240", but it does not show up. Instead the error message ```timeline.js:8182 Uncaught ReferenceError: url is not defined``` is thrown.

I think this line contains an error: [TL.Media.Twitter.js#L22](../blob/2f910baeb2d59699f44eb2294f33f4f32557c551/source/js/media/types/TL.Media.Twitter.js#L22)
```url.match("statuses\/")``` should read ```this.data.url.match("statuses\/")``` instead.

**Comment by JoeGermuska** [comment]
closed with 25c2cf8d7b61378a1b1f342e09eeb2aec346b7e6
