### ISSUE TITLE
Can the marker headline text differ from the slide headline text?

### ISSUE THREAD

**Issue by gitgrimbo** [NUKnightLab/TimelineJS3#283]
In the example below, does "A Musical Heritage" have to be the text in both the marker headline text and the slide headline text?

I would like to have different text - a shortened version in the marker, and the full version in the slide.

![timelinejs3-markers](https://cloud.githubusercontent.com/assets/1020541/10563912/cba2b9a4-7595-11e5-91af-f2bef684e416.png)

**Comment by JoeGermuska** [comment]
This is not supported, and is unlikely to be supported. If the labels are different, how would a reader know that they go together?

**Comment by gitgrimbo** [comment]
Hi. A reader would know the labels go together because of an obvious (to the reader) correspondence between the the marker text and slide headline text (within the context of a specific timeline).

I appreciate this might not be the case for all timelines, but I have shortened versions of the headline which would make ideal marker text, and my readers would immediately and unambiguously recognise these as corresponding to the relevant main slide headline.

If you would rather not change the TimelineJS JSON data format, do you have any suggestion as to the best way to modify the headline DOM when a slide changes in order to modify the headline?

**Comment by JoeGermuska** [comment]
From a design perspective, I'd discourage assumptions about what is obvious to readers, but of course, I'll concede that it's possible. 

In any case, I wouldn't endorse trying to muck with the DOM to achieve this end. Even if TimelineJS were that well-architected, it's a royal hack, and I'm afraid this is the kind of thing that TimelineJS isn't well-factored to support.

I'd consider an optional `marker_label` property in the JSON format, but I definitely do not expect that we'd add this to the spreadsheet format.
