### ISSUE TITLE
How to refresh timeline when one event is modified/updated on JSON?

### ISSUE THREAD

**Issue by lerayj** [NUKnightLab/TimelineJS3#286]
Without reloading page obviously...
Is that possible?

**Comment by JoeGermuska** [comment]
I'm afraid it would be difficult. As it is now, the Timeline doesn't act as a standard "view" on a "model" of events; instead, it processes the events at initialization time, copying data into the various DOM elements. It isn't as careful as it could be about encapsulating certain kinds of data. At least, last time I started looking through it, it seemed like there would be a lot of risk in trying to move all the parts around to get to the point where you could really set it up as an observer to property changes on the original data.

We would like to support what you request, but odds are good that trying to get there would break subtle things. I'm going to leave this open, but it could be a long time in coming.

**Comment by lerayj** [comment]
<iframe src="//giphy.com/embed/dBpDdp7GCokcE" width="480" height="198" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="http://giphy.com/gifs/lol-fun-amazing-dBpDdp7GCokcE">via GIPHY</a></p>

We found a way. :sunglasses:

**Comment by Yamakaky** [comment]
I have the same problem. I would like to be able to change the data timelinejs is rendering. Maybe by implement a method to change the JSON after the creation of the timeline ?

**Comment by lerayj** [comment]
You can't do that, the timeline won't be re draw. But like I said you can trick it by directly access to the _storyslider._slides. You could also overload HTML with JQuery.
Working well for me.

**Comment by peyruchat** [comment]
+1

**Comment by JoeGermuska** [comment]
So, it behooves me to point out that the "_" convention for those symbol names is to make it quite clear that there's no guarantee those implementation details won't change and bring your fix crashing down -- but :+1: for the hacker spirit.

I'll also point out that if your slides are changing, you probably also want to consider making updates to `_timenav._markers`

**Comment by lerayj** [comment]
I do not have any trouble with this "dirty quick fix".

I do not use marking, but you're true, if you want it, this would be a little more tricky.

**Comment by durriyajamali** [comment]
@lerayj, I want to change the datasource, the json file without re-initializing everything, so can you share some of your code., of how you overloaded your _storyslider._slides data and/or make an update with Jquery.

**Comment by rmarinho** [comment]
:+1: for a easy way to do this..

**Comment by fongfai** [comment]
> <iframe src="//giphy.com/embed/dBpDdp7GCokcE" width="480" height="198" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
> [via GIPHY](http://giphy.com/gifs/lol-fun-amazing-dBpDdp7GCokcE)
> 
> We found a way. 😎
> 
> you could just overload your _storyslider._slides data and/or make an update with Jquery.

hi, your link cannot open, could you check it ? thanks a lot , i am blocked on this problem too😭
