### ISSUE TITLE
Validate that eras have end dates

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#287]
a Zendesk user inadvertently created a timeline with almost all rows marked as 'era'. This resulted in an uncaught exception, because Eras are assumed to have end dates.

We should validate that all eras have start and end dates in the TimelineConfig validation, so that at least a clear message is shown. The message may not help someone who doesn't realize that they are misusing eras, but it is better than an uncaught exception.

**Comment by JoeGermuska** [comment]
We've had at least one Zendesk question about indeterminate ends for eras (as in "to the present"). It would probably not be appropriate to simply take today's date as the end date, so we may need to figure out some kind of styling for this case instead of enforcing end dates?

**Comment by JoeGermuska** [comment]
Another odd issue around this: we routinely drop end dates that are the same as start dates. This can lead to eras with spreadsheets which have both configured still leading to the `TypeError: Cannot read property 'getTime' of undefined` message. 

This will kind of wash out as we do this validation, but it took me a while to figure out why someone had a value in the 'end date' column but was still getting this message. (In this specific case, the person had mistakenly entered `era` in almost every row for the `type`, which was not their intention.

**Comment by JoeGermuska** [comment]
hey @ashwu  this is a pretty easy one while your head is still in 'validation' space

**Comment by ashwu** [comment]
Pushed to the verify-headers branch.
Pull request here: https://github.com/NUKnightLab/TimelineJS3/pull/307
