### ISSUE TITLE
question: Bower support?

### ISSUE THREAD

**Issue by angelxmoreno** [NUKnightLab/TimelineJS3#289]
I'm curious to know what the authors' thoughts are on providing bower support.

**Comment by JoeGermuska** [comment]
We don't use bower routinely for Knight Lab projects, but I feel like every time I look into it, I mostly see [warnings that it's dead](https://github.com/rackt/redux/issues/944#issuecomment-154858804), or questions about whether it is dead, or [suggestions that it should merge with npm](https://github.com/bower/bower/issues/1520)... which doesn't motivate me to invest a lot of energy. 

My read is that we are better off supporting npm (see #308). I'll leave this open for a while to see if anyone wants to champion Bower, but if there's no clear momentum for it in a month or two, we'll close this.

**Comment by angelxmoreno** [comment]
Many projects are indeed moving from other package managers ( including Bower ) to NPM. I apologize for not being clearer. What I was implying was using ANY package manager. Some open source projects have even gone as far as offering bower AND npm. The setup is very easy and I do not expect that work to fall on the KnightLab team. After all, the project is open source and what better way to say "thank you for your contribution" than pull request? :smile:

**Comment by angelxmoreno** [comment]
:+1: for NPM

**Comment by JoeGermuska** [comment]
Closing this in favor of #308
