### ISSUE TITLE
unique_id behavior after manipulation

### ISSUE THREAD

**Issue by lerayj** [NUKnightLab/TimelineJS3#290]
When you remove event with removeId(), and try to add new event with same id than the old one, timelineJs generate a new one.

eg:

```javascript
timeline.removeId("1");
timeline.add({
//usual event
unique_id= "1"
});

timeline.on("added", function(data) {
    console.log("added: ", data);
});
```
**output:** 
added: 1-2

I think remove the id on internal behavior has been forgotten.
It should be 1

**Comment by cyberhorse** [comment]
This is an issue for us too - the expected behaviour should be that after a removal of an id, that id is available to be re-inserted.

**Comment by cyberhorse** [comment]
Around line 12799:

after this line:
`var event = this.config.events.splice(n, 1);`

add this line:            
`delete this.config.event_dict[event[0].unique_id];`

**Comment by JoeGermuska** [comment]
Thank you. This should make it through to a new minor release soon. Note that there are probably other ways in which adding and removing events dynamically doesn't behave entirely correctly. That is not an area which has seen substantial testing and attention -- but with help from the community, we can try to bring it forward!

**Comment by cyberhorse** [comment]
Thank you Joe :)
