### ISSUE TITLE
doctype for html5 ruins timeline

### ISSUE THREAD

**Issue by ipepe** [NUKnightLab/TimelineJS3#296]
I am trying to fit timeline into my rails app and I have problem, when there is ```<!DOCTYPE html>``` at beginning of my html file. Timeline is flat and javascript console for ```timeline.options.height``` is 1

I am using firefox 41.0.2 on MaxOS. I also tried jquery 1.x and 2.x

Here is my example html file:
```html
<!-- uncomment me to ruin timeline <!DOCTYPE html> -->
<html>
<head>
	<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
	<link rel="stylesheet" type="text/css" href="https://cdn.knightlab.com/libs/timeline3/latest/css/timeline.css">
	<script type="text/javascript" src="https://cdn.knightlab.com/libs/timeline3/latest/js/timeline.js"></script>
</head>

<body>
	<script type="text/javascript">
	$().ready(function(){
		window.timeline = new TL.Timeline('my-timeline', '1cWqQBZCkX9GpzFtxCWHoqFXCHg-ylTVUWlnrdYMzKUI');
	});
	</script>
	<div id="my-timeline"></div>

</body>
</html>
```
Any help on this issue?

**Comment by JoeGermuska** [comment]
You This is not an issue with the doctype. Your div has no dimensions. TimelineJS will not choose them for you. You must explicitly set the width and height of the timeline element.

Here are examples of TimelineJS in pages with an html DOCTYPE declaration (and explicit dimensions for the container):

[Revolutionary User Interfaces](http://timeline.knightlab.com/examples/user-interface/)
[Whitney Houston: 1963-2012](http://timeline.knightlab.com/examples/houston/)
