### ISSUE TITLE
Flickr Image Sizing issues

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#303]
In looking at [the venerable Radio Lab color walk example](http://www.radiolab.org/story/214709-color-walk/), I found that they are still using the original verite.co embed, which was never updated to catch up with the Flickr API.

I adapted their URL to work with both [TimelineJS](http://cdn.knightlab.com/libs/timeline/latest/embed/index.html?source=0Aq_-Amw73CNodE5zcng3cjc0bkYwaEQzN2gtQzU0Z3c&font=Bevan-PotanoSans&maptype=toner&lang=en&width=620&height=650) and [TimelineJS3](http://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=0Aq_-Amw73CNodE5zcng3cjc0bkYwaEQzN2gtQzU0Z3c&font=Bevan-PontanoSans&maptype=toner&lang=en&width=620&height=650) and see that the images are not scaled properly in TimelineJS3.

![image](https://cloud.githubusercontent.com/assets/46313/11188170/2cc2dbc2-8c4f-11e5-887c-5d8acec5d5ab.png)

**Comment by zachwise** [comment]
This is because the old timeline tried to make images fit in whatever vertical space was left over from the text. TimelineJS3 fits the image height when in the vertical layout mode (mobile) to the content height instead of leftover height from text and allows the content area to scroll. The reason is because if the text is longer than this example then the image may be only a couple pixels wide by a couple pixels high.

**Comment by mazhang2718** [comment]
@zachwise Should we close this issue then?

**Comment by zachwise** [comment]
I guess it depends on if someone thinks it's an issue or not. I'm not sure what the expectation might be, I simply tried to deal with an existing design problem that popped up with the old timeline.

**Comment by zachwise** [comment]
An example of the case I'm talking about for posterity:
OLD TIMELINE
![screenshot apr 25 16 31 11](https://cloud.githubusercontent.com/assets/741789/25408757/bb1b6604-29d4-11e7-970a-f136421e62cc.png)

TIMELINEJS3
![screenshot apr 25 16 31 27](https://cloud.githubusercontent.com/assets/741789/25408774/c86194dc-29d4-11e7-9bdb-a60246f3debd.png)

**Comment by zachwise** [comment]
Even better illustration of the issue:
OLD TIMELINE:
![apr-25-2017 16-38-42](https://cloud.githubusercontent.com/assets/741789/25408983/bf388612-29d5-11e7-925a-b324b1ba40d1.gif)

TIMELINEJS3:
![apr-25-2017 16-37-04](https://cloud.githubusercontent.com/assets/741789/25408989/c6a5f3b2-29d5-11e7-973e-e44220cc48b8.gif)

**Comment by JoeGermuska** [comment]
sounds like a feature not a bug. Closing.
