### ISSUE TITLE
Timezone in json

### ISSUE THREAD

**Issue by Yamakaky** [NUKnightLab/TimelineJS3#305]
https://timeline.knightlab.com/docs/json-format.html
The Date object documentation doesn't mention the timezone.

**Comment by JoeGermuska** [comment]
All events in a timeline are relative to each other, so adding the complexity of timezones would gain little compared to making it the author's responsibility to convert any times to a common timezone. (Anecdotally, timelines which go beyond "date resolution" into hours and minutes seem quite rare.)

If, for narrative's sake, the time zones need to be distinguished, you can use the "display date" field to change how timeline presents the date in the slide and near the navigation buttons, and of course, you can explain further in the text for a given slide.
