### ISSUE TITLE
support npm install

### ISSUE THREAD

**Issue by timqian** [NUKnightLab/TimelineJS3#308]
Is there a plan to publish this project as a npm package?

**Comment by angelxmoreno** [comment]
I'm ready to assist to push this to NPM.

**Comment by timqian** [comment]
good to hear that!

**Comment by thijstriemstra** [comment]
Any update?

**Comment by po5i** [comment]
A 2017 question: after install the package via npm (or yarn) which are the next steps? I cannot find any documentation of how to use it without the authoring tool.

**Comment by DrSensor** [comment]
Seems like there is no CI or whatsover for autopublish to npm registry when there is tag release 🙍

**Comment by JoeGermuska** [comment]
As of today, TimelineJS is on the NPM registry at https://www.npmjs.com/package/@knight-lab/timelinejs

Other versions of TimelineJS in the repository are not official (and are not maintained) and should be disregarded.

For more information, see [this blog post](https://knightlab.northwestern.edu/2020/07/09/timelinejs-update/index.html).
