### ISSUE TITLE
Implement right-to-left language support

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#309]
Our language files have a `right_to_left` property for languages like Arabic, Farsi and Hebrew, but TimelineJS3 doesn't take that into account. 

[Here's the analogous code](https://github.com/NUKnightLab/TimelineJS/blob/master/source/less/Core/Typography.less#L188-L200) from NUKnightLab/TimelineJS

**Comment by daonb** [comment]
I'll be happy to do it. I just need to get the fab working(#371)
