### ISSUE TITLE
Timeline editor should handle invalid inputs better

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#310]
A given spreadsheet URL returns null from `TL.ConfigFactory.parseGoogleSpreadsheetURL`

This leads to an unhandled `Uncaught TypeError: Cannot read property 'key' of null` in `main.js`

We should catch this and show a message to the user. In some cases, people actually have valid URLs that our parser misses, so the message should include something like "If you think this is our problem, send us an email".

(see separate issue about actually successfully parsing the URL that initiated this)

**Comment by scott2b** [comment]
this is now tracked via #318
