### ISSUE TITLE
Wider application of Dropbox URL magic?

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#312]
A couple of people have posted Zendesk tickets recently confused because their Dropbox PDFs don't embed.

We may be setting up confused expectations by "magically" converting `www.dropbox.com` to `dl.dropboxusercontent.com` for images but not for other media types.

I can't think of any reason not to do it for PDFs. Are there any other mediatypes where we should do this?

**Comment by ashwu** [comment]
Putting it into the google doc viewer worked - pushed changes.
