### ISSUE TITLE
 NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by Allenivesix** [NUKnightLab/TimelineJS3#319]
i don't understand why i get this error?  

http://www.speedythemes.net/people_tab/index.html      MILESTONES TAB.. 

any suggest?

**Comment by JoeGermuska** [comment]
That page times out when I try to reach it, on multiple browsers. Did you use a Google Spreadsheet? If so, maybe you can just provide that URL?

**Comment by Allenivesix** [comment]
i just use a json from your demo,

**Comment by JoeGermuska** [comment]
If it's JSON that works on an example page in our environment, then there must be some error in copying/reproducing the setup. Typically we'd prefer to handle that through our [Support website](http://knightlab.zendesk.com) but in any case, if we can't load your page we can't help.

**Comment by Allenivesix** [comment]
![schermata 2015-12-09 alle 17 04 03](https://cloud.githubusercontent.com/assets/10564207/11690444/ed5c16f6-9e96-11e5-9182-3916bbd77c69.png)

Yes now the server is down :/

**Comment by Allenivesix** [comment]
@JoeGermuska  please check now http://www.speedythemes.net/people_tab/index.html  on the third tab (milestones).

**Comment by Allenivesix** [comment]
@JoeGermuska  another bug, the thumb is not visible why?    this is an extract of my json :  "media": {
                "caption": "Some Txt",
                "credit": "Some text",
                "url": "http://i64.tinypic.com/33e6kwy.png",
                "thumb": 	"http://i64.tinypic.com/33e6kwy.png"
            },

**Comment by JoeGermuska** [comment]
So, you are not using our example JSON. Can you send a URL to the JSON data you are using for your timeline? Odds are good that you've simply misconfigured it somehow.

Your thumbnail is not working because you have the wrong property name. See http://timeline.knightlab.com/docs/json-format.html#json-media.

**Comment by Allenivesix** [comment]
Thx, but it's the same if i use your demo.  

 This is a URL of my JSON http://www.speedythemes.net/people_tab/spidi.json

**Comment by JoeGermuska** [comment]
The JSON at http://www.speedythemes.net/people_tab/spidi.json does not conform to the specifications we have documented. Please read the documentation carefully. Your JSON is an array of events. Timeline JSON must be an object with several properties, one of which is `events`. If you compare your JSON to one of ours, such as https://github.com/NUKnightLab/TimelineJS3/blob/master/website/templates/examples/houston/timeline3.json, the differences should be clear.
