### ISSUE TITLE
Implement tag mechanism

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#33]
I know this makes @zachwise cringe but people like them.

**Comment by JoeGermuska** [comment]
The layout parts of this were implemented by @jywsn in 62cae28a5a8e100de35e0e5311e4ae6793f85990 . It's based on using a 'group' property for a given slide.

**Comment by zachwise** [comment]
closed as of 2c582fffedd390d7b1e0617ef34c7bf2a805e33f
