### ISSUE TITLE
Unit Tests Fail on Safari

### ISSUE THREAD

**Issue by thehandsomepanther** [NUKnightLab/TimelineJS3#333]
Two unit tests fail after cloning and setting up TimelineJS locally on Safari. All unit tests pass on Chrome.

![screen shot 2016-01-26 at 5 20 05 pm](https://cloud.githubusercontent.com/assets/6078575/12598646/24d56fe4-c451-11e5-91aa-673e7114a4b4.png)

**Comment by francoismassart** [comment]
I got the same issue on Firefox 51 running on Mac OS X Sierra

**Comment by francoismassart** [comment]
This seems to be due to the fact that I am using an European Timezone.
If I change my Date/Time settings and set it as if I were in Chicago, the test passes as a charm.
