### ISSUE TITLE
Load Two Timelines on one page

### ISSUE THREAD

**Issue by invot** [NUKnightLab/TimelineJS3#334]
Is there a way to load two timelines on one page? 
![2016-01-28 17_18_11-w-2 _ assessment overview](https://cloud.githubusercontent.com/assets/2650927/12662031/298b22ac-c5e3-11e5-9c3c-01308a662cdd.jpg)

Initializing multiple timelines results in some strange behavior for the second instance...

**Comment by JoeGermuska** [comment]
There is a [test case](http://github.com/NUKnightLab/TimelineJS3/blob/a0bed5d7c22973d68d891e9cfcdd0c3c910b59bc/compiled/examples/multiple_timeline.html) in the git repository which shows two timelines in one page. Sorry that it is not easy to preview without setting up to develop on TimelineJS, but I just checked it and everything seems fine.

If you want further consulting, please submit a support ticket at knightlab.zendesk.com and be sure to include a link to a page which demonstrates the issue.
