### ISSUE TITLE
Document font choices

### ISSUE THREAD

**Issue by alipasas** [NUKnightLab/TimelineJS3#337]
Sorry guys if this has been asked in the past. I can't seem to find a list of options to change the type of the timeline in a clear-cut way. I can only use "default"
Can someone point me to such a list (if it exists somewhere)?

Thanks a mil

tjm++

**Comment by JoeGermuska** [comment]
By 'type' do you mean the fonts used? There's a menu in the authoring tool:

![image](https://cloud.githubusercontent.com/assets/46313/12716610/6c306218-c8a7-11e5-8acf-03f452105c75.png)

You are correct, though, that there ought to be a more explicit list.

The values can be any of the filenames in https://github.com/NUKnightLab/TimelineJS3/tree/master/source/less/fonts, after stripping `font.` from the beginning and `.css` from the end. You can also pass the fully-qualified URL to a font CSS file that is served on your system or anywhere else on the internet.

```
abril-droidsans
amatic-andika
base
bevan-pontanosans
bitter-raleway
clicker-garamond
dancing-ledger
default
fjalla-average
georgia-helvetica
knightlab
lustria-lato
medula-lato
oldstandard
opensans-gentiumbook
playfair-faunaone
playfair
pt
roboto-megrim
rufina-sintony
ubuntu
unicaone-vollkorn
```

**Comment by alipasas** [comment]
Mmmm, not quite sure now...
What I mean is this:
![timeline](https://cloud.githubusercontent.com/assets/6896727/12717228/1b59b81a-c8ef-11e5-9490-58bdc3fbd975.png)

- Can I change "default"?
- What are the options?
- Is there a list some place?

Thanks
tjm++

**Comment by JoeGermuska** [comment]
The screenshot you show is from [the previous version of TimelineJS](https://github.com/NUKnightLab/TimelineJS). That JSON format is not supported any more. 

In that version of Timeline, the `type` was used to distinguish `title` and `era` data from regular events. In the new JSON format, ([documented pretty extensively here](http://timeline.knightlab.com/docs/json-format.html)), titles and eras are configured under separate keys of the root JSON object.

**Comment by alipasas** [comment]
Indeed it's the old version. Thanks for the reply.
