### ISSUE TITLE
Build without CodeKit

### ISSUE THREAD

**Issue by asnoba** [NUKnightLab/TimelineJS3#338]
Hi,

Is there a way to make a new build without having CodeKit installed?

BR,
Asger

**Comment by JoeGermuska** [comment]
There sure is. Please see [CONTRIBUTING.md](https://github.com/NUKnightLab/TimelineJS3/blob/master/CONTRIBUTING.md)

**Comment by asnoba** [comment]
Okay, thanks. Will `fab build` also compile the JavaScript files according to the `@codekit-prepend` specified in `TL.Timeline.js`? I'd like to remove some of the media types includes.

**Comment by JoeGermuska** [comment]
yes, we re-implemented the codekit reference resolution in python. The builds which are deployed are created with python. Codekit is just a legacy because Timeline's creator prefers it to command-line.

**Comment by asnoba** [comment]
Great, thx. I got it to work.
