### ISSUE TITLE
Support for marker thumbnail with background image?

### ISSUE THREAD

**Issue by snpower** [NUKnightLab/TimelineJS3#339]
Hi,

I'm using the JSON method to integrate, and am showing a background image, with no media, in my timeline. However, with this method I then have no thumbnail in the marker. If I provide a media image, then I do get one, but I don't want to display a media item, just a background image.

I don't see how I can do that with the API but one of the examples generated from a spreadsheet seems to support it...

Cheers,
Stella

**Comment by scott2b** [comment]
This is done with the thumbnail property as documented here: http://timeline.knightlab.com/docs/json-format.html

In general, please open support requests at our helpdesk at knightlab.zendesk.com rather than in Github
