### ISSUE TITLE
Devise spreadsheet format for TimelineJS 3

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#34]
Current columns:
* Start Date  
* End Date    
* Headline    
* Text    
* Media   
* Media Credit    
* Media Caption   
* Media Thumbnail 
* Type    
* Tag

Challenges: supporting arbitrary formats in "date" column, including European (where Christmas is 25/12/2014) as well as the fact that values are not technically dates, at least in some cases (year-only or month/year only) 

Tags are not implemented yet. (see #33)

Users have recently requested "alt" tags for media via ZenDesk, etc. Should we support them?

**Comment by JoeGermuska** [comment]
Template by @zachwise 
https://drive.google.com/previewtemplate?id=0AppSVxABhnltdDg0WWJ0TzRPZXZRTVBwSEt6cE9GNlE&mode=public

**Comment by hbillings** [comment]
@thejordan two minutes, apparently

**Comment by thejordan** [comment]
woohoo!
