### ISSUE TITLE
Set start position from unique_id in JSON-file

### ISSUE THREAD

**Issue by asnoba** [NUKnightLab/TimelineJS3#345]
Hi,

I see that you can set `start_at_slide ` in the options hash. Is it also possible to set the start position from the `unique_id` specified in the JSON-file?

BR,
Asger

**Comment by JoeGermuska** [comment]
you can use it in directly the URL if you use the [`hash_bookmark`](http://timeline.knightlab.com/docs/options.html#hash_bookmark) option. If you're using an options hash in javascript and instantiating your own timeline, you could do this with `timeline.goToId(unique_id)`

Given these options, I'm not super inclined to add another configuration option, but if you'd like to make the case or clarify, feel free. We'll reopen if we need to.
