### ISSUE TITLE
Conditions to use Knightlab CDN?

### ISSUE THREAD

**Issue by vtamara** [NUKnightLab/TimelineJS3#346]
Blessings.  Thank you for TimelineJS and for the CDN.  
I understand the license of the sourcecode of TimelineJS and appreciate and thank for it.

However I cannot find conditions for the usage of the Kngithlab CDN.  ¿For what purposes can it be used? ¿How long?

We are experimenting it in: https://www.reiniciar.org/node/36

**Comment by JoeGermuska** [comment]
You can use `cdn.knightlab.com` as much as you like, with no limitations or conditions. 

We make no formal guarantee of service or uptime, but it is our intention to support it for the foreseeable future.

**Comment by vtamara** [comment]
Even more thanks.  God bless all of you.
