### ISSUE TITLE
image doesnt load in timeline

### ISSUE THREAD

**Issue by jayantkhanuja** [NUKnightLab/TimelineJS3#349]

**Comment by jayantkhanuja** [comment]
Hi i upload images on imgur . take the embedded link for spreadsheet , but when i take the link from spreadsheet and paste it on timeline.js and click preview. Images fail to load . It was working since last couple of months with the provided link but now it suddenly stopped loading images

**Comment by JoeGermuska** [comment]
Please use our support system at http://knightlab.zendesk.com and be sure to include a link to the Google Spreadsheet in question with your request.
