### ISSUE TITLE
Unit tests fail on clean install

### ISSUE THREAD

**Issue by bronzehedwick** [NUKnightLab/TimelineJS3#351]
Following guidelines from `CONTRIBUTING.md`, and with no local changes, I opened up the unit test page and got the following failures.

![failed_tests](https://cloud.githubusercontent.com/assets/637174/13683537/2ec17a9c-e6d5-11e5-82d2-265d2302683a.png)

**Comment by binary-koan** [comment]
I'm getting slightly different errors from the same test cases:

<img width="1215" alt="screen shot 2016-07-18 at 10 37 14 am" src="https://cloud.githubusercontent.com/assets/1077405/16903486/b82922da-4cd3-11e6-811b-8fdc4df86eb3.png">
<img width="1218" alt="screen shot 2016-07-18 at 10 37 32 am" src="https://cloud.githubusercontent.com/assets/1077405/16903487/b8298702-4cd3-11e6-9af0-ebf3c8d57044.png">

Again, a clean install in a virtualenv using Python 2.7.11 and pip 8.1.2 (on OS X)

**Comment by binary-koan** [comment]
Changing that date constructor to `new Date('Aug 07 2014 04:05:00')` (i.e. a date which doesn't specify timezone) fixes the six date formatting errors, and I assume a similar fix could be applied to the floored date one. Happy to fix the other one and submit a PR if that sounds like a reasonable method?

**Comment by JoeGermuska** [comment]
Thanks for the offer. I opted to simply use numeric values in the constructor to eliminate any ambiguity or risk that different JS implementations might have different date string parsing behavior.
