### ISSUE TITLE
Is it possible to disable to top "slide" part of TimelineJS3

### ISSUE THREAD

**Issue by codecvlt** [NUKnightLab/TimelineJS3#355]
In other words, can I receive an event when a user clicks on a timeline element with the unique_id, and forgo all the fancy carousel'ness on top?

Cheers, and thanks for a great component!

**Comment by JoeGermuska** [comment]
As the "fancy carouselness" is fundamental to our design intentions for TimelineJS, we won't directly support this.

However, a design which supports flexibility and customization is also important, so:

you should be able to do this with CSS by hiding the element with the `tl-storyslider` class. See http://timeline.knightlab.com/docs/overriding-styles.html for more on the CSS specifics.

**Comment by GusGusGusGus** [comment]
I tried what @JoeGermuska suggested on an embeddable iframe with 
`.tl-storyslider { display: none;} `
and nothing. I also tried hiding all other classes regarding the slider. Still nothing. Personnally I just need the timeline. Any other way around this?

**Comment by Aybee** [comment]
@GusGusGusGus
Your CSS works, but it has to be in the iframe to take effect on the `.tl-storyslider` within the iframe.

**Comment by TruongGiang1711** [comment]
If I separate the css and js file of 'tl-Storyslider' from timlineJS3, can I use it as a normal component for other projects?
