### ISSUE TITLE
TimelineJS3 destroys vanilla getPropertyValue()

### ISSUE THREAD

**Issue by solverat** [NUKnightLab/TimelineJS3#358]
Test it here: https://jsfiddle.net/yyketxyq/2/
It's the demo code with some extra markup. to reproduce the error:

1.) run code and watch console
2.) remove `<script src="//cdn.knightlab.com/libs/timeline3/latest/js/timeline.js"></script>` and run again
3.) console will show the correct `content` propertyvalue.

**Comment by JoeGermuska** [comment]
You may have found something, but it isn't a problem with the getPropertyValue function. Try it with other properties besides 'content' and you'll get non-blank values.

Can you elaborate on the consequence of this issue?

**Comment by solverat** [comment]
the problem, i think, is here: 

https://github.com/NUKnightLab/TimelineJS3/blob/c97e19e075056fd587f964759effd7a1ca7eb127/compiled/js/timeline.js#L2336

```javascript
try {
        getComputedStyle(undefined)
} catch(e) {
        var nativeGetComputedStyle = getComputedStyle;
        window.getComputedStyle = function(element){
          try {
            return nativeGetComputedStyle(element)
          } catch(e) {
            return null
          }
        }
}
```
when i remove the catch content, the getPropertyValue function is working as aspected. probably it's a zepto- not a timelineJS3 issue?

**Comment by JoeGermuska** [comment]
looks like there's a long-open PR for Zepto to address this too https://github.com/madrobby/zepto/pull/1074

Since we use Zepto by copy, we could take the liberty of implementing the fix in that patch. Any chance you have some time to test that a bit?
