### ISSUE TITLE
Inconsistent hashing across browsers

### ISSUE THREAD

**Issue by joshpaulchan** [NUKnightLab/TimelineJS3#359]
Hey,

We're doing some cross-browser testing on Timeline [here](http://timeline.rutgers.edu) and we're running into a strange bug.

Visiting http://timeline.rutgers.edu/#40 on `Chrome Version 49.0.2623.87 m` whereas visiting that same link on `Firefox 40.0.3` and `Safari Version 9.0.3` links to different slides. The latter two link to the same slide but the former links to the slide beforehand.

Do you guys have any idea on why this is inconsistent ordering is occuring?

Josh

**Comment by JoeGermuska** [comment]
Sorry, no specific idea, but you are using NUKnightLab/TimelineJS which is deprecated, and for which this repository/issue tracker is not applicable.

In the new version of timeline, index-based permalinks to slides is retired in favor of explicit slide IDs. When using the spreadsheet configuration format, slide IDs are computed based on the title of the slide (and so, yes, are subject to "rot" if the titles change). However, if you use the [JSON format](http://timeline.knightlab.com/docs/json-format.html), you can explicitly specify IDs for each slide and ensure that they are stable.

Sorry, but we can't spare resources to continue to support the deprecated version of TimelineJS.
