### ISSUE TITLE
Handle 'title' slides appropriately

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#36]
Right now, the first slide is always marked as the 'title' slide (based on its position, not an explicit 'type'), but also, the setup process doesn't allow for slides which don't have a date.

I wonder if we should make the title slide a separate thing in the JSON, even if it's configuration is similar to other slides, and the markup generation mostly the same. 

Title slides in the original Timeline don't show up in the time nav, and they don't require dates. I think that's probably what we want too.

Treating this as a question for now, but we will need to turn it into action items.

**Comment by JoeGermuska** [comment]
I think my proposal is to go ahead with a separate `title` property in the JSON that takes a single slide-like object. To reduce confusion, I think then I'd also want to rename `slides` in the JSON to `events`, so as to help clarify that the title doesn't go *in* the events.

**Comment by jywsn** [comment]
Should be working as of 682247b5e9fdb5a8a6dee915b59d7dd3aeb711e8
