### ISSUE TITLE
1 month offset in timeline

### ISSUE THREAD

**Issue by saurabhgayali** [NUKnightLab/TimelineJS3#364]
I have created a timeline using an old JS because thats what easy template I could get on net.

http://nipgrnc104.neocities.org/mitotimeline.html

I saw all points have a 1 month lag between real and shown times on timeline. Please help

**Comment by saurabhgayali** [comment]
its urgent. plz help

**Comment by JoeGermuska** [comment]
That is not our software. Sorry.

**Comment by saurabhgayali** [comment]
I think I got confused. thanks for clearing it. I am reporting it to the source.
Thank you
