### ISSUE TITLE
.vcard CSS rules are not properly contained

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#365]
A TimelineJS user reported issues which trace back to rules for `.vcard` which are not contained. This causes trouble when Timeline is used not-in-an-iframe-embed, such as when people use the Wordpress plugin.

Problem (away from timeline, but impacted by this rule):
![image](https://cloud.githubusercontent.com/assets/46313/15433122/91c3551a-1e76-11e6-878d-27f0416aa10b.png)

Expected behavior of original page:
![image](https://cloud.githubusercontent.com/assets/46313/15433146/a8536fea-1e76-11e6-90e4-248db8021170.png)

Here's the page where the issue showed up:
http://boatman.in/164

Can't attach CSS files, but [here's a gist](https://gist.github.com/JoeGermuska/0c544885ad0c774ce6ee8724e0f36d5b) of the uniminified CSS which makes it easier to see where there are "naked" rules about `.vcard`

**Comment by zachwise** [comment]
Found it here: https://github.com/NUKnightLab/TimelineJS3/blob/master/source/less/media/TL.Media.less#L77
