### ISSUE TITLE
Destroying timeline

### ISSUE THREAD

**Issue by pawelkondraciuk** [NUKnightLab/TimelineJS3#367]
Hi, Is there anyway to destroy and cleanup timeline dynamically? eg.
```js
var timeline = new TL.Timeline(/*...*/);
...
timeline.destroy()
```

**Comment by lbineau** [comment]
Same question here. Have you found a solution ?

**Comment by pawelkondraciuk** [comment]
I ended up writting custom code.

**Comment by 595624187** [comment]
Like cleaning div tag?

**Comment by pawelkondraciuk** [comment]
Can't remember, was some time ago but it might be cleaning div - it should also remove all the listeners
