### ISSUE TITLE
current_id and current_slide out of sync

### ISSUE THREAD

**Issue by jywsn** [NUKnightLab/TimelineJS3#37]
When using Timeline.goToId() and Timeline.goTo() as API functions, Timeline.current_id and Timeline.current_slide get out of sync.  It also seems like this happens when just navigating through the slides normally using the built-in timeline controls.

**Comment by JoeGermuska** [comment]
seems like a liability to store both, for just this reason. Any reason not to choose one way of tracking the current slide and then just transforming it to the other as needed?

**Comment by jywsn** [comment]
I don't know.

**Comment by jywsn** [comment]
removed Timeline.current_slide; track current slide by id only

da5883f4f257ab8cbe6d0fc1eabcfdafe265435a
