### ISSUE TITLE
missing fab options

### ISSUE THREAD

**Issue by daonb** [NUKnightLab/TimelineJS3#371]
according to [CONTRIBUTING.md](https://github.com/NUKnightLab/TimelineJS3/blob/master/CONTRIBUTING.md) I can get the system up and running using:

```bash
 $ fab build
 $ fab serve
```

Both commands don't exist in the fabfile and I get his error:

```bash

Warning: Command(s) not found:
    build

Available commands:

    stage_compiled  Copy CSS/JS from build to compiled
    stage_wp        * Use to copy over CSS/JS files to WP Plugin directory

```

**Comment by JoeGermuska** [comment]
@daonb  I am not sure why you would only get those commands -- which are clearly idiosyncratic to our development environment. Are you sure that everything is up to date?

Can you run `fab --list` and paste the output here?

**Comment by daonb** [comment]
I've just pulled from `master` and tried it again with no look. I also looked in the fabfile.py and that's all it has: 56 lines of code with just 2 tasks:

```bash
$ fab --list
Available commands:

    stage_compiled  Copy CSS/JS from build to compiled
    stage_wp        * Use to copy over CSS/JS files to WP Plugin directory
```

**Comment by binary-koan** [comment]
Have you definitely downloaded NU's fablib and put it beside your Timeline folder (like CONTRIBUTING.md says)? I would have thought you'd get an import error if not, but might be worth checking ...

**Comment by daonb** [comment]
I missed that.  Like you say, all the info was in CONTRIBUTING.md but it was confusing for me. I guess now I'll have a go at improving the doc.
