### ISSUE TITLE
Can I hide the BCE dates?

### ISSUE THREAD

**Issue by boblodi** [NUKnightLab/TimelineJS3#375]
It seems in older versions of timeline.js, you could hide dates "in the past" from what you are building. I want to hide all the BCE dates so my timeline starts at year 0.
is that possible? I tried changing to   "scale": "cosmological" but that changed every date - before and after 0 - to x years ago, which looked weirder than showing BCE.
something like in this example from the timeline.js site - http://www.lemonde.fr/election-presidentielle-2012/visuel/2012/04/21/chronologie-une-si-longue-campagne-presidentielle_1681661_1471069.html#meter_toaster

any ideas?

**Comment by scott2b** [comment]
Sorry, there is currently no supported or known mechanism for turning off BCE dates. If you have early dates in your timeline, BCE will show on the line due to the way TimelineJS manages the display.
