### ISSUE TITLE
Timeline click and drag doesn't work in Firefox 49

### ISSUE THREAD

**Issue by Nolski** [NUKnightLab/TimelineJS3#379]
Expected:
User can click and drag timeline horizontally in Firefox to scroll through the timeline. (This feature works in Chrome).

Observed:
Despite the drag icon, user cannot move timeline.

**Comment by JoeGermuska** [comment]
Thanks for your report. However, Firefox 49 is not yet released. Timeline behaves as expected on the current Firefox release (47.0.1).

**Comment by Nolski** [comment]
In case anyone wants to track this issue, I filed one against the browser. https://bugzilla.mozilla.org/show_bug.cgi?id=1283244

**Comment by JoeGermuska** [comment]
Thank you!
