### ISSUE TITLE
Plans for vertical timeline option?

### ISSUE THREAD

**Issue by daneasterman** [NUKnightLab/TimelineJS3#380]
Not an issue exactly, but very curious to know if there are currently any plans to introduce a vertical timeline as an alternative format? Thanks in advance, Daniel

**Comment by JoeGermuska** [comment]
Daniel:

Javascript management of vertical space, especially accounting for responsive layout on different sized screens, is extremely challenging. Thus, we're not likely to take on creating a vertical option for TimelineJS.

It's different in many ways, but you may be interested in [TikTok](http://datanews.github.io/tik-tok/), from our friends at WNYC. (Here's an [OpenNews article](https://source.opennews.org/en-US/articles/beautiful-timelines-easy-way-tik-tok/) about it)

**Comment by daneasterman** [comment]
Thanks v. much Joe, much obliged for your answer, will definitely check out TikTok!
