### ISSUE TITLE
INHA use of TJS timelines

### ISSUE THREAD

**Issue by agrahamt** [NUKnightLab/TimelineJS3#384]
Hi Knightlabbers,
theis is more a query than an issue, hope this is an okay forum for this.
I found an interesting use of TJS to explore an artist's work chronologically.
The french INHA is using it, and you can check out an implementation at http://bibliotheque-numerique.inha.fr/collection/376-fonds-et-couvercles-de-coupes/?n=9 (scroll down).

The thing is it seems to be referencing http://tools.yoolib.com/timeline/, part of a commercial package (http://www.limb-gallery.com/faq/).  I was curious if you've engaged with either the INHA or limb-gallery about that.  There's also a Wordpress site, http://my.yoolib.com/demo/.  I understand that TJS is opensource.
Any thoughts?
Regards, Andrew Taylor

**Comment by JoeGermuska** [comment]
Andrew:

Regarding the question, no, we have had no interactions with INHA or limb-gallery. When I visit the http://tools.yoolib.com/timeline/ page, I get an error. When I go to http://bibliotheque-numerique.inha.fr/collection/376-fonds-et-couvercles-de-coupes/?n=9 and scroll down, I don't see a Timeline. 

It looks from under the hood, though, that they are using an older version of Timeline. This is most likely within the terms of the [Mozilla license](https://github.com/NUKnightLab/TimelineJS3/blob/master/LICENSE) under which TimelineJS is offered.  We will probably take a closer look just to make sure, but we are aware that our license is relatively permissive.

**Comment by agrahamt** [comment]
Thanks for responding, Joe!  It does look like an old version.
I think my link was off, here's a page that I see one on, and a shot of it just in case:
Permalink: http://www.purl.org/yoolib/inha/19541
Regards, Andrew Taylor
![inha](https://cloud.githubusercontent.com/assets/3066864/17337763/d6a7dda0-58a9-11e6-8a80-bdb8cd10167c.jpg)
