### ISSUE TITLE
Time marker formatting in RTL languages

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#397]
@zachwise If the text for RTL languages is right-aligned in markers, should the icons be to the right of the text?

English:
![image](https://cloud.githubusercontent.com/assets/46313/17864997/0d68132a-6866-11e6-8a26-74a30fe6ab96.png)

Hebrew:
![image](https://cloud.githubusercontent.com/assets/46313/17865010/1f168b9c-6866-11e6-9a4d-32319a04f4a9.png)

see also #395 and #309

**Comment by mazhang2718** [comment]
I adjusted it to this, hopefully that looks fine?
<img width="524" alt="screen shot 2016-08-23 at 2 28 37 pm" src="https://cloud.githubusercontent.com/assets/12781097/17907927/ad27ae74-6943-11e6-86c3-be7c7e6d28f2.png">
