### ISSUE TITLE
Submission of a script to convert google spreadsheet to json file

### ISSUE THREAD

**Issue by iamamoose** [NUKnightLab/TimelineJS3#398]
We tested out using TimelineJS using a google spreadsheet but wanted to then move everything internal.  Rather than rewrite everything I made this Python program that can take the spreadsheet and convert it to a json file which you can then host internally etc.    As there is no contrib/ directory I didn't submit a MR, but feel free to create some place for this and request a MR from me instead.  Submittted under MPL as per LICENSE.

[timeline.py.txt](https://github.com/NUKnightLab/TimelineJS3/files/436861/timeline.py.txt)

**Comment by fedorbeets** [comment]
Here is a version of the script that will also convert era's.

[timeline.py.txt](https://github.com/NUKnightLab/TimelineJS3/files/671841/timeline.py.txt)
