### ISSUE TITLE
Some media types do not pause when the slide is changed.

### ISSUE THREAD

**Issue by Hammman** [NUKnightLab/TimelineJS3#399]
I've noticed that ~~Vines~~, ~~soundcloud~~, ~~dailymotion~~ and spotify media do not pause when the slide changes where youtube and vimeo do.

Edit: pull #400 fixed vines, soundcloud and dailymotion.
Couldn't get spotify to work with a similar fix at the time.

**Comment by yawkity** [comment]
Seems like Spotify doesn't allow it's embeded player to be controlled by JS:

"**Is there a JS SDK for the player? Can I send play/pause commands using Javascript?**
The Play button doesn’t have any observable events, nor does it listen for any. Playback can only be triggered by the user clicking the button."

Source: https://developer.spotify.com/technologies/widgets/spotify-play-button/

**Comment by scott2b** [comment]
ok, thanks for checking into this
