### ISSUE TITLE
Sequencing flexibility

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#40]
In NUKnightLab/TimelineJS#725, someone requested the ability to display markers on the timeline corresponding to, for example, the lifespan of a person, but to sequence the slide based on some time other than that person's birthdate.

This is an understandable request, although it seems kind of complex. Perhaps it can be handled simply with a "sequence_date" property that would override the start_date?

We've also had requests for what amount to "title" cards in the midst of timelines, as sort of chapter markers. This seems a lot harder, because we don't have a paradigm for displaying a marker for them in the timeline.

**Comment by JoeGermuska** [comment]
After discussion, we thought that this can also become an evolution of eras. Instead of treating them like chapters, we can implement them as spans near the timeaxis with labels.


![image](https://cloud.githubusercontent.com/assets/46313/5649466/a28e2ffe-965b-11e4-8a67-abcaedfd52d2.png)

**Comment by evanwolf** [comment]
+1.

**Comment by JoeGermuska** [comment]
Closing, as eras have been implemented, and they seem like a sound solution for this.
