### ISSUE TITLE
Website snippets not showing up in media 

### ISSUE THREAD

**Issue by dcdtla** [NUKnightLab/TimelineJS3#403]
I am researching a news topic and documenting articles, I am placing the article in the MEDIA column but I am getting broken links. Screenshots below. 

![image](https://cloud.githubusercontent.com/assets/22063212/18330574/45f4b41e-750e-11e6-81bc-7c25b43048b7.png)
![image](https://cloud.githubusercontent.com/assets/22063212/18330587/56ac4286-750e-11e6-9b51-659e99516e21.png)

**Comment by mazhang2718** [comment]
Hi there,

We don't really have support for direct website links in the Media column - you can try embedding your website through an iframe, though that result may or may not work that well.
