### ISSUE TITLE
Get the index of the selected slide ?

### ISSUE THREAD

**Issue by Shoko84** [NUKnightLab/TimelineJS3#407]
Hi everyone,

I was wondering if there was a solution to get the selected slide index ? I need that to create a "More info" function and all that stuff. I searched and tried many things but that didn't work.

Any idea about that problem ? If that doesn't exist, it may even be a useful feature to implement i guess

**Comment by scott2b** [comment]
There is, in fact, a feature referred to as "deep linking" or "hash bookmarks". This is enabled by selecting "Optional Settings" in Step 3 when creating the timeline, and enabling "Use hash bookmarks". This will enable slide-specific URLs that can be copied from your browser's address bar.

If you have already created your timeline, I recommend going through the timeline creator and selecting "use hash bookmarks" to see how it affects the embed code -- you will need to add `hash_bookmark=true` to the options of the iframe src in your embed.

**Comment by scott2b** [comment]
Sorry, I misspoke. This feature does in fact exist, but it will not work for iframe embed codes. It will only work if you use the option of directly linking to the timeline. We do not currently have deep-linking implemented for iframe embeds.
