### ISSUE TITLE
Hide thumbnail in timeline

### ISSUE THREAD

**Issue by MathieuDerelle** [NUKnightLab/TimelineJS3#409]
I'd like to disable thumbnails even if there's a media object.

![image](https://cloud.githubusercontent.com/assets/16286023/18906841/7cc2ea90-8569-11e6-8b4b-4bc35bc0bdc9.png)

I'm passing a media object with { url: '...', thumbnail: false/null } but it does not work. 
Is there a proper way to do this ? My workaround is too hide the icon via CSS.

**Comment by scott2b** [comment]
@MathieuDerelle there is not currently a supported feature for hiding the thumbnail. Your approach of using CSS to hide it is the correct one.
