### ISSUE TITLE
Marker length sometimes too long

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#41]
We saw this in the Mark Twain demo on the test site
![image](https://cloud.githubusercontent.com/assets/46313/5649220/c837cec4-9659-11e4-8080-5d89b8114e32.png)

**Comment by zachwise** [comment]
I can't seem to reproduce this

**Comment by JoeGermuska** [comment]
I still see it on http://localhost:8000/examples/multiple_timeline.html (running a local server, as I believe you do with CodeKit).

I can also make an example available under the python server if you are working that way.

**Comment by zachwise** [comment]
I'm looking at that example and still not seeing it. I only see it go larger when it's below the minimum threshold, which the screenshot above seems to suggest it's larger above that threshold. Can you add another screenshot of a more recent incident?

**Comment by JoeGermuska** [comment]
Actually, the current situation may qualify as "below the minimum threshold." It's generously padded, but but as generously as the screenshot before.

![image](https://cloud.githubusercontent.com/assets/46313/6833684/ec8566c6-d2fc-11e4-8483-eacc37fefaab.png)

Close this if you think that's within the reasonable limits.

**Comment by zachwise** [comment]
The minimum is set in the config. It should be 100px by default, which this appears to be. Closing.
