### ISSUE TITLE
Timeline does not display properly with font-awesome

### ISSUE THREAD

**Issue by JustinRickard** [NUKnightLab/TimelineJS3#410]
I have a page that has a reference to font-awesome, and has a timeline on it.
If the font-awesome CSS link is added before the timeline CSS link (as per the below), the timeline does not display properly. Instead of showing a timeline, all the content is displayed one after another. So presumably there are conflicting classes.

Adding the font-awesome link after the timeline link causes the font-awesome doesn't work. So I have to choose between using font-awesome and timelinejs.

**Links on my HTML page:**

```
<link title="font-awesome" rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.css">

<link title="timeline-styles" rel="stylesheet" type="text/css" href="https://cdn.knightlab.com/libs/timeline3/latest/css/timeline.css">
```

**Comment by thehandsomepanther** [comment]
@JustinRickard can you provide some screenshots/more information on how to replicate your issue? do you font awesome icons in your timeline, or just in the surrounding content?

**Comment by JustinRickard** [comment]
@thehandsomepanther , I experienced the issue with no fontawesome icons in the timeline itself, just in the surrounding content. I'll try to replicate it on a very simple project and provide the GitHub repo link.

**Comment by JustinRickard** [comment]
@thehandsomepanther , I have created a very simple project to replicate the bug and put it on GitHub:

https://github.com/JustinRickard/TimelineJS3_410.git

In the index.html, I have added a note regarding the ordering of the 2 CSS files. Simply switch them to see the change in the web page.

**Comment by thehandsomepanther** [comment]
@JustinRickard I've taken a crack at this and it seems like a really strange issue. we don't have a solution yet, but in the meantime, is there a reason you can't use a timeline in an iframe?

**Comment by JustinRickard** [comment]
It's very strange, when I first saw it I was convinced I was doing something wrong.

I don't need this fixed any time soon. I found it while having a play around with some front-end technologies, I wasn't developing anything important.

Justin

**Comment by numero90** [comment]
try to remove  title="font-awesome" , it solved the issue for me
