### ISSUE TITLE
Support <video> tags

### ISSUE THREAD

**Issue by thehandsomepanther** [NUKnightLab/TimelineJS3#411]
Allow for direct video embed through use of the `<video>` tag.

**Comment by 03stories** [comment]
Trying to make this work with some custom js on a local project, but yes if it was core that'd be beautiful ;)

**Comment by thehandsomepanther** [comment]
under construction at https://github.com/NUKnightLab/TimelineJS3/pull/468

**Comment by thehandsomepanther** [comment]
#468 has been merged
