### ISSUE TITLE
Support <audio> tags

### ISSUE THREAD

**Issue by thehandsomepanther** [NUKnightLab/TimelineJS3#412]
Allow for direct audio embed through use of the `<audio>` tag.

**Comment by thehandsomepanther** [comment]
under construction at https://github.com/NUKnightLab/TimelineJS3/pull/468

**Comment by zachwise** [comment]
I see the audio tag is only allowing .wav and .mp3. You should also allow .ogg, .m4a, .oga, and .webma

**Comment by thijstriemstra** [comment]
It would be great to support waveform visualization using https://github.com/katspaugh/wavesurfer.js or https://github.com/collab-project/videojs-wavesurfer. I can add a PR once #468 lands.

**Comment by thehandsomepanther** [comment]
#468 has been merged
