### ISSUE TITLE
Document Cloud embed type

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#42]

**Comment by JoeGermuska** [comment]
This is basically what needs to be done to embed a document cloud doc:
https://www.documentcloud.org/help?page=publishing#embed

Here's an example URL that should be embeddable:
https://www.documentcloud.org/documents/346266-healthcarefullplan.html
so if that is the URL in the 'media' field for a slide, we should trigger the embed.

(Changing the 'html' to 'js' gets the URL for the embed.)

**Comment by jywsn** [comment]
dfcc43ed649b2c1a3c643c4aacba63fcc17888ae
