### ISSUE TITLE
Allow usage of local csv files

### ISSUE THREAD

**Issue by benjaminabel** [NUKnightLab/TimelineJS3#420]
Hi, first of all thanks for this framework.
I think it could be great to allow users to use local `csv` files and not only `json` files. I made a crude implementation for my (french) students using the new d3-request library, you can see the code [here](https://github.com/benjaminabel/timelinejs-local/tree/gh-pages) and live demo [here](https://benjaminabel.github.io/timelinejs-local/).

Are you interested in such an implementation?

**Comment by berteh** [comment]
nice, esp. as CSV is so easy to create with openoffice (or googlespreadsheet).

**Comment by ElMacBgl** [comment]
Nice one !
However, does not seem to work on iPhone, for a reason I cannot explain  (yet).
I tried both your live demo abd and example I made on my own (which is working on desktop)

**Comment by ElMacBgl** [comment]
Found it the bug on IOS (iPhone):
It seems IOS does not like the syntax 
d3.csv('http://elmac.noip.me/includes/real.csv', (error, data) => {});

After checking d3 website, proper constructor should be:
d3.csv('http://elmac.noip.me/includes/real.csv', eachRow, callback);

Where eachRow is a function executed on each row (put inside what you have inside "data.forEach((itemData) => {}")
And callback is executed when all file had been read (ou send the csvdata to timeline there)

Tested and it works on all paltforms, IOS included.

**Comment by benjaminabel** [comment]
Thanks @ElmacBgl for these precisions. You can open a PR on my forked repository to update the code. However, it was just a crude implementation and I'm waiting more precisions about team members @mazhang2718:

- do they want to include this feature
- are they ok to include the d3 dependencies or to handle the CSV data

**Comment by JoeGermuska** [comment]
It's extremely unlikely that we'll add a feature to TimelineJS which requires an external dependency. 

We shouldn't just implement naïve CSV parsing either. TimelineJS's use cases are rife with embedded newlines and embedded quote characters, etc. which are very challenging to manage.

If a public domain or permissively licensed javascript CSV parsing solution can be found which could be inlined into TimelineJS, we'd consider it, but I would want to be careful about adding a lot of extra code for a use case for which we haven't heard a lot of demand.  

The other approach would be to simply publish a separate solution for just the parsing which would be loaded into a web page after the main TimelineJS and would presumably provide as its main entry point for users something like this:

```javascript
var timeline = makeTimelinefromCSV(div_id,csv_url,options);
```

**Comment by scott2b** [comment]
Based on comments above, closing as wontfix
