### ISSUE TITLE
multiple language timeline content

### ISSUE THREAD

**Issue by berteh** [NUKnightLab/TimelineJS3#422]
I'd like to be able to publish the same timeline in different languages.

As a workaround I can already make duplicates of a single timeline and then translate all text elements... but updating them, and adding or removing some becomes more tedious when multiple languages are involved.

I'd love it nevertheless if multiple language content could be supported from a single spreadsheet... that way all metadata (dates, medias...) would be easier to maintain, and I'd just provide translations for texts elements, as in this sample spreadsheet that provides data in EN-FR-DE for the homepage of timelinejs:  (see columns S and following)

https://docs.google.com/spreadsheets/d/14b8Mm8e5XC1KF8OYXwdUuetb5H9i7hK5Mo0Nq-s8r0A/edit?usp=sharing

Some button/flag would be needed to switch languages, and It'd be nice if the embed (wikipedia) link could be updated accordingly too... but that goes even further ;)

It may be easier to leave out groups label translation at first in case of inconsistencies... don't know.

Any thought is welcome, I'm available to help test or provide additional ideas... but my tech skills won't allow me to pull this one off nicely.

Thanks to all contributors for the GREAT tool!
B.

**Comment by scott2b** [comment]
The architectural complexity and lack of development resources currently on Timeline means this request will never get addressed. Closing as such. The recommended workaround is the above mentioned approach of creating multiple timelines in different spreadsheets
