### ISSUE TITLE
Title slide gets overwritten when timeline is reversed

### ISSUE THREAD

**Issue by mazhang2718** [NUKnightLab/TimelineJS3#426]
The title slide doesn't display first when 'Start from End' is checked - probably more of a design issue than a technical flaw?

https://knightlab.zendesk.com/agent/tickets/3705

**Comment by scott2b** [comment]
I think this might be a duplicate of #288

**Comment by mazhang2718** [comment]
Oh, I haven't seen that one - it is a duplicate, I'll close this one.
