### ISSUE TITLE
Vertical alignment in Internet Explorer

### ISSUE THREAD

**Issue by mx5pixie** [NUKnightLab/TimelineJS3#427]
Since the release of CSS 3.4.3 on 15 November 2016, the vertical alignment of slides with no media no longer centers. It occurs even running on Knight Lab preview without the override CSS file we use on the instantiated version (both screengrab examples attached).

I've narrowed it down to a specific set of changes in the CSS from v3.4.1 and 3.4.3

I've given the Department of Prime Minister and Cabinet the option of overriding the changes or using the 3.4.1 timeline.css specifically but would prefer that we can rely on the latest version hosted by Knight Lab.

Help please! We love TimelineJS and would like to keep customisations minimal and cosmetic.

<img width="960" alt="vertical align example" src="https://cloud.githubusercontent.com/assets/23511615/20369839/33749a86-acc0-11e6-9e00-1748590b59ee.PNG">
<img width="960" alt="vertical align example2" src="https://cloud.githubusercontent.com/assets/23511615/20369963/e352fb8c-acc0-11e6-9a8c-ae6c771a2b60.PNG">
<img width="850" alt="vertical align issue" src="https://cloud.githubusercontent.com/assets/23511615/20369838/3365e4e6-acc0-11e6-831c-8a7c07580e96.PNG">

**Comment by mx5pixie** [comment]
Logged on Zendesk as #3783

**Comment by ijoemonaco** [comment]
This may be much to ask, but how do I access the source files to implement this change?

**Comment by scott2b** [comment]
@ijoemonaco This code has not yet been deployed to our servers. I will try to do that this week.

Regarding the source code, this repository is it.

**Comment by scott2b** [comment]
This is now in latest which is 3.4.4

**Comment by ijoemonaco** [comment]
Scott, This works great! Thank you for the fix!!
