### ISSUE TITLE
Timeline giving an error

### ISSUE THREAD

**Issue by uxeyali** [NUKnightLab/TimelineJS3#429]
Creating a new timeline using the template is giving an error. Screenshot:
<img width="797" alt="screen shot 2016-11-21 at 2 50 56 pm" src="https://cloud.githubusercontent.com/assets/19575046/20500783/85ad9a0c-affc-11e6-903e-5060a8a6d5b6.png">

**Comment by JoeGermuska** [comment]
In general, please start with our support desk at knightlab.zendesk.com

Whenever you ask for help there, please be sure to provide the URL of your Google Spreadsheet.

It does seem that Google may have changed something about the "publish to the web" section. You may do better taking the URL of your spreadsheet while you are editing it, even though that is not how our instructions currently read.

**Comment by thehandsomepanther** [comment]
#430

**Comment by JoeGermuska** [comment]
We documented a workaround to this issue at https://knightlab.northwestern.edu/2016/11/21/a-google-spreadsheets-change-affecting-timelinejs-users/
