### ISSUE TITLE
handle dropbox HTML page images correctly

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#43]
Users often use a Dropbox URL like https://www.dropbox.com/s/llahmtejgebc5h5/boombox.jpg which points to HTML, not an image. The transformation is simple: change the domain name to "dl.dropboxusercontent.com" (e.g. https://dl.dropboxusercontent.com/s/llahmtejgebc5h5/boombox.jpg)

We should infer this when people use www.dropbox.com/...(jpg|gif|png) URLs.

**Comment by jywsn** [comment]
294a166bef4b5f369bb35c938b6ce2bb5354e276
