### ISSUE TITLE
Migrate Timeline to Google Sheets API v4

### ISSUE THREAD

**Issue by thehandsomepanther** [NUKnightLab/TimelineJS3#430]
The Google Sheets API currently used by TimelineJS (v3), is being deprecated (https://developers.google.com/sheets/guides/migration). One major change is that the publish functionality in Google Sheets no longer returns a url in the pattern we expect, and users are currently having to work around it.

**Comment by toddp0530** [comment]
Is there a work-around for this issue yet?

**Comment by scott2b** [comment]
This was an issue for a brief moment when Google changed the URL format, but they have changed it back. wontfix
