### ISSUE TITLE
Captions are being cut off for vertical photos

### ISSUE THREAD

**Issue by mazhang2718** [NUKnightLab/TimelineJS3#431]
Some users are reporting that their captions are getting cut off by the timeline navigation, usually when they're embedding an image in vertical orientation. I'm guessing this just needs an adjustment in the image/media container for vertical images.

https://knightlab.zendesk.com/agent/tickets/3773
https://knightlab.zendesk.com/agent/tickets/3821

**Comment by zachwise** [comment]
Can you provide some links to the timelines in which this problem is happening?

**Comment by zachwise** [comment]
The problem is here:
```
.tl-slide .tl-slide-scrollable-container {
    height: 100%;
    padding-top: 10px;
    z-index: 1;
    overflow-x: hidden;
    overflow-y: auto;
}
```
I'm not sure when the padding-top:10px was added but that is what is causing the problem. It must have been added recently.

**Comment by zachwise** [comment]
Problem was possibly created with this https://github.com/NUKnightLab/TimelineJS3/commit/62e55594183dee6e44f6a5be45027913da149a59

**Comment by mazhang2718** [comment]
Removing the padding worked for me as well! I'll push to master, since it's just one line of code.
