### ISSUE TITLE
API for adding multiple events?

### ISSUE THREAD

**Issue by anurag6792** [NUKnightLab/TimelineJS3#432]
Is there an API for adding multiple events?

**Comment by yawkity** [comment]
Hi!

Can you please elaborate what kind of API you were imagining for this feature?

Thanks!

**Comment by anurag6792** [comment]
What I need is that , if it was possible to add multiple events . As of now I found that the 'add' method adds only one event.In our case there are more than one event that needs to be added.What we are doing is that  we are looping in each event that needs to be added.So there is a performance issue in that.The browser hangs till the loop finishes.So can you suggest something for it?
Apart from this I have more question that dragging along the timeline doesn't work.But when we swipe through mouse pad of laptop it works.Is this an issue?

Thanks!

**Comment by shaula** [comment]
I had the same issue and I hacked into the library a bit. Just add this code to your JS file:
```
    TL.Timeline.prototype.addBatch = function (events) {
      for (var i in events) {
        this.addDeferred(events[i]);
      }

      // FIXME: Sorting destroys grouping
      TL.DateUtil.sortByDate(this.config.events);
      TL.DateUtil.sortByDate(this.config.eras);

      this._storyslider._updateDrawSlides();
      this._timenav._updateDrawTimeline(false);

      for (i in events) {
        this.fire("added", {unique_id: events[i].unique_id});
      }
    };

    TL.Timeline.prototype.addDeferred = function (data) {
      var unique_id = this.config.addEvent(data, true); // defer sorting

      var n = this._getEventIndex(unique_id);
      var d = this.config.events[n];

      this._storyslider.createSlide(d, this.config.title ? n+1 : n);
      this._timenav.createMarker(d, n);
    };
```

However, there is one caveat - the grouping feature is a mess afterwards. Any hints?

**Comment by randragon42** [comment]
@shaula were you able to come up with a solution that worked? I am currently facing the same issue.

**Comment by JoeGermuska** [comment]
We will readily admit that TimelineJS was not really developed with a full MVC model. That is, when event "model objects" are added or changed, the corresponding views don't automatically update. 

Support for that was not a primary use case, and to correct the data/lifecycle issues in the current codebase would be no small project, especially given that our design target for TimelineJS is storytelling, which is usually not so dynamic.

You are almost certainly better off just manipulating a JSON representation of the timeline and instantiating a new timeline when you need it. If you wanted the viewer to stay on the same slide they were at, you'd need to take some more steps, but that would still probably be easier than reimplementing the existing codebase as proper MVC.
