### ISSUE TITLE
Is it possible to remplace the "Before JC" text ? 

### ISSUE THREAD

**Issue by thalwani** [NUKnightLab/TimelineJS3#439]
Is it possible to remplace the "Before JC" text ? 

Thank you.

Regards,
Toufic.

**Comment by JoeGermuska** [comment]
Generally, we prefer to handle questions like this through our [Support website](https://knightlab.zendesk.com)

It's a complicated answer, so I took the opportunity to [write a document on that help site.](https://knightlab.zendesk.com/knowledge/articles/218289103/en-us?brand_id=2621286) Please check it out, and if you have further questions, we'll see you on Zendesk.
