### ISSUE TITLE
Default text for SlideNav

### ISSUE THREAD

**Issue by jywsn** [NUKnightLab/TimelineJS3#44]
If a slide has no headline, then the text in the Previous/Next StorySlider controls is not replaced.  As you navigate back and forth within a timeline, the text in the control will not match what the previous/next slide actually is, which is confusing.  There should probably be some language-dependent default text.  Or, maybe allow no text.

**Comment by JoeGermuska** [comment]
I'm inclined to allow no text. But I also see that the dates aren't appearing, so I'm going to check into that before closing this.
