### ISSUE TITLE
style review process needed

### ISSUE THREAD

**Issue by scott2b** [NUKnightLab/TimelineJS3#442]
create a standardized process for reviewing style code changes before deployment. This should include a page with embeds and/or links for known existing Timelines with checklists of things to look for when reviewing new styles.

**Comment by scott2b** [comment]
@zachwise please provide a list of some of the things you look at when reviewing to be codified into the fix for this issue

**Comment by zachwise** [comment]
Previously I created examples to check in the compiled/examples folder https://github.com/NUKnightLab/TimelineJS3/tree/master/compiled/examples
Maybe we should rename it `tests` and continue to add cases to check against in there.

**Comment by zachwise** [comment]
There are test pages for `media types` `cosmological` time frames, several grouping tests and an embed size test page. Tests for navigation both large and positioned to the top. There's a test for eras which is largely undocumented and also a test for very small timeframes (milliseconds). We should add new pages for problem edge case timelines to the same folder.

**Comment by zachwise** [comment]
It might be easier for me to document a testing workflow if I actually tested a change with someone else. Maybe @scott2b and I could do that and document the process.

**Comment by scott2b** [comment]
This is now documented in an internal document titled "TimelineJS Development Cycle". Summary reviews of design changes will be passed to @zachwise before they get deployed to latest.

TODO: we should have an "official" internal spreadsheet that hits checkpoints including, but not limited to, each media type

**Comment by scott2b** [comment]
There is a test spreadsheet here: https://docs.google.com/spreadsheets/d/1BxNc9dCDEBJpNSnYpucg4uCjn-TBQhITHq69I-eGUNc/edit#gid=0
