### ISSUE TITLE
Vertical scroll?

### ISSUE THREAD

**Issue by chrislong** [NUKnightLab/TimelineJS3#443]
I really like the look of this timeline. In our application we have a lot of events overlapping in time and need to scroll the timeline vertically. Are there any plans to add an option for a vertical scrollbar?

**Comment by JoeGermuska** [comment]
We would recommend using [options](http://timeline.knightlab.com/docs/options.html) to change the size of the navigation area. See [`timenav_height`](http://timeline.knightlab.com/docs/options.html#timenav_height) or [`timenav_height_percentage`](http://timeline.knightlab.com/docs/options.html#timenav_height_percentage)

**Comment by chrislong** [comment]
Thanks for the quick reply. Doesn't that just change how big the timeline is? Our app has limited screen real estate. We need a timeline that can scroll vertically (internally, without changing the rest of the screen).
