### ISSUE TITLE
Vimeo embed controls not showing for iframe embeds

### ISSUE THREAD

**Issue by scott2b** [NUKnightLab/TimelineJS3#446]
When pasting the Vimeo iframe embed with allowfullscreen into the spreadsheet instead of just a URL, it is expected that the full embed will show, including the fullscreen popout arrows icon. 

In Chrome, while the overall embed works, the fullscreen icon seems to get suppressed in a Timeline context (whereas works fine in a simple HTML test page). In Firefox, none of the embed controls show except for the centralized play/pause button.

It is unclear if this is being caused by something in Timeline styles or layout (perhaps size constraints? although - this seems unlikely given different behaviors for different browsers) or if Vimeo is modifying behavior for different contexts (not sure how they would be doing this for an iframe).

**Comment by thehandsomepanther** [comment]
found this [thread](https://vimeo.com/forums/help/topic:277610) after a little googling. basically, the iframe containing the whole timeline needs the `webkitallowfullscreen mozallowfullscreen allowfullscreen` attributes as well.

**Comment by scott2b** [comment]
Fixed by #446
