### ISSUE TITLE
Inconsistent sizing of "Storytelling Tools" elements - Safari [iPad]

### ISSUE THREAD

**Issue by yawkity** [NUKnightLab/TimelineJS3#449]
iPad IOS 10.1, Screen Size: 1024x1366

![Sizing Issues](https://cloud.githubusercontent.com/assets/3255833/21869339/bd817cee-d81c-11e6-9679-774e88ac11e9.PNG)

**Comment by scott2b** [comment]
A general Safari issue. Same problem occurs on desktop

**Comment by zachwise** [comment]
@yawkity move to main orangeline issues.

**Comment by yawkity** [comment]
Moved to orangeline
