### ISSUE TITLE
Div overflow - Microsoft Edge [Lumia 950]

### ISSUE THREAD

**Issue by yawkity** [NUKnightLab/TimelineJS3#450]
Windows Lumia 950, Screen Size: 360x640

![yoe67ug](https://cloud.githubusercontent.com/assets/3255833/21869537/aed7ac30-d81d-11e6-9b57-78e3cf05773e.png)

**Comment by scott2b** [comment]
This seems to be an IE issue. I am seeing the same thing on a desktop with Windows / IE

**Comment by zachwise** [comment]
@yawkity This should be moved to the main orangeline issues.

**Comment by yawkity** [comment]
moved
