### ISSUE TITLE
Button Text

### ISSUE THREAD

**Issue by yawkity** [NUKnightLab/TimelineJS3#451]
Not sure if this is an issue or not but button text is a bit choppy on mobile devices:

![img_0066](https://cloud.githubusercontent.com/assets/3255833/21870505/51c3b96c-d822-11e6-8eed-fba39d6d9765.PNG)

**Comment by scott2b** [comment]
Could you provide a bit more detail? Does choppy mean pixelated? Or are you referring to the shadow animation? Also, is this Timeline specific? I would expect this to be similar across projects

**Comment by zachwise** [comment]
@yawkity could you be more descriptive and also move this to the main orangeline issues.

**Comment by yawkity** [comment]
Looking at https://nuknightlab.github.io/orangeline/dist/#buttons, the shadow animation is intended to look this way, this can be closed

<img width="490" alt="screen shot 2017-01-23 at 3 43 47 pm" src="https://cloud.githubusercontent.com/assets/3255833/22224110/26dcef2e-e183-11e6-86f2-4380a47cbab7.png">
