### ISSUE TITLE
Spotify Album list was invalid.

### ISSUE THREAD

**Issue by onpota** [NUKnightLab/TimelineJS3#459]
I put Spotify album id into media column. but didn't work.
so I changed the code as below. don't know anybody needs this tiny change, though ;)

//@timeline.js #8437
		// Get Media ID
		if (this.data.url.match(/^spotify:track/) || this.data.url.match(/^spotify:album/) || this.data.url.match(/^spotify:user:.+:playlist:/) ) {
			this.media_id = this.data.url;
		}
		if (this.data.url.match(/spotify.com\/track\/(.+)/)) {
			this.media_id = "spotify:track:" + this.data.url.match(/spotify.com\/track\/(.+)/)[1];
		} else if (this.data.url.match(/spotify.com\/album\/(.+)/)) {
			this.media_id = "spotify:album:" + this.data.url.match(/spotify.com\/album\/(.+)/)[1];
		} else if (this.data.url.match(/spotify.com\/user\/(.+?)\/playlist\/(.+)/)) {
			var user = this.data.url.match(/spotify.com\/user\/(.+?)\/playlist\/(.+)/)[1];
			var playlist = this.data.url.match(/spotify.com\/user\/(.+?)\/playlist\/(.+)/)[2];
			this.media_id = "spotify:user:" + user + ":playlist:" + playlist;
		}

**Comment by thehandsomepanther** [comment]
Thanks for the help! I've put your contribution into a pull request [here](https://github.com/NUKnightLab/TimelineJS3/pull/460)
