### ISSUE TITLE
request for multiple groups

### ISSUE THREAD

**Issue by berteh** [NUKnightLab/TimelineJS3#461]
Hello. 
Love TimelineJS3, thanks al lot!

Could you please think of a way to support multiple groups?  I would like to use group information as tags, to have the same event show in a few "categories".  Would that be possible?

It would fare great with group ordering in #416 too.

**Comment by JoeGermuska** [comment]
If the way that an event is linked to a group is by its row in the navigation panel, how would you propose to display an event which is in more than one group? Show it multiple times? That seems quite confusing.

Besides that, our design priority with TimelineJS is storytelling, and we find repeatedly that when people put great effort into groups, they tend to lose the narrative thread. 

I'm sorry, but we're not likely to take this on.
