### ISSUE TITLE
Smooth scroll not working on orangeline page

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#466]
Looks like it's lacking the orangeline JS file which makes smooth scroll happen.

**Comment by bdin** [comment]
The smoothscroll seems to be working for me. Is there somewhere else it should be scrolling besides from the main navbar at the top?

**Comment by zachwise** [comment]
Is it rolled out on staging? Last time I looked at the staging site it wasn't working.

**Comment by bdin** [comment]
It is now! Let me know if that's ok

**Comment by zachwise** [comment]
It doesn't seem to work. It just jumps down the page. It looks like there's a JS file called `smoothscroll` that's loading that may conflict. Also I don't see the orangeline js file being loaded.

**Comment by zachwise** [comment]
Also, I'm not sure why we're loading jquery on the page.

**Comment by scott2b** [comment]
Scroll works for me. @zachwise can you give details about your test environment so @bdin can replicate?

**Comment by zachwise** [comment]
@scott2b I'm just looking at http://timeline.knilab.com/ in Chrome on a mac.

**Comment by scott2b** [comment]
me too

**Comment by zachwise** [comment]
Same in Firefox and Safari

**Comment by scott2b** [comment]
maybe I don't know what a scroll is actually supposed to look like

**Comment by zachwise** [comment]
It should smooth scroll down the page, not jump. I can also see that the orangeline JS file is still not in there.

**Comment by zachwise** [comment]
You can see smooth scroll working here: https://nuknightlab.github.io/orangeline/dist/templates/pages/product.html
Also there is a sticky subnav on that page that is probably not working because the orangeline JS is not on the page.

**Comment by bdin** [comment]
Scroll is now working
