### ISSUE TITLE
[FEATURE] Allow Markdown in all HTML-supporting fields

### ISSUE THREAD

**Issue by patcon** [NUKnightLab/TimelineJS3#470]
Firstly, his tool is amazing. Thanks so much! I started using it for everything from chronicling family history (my siblings and I working on a gift that involves documenting all the significant buildings in our parent's lives) to documenting legislative history of certain issues in my city for consultative purposes.

Anyhow my feature request: the spreadsheet document, while super-simple, can often become a little difficult to read. Since most of the formatting folks will do will be very simple, it would be amazing if we could write in markdown instead of HTML.

Thanks! :)

**Comment by scott2b** [comment]
While this seems nice, it is out of scope of any roadmap we have for Timeline. I don't really see this getting done - at least not internally here. Closing as wontfix
