### ISSUE TITLE
"Women in Computing" Soundcloud Example no longer works

### ISSUE THREAD

**Issue by yawkity** [NUKnightLab/TimelineJS3#471]
The "Grace Hopper Invents The Compiler" Sound Cloud example on timeline.knighlab.com is no longer working. When arriving at the slide, the loading icon continues to run but the media never loads. 

<img width="1261" alt="screen shot 2017-02-08 at 3 37 50 pm" src="https://cloud.githubusercontent.com/assets/3255833/22758595/f69b5dca-ee14-11e6-8f52-c04bf8d38ea7.png">

**Comment by thijstriemstra** [comment]
Noticed same on OSX Firefox 51.

**Comment by yawkity** [comment]
Track no longer exists on SC, was probably lost during transition from Obama to Trump 😞

**Comment by yawkity** [comment]
Sent message to @JoeGermuska to update spreadsheet from https://soundcloud.com/whitehouse/grace-hopper-as-told-by-u-s to https://soundcloud.com/obamawhitehouse/grace-hopper-as-told-by-u-s, not a Software bug
