### ISSUE TITLE
Replace w3schools links

### ISSUE THREAD

**Issue by scott2b** [NUKnightLab/TimelineJS3#477]
There are some links to w3schools in the docs. We would like to replace those with relevant Mozilla Developer Network links

**Comment by zachwise** [comment]
Why?

**Comment by scott2b** [comment]
w3schools is not taken seriously by the community. Just MHO but I feel like linking to them undermines our credibility. I don't feel super strong about it but think it would be better not to. Also, more to the point, I think it would be better to link to a consistent source as much as it makes sense. We have a mix of w3s, Wikipedia, and MDN right now.

Re: community view of w3s, e.g., a quick search yielded this meta SO: http://meta.stackoverflow.com/questions/280478/why-not-w3schools-com. See also just about every comment ever made about w3s from any developer you trust

**Comment by zachwise** [comment]
I see. Depending on the audience, I always thought w3s was easier to read for someone new to HTML etc, but others might be better for developers.

**Comment by scott2b** [comment]
That could be a valid point. TBH, I don't have strong opinions about the content itself -- it's more about community perception and reputation. Perhaps it is easier/better for newcomers. If that's the case then it is a strongly valid point given the audience for our products -- Timeline in particular
