### ISSUE TITLE
Orangeline metadata titles need changed

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#478]
We should use `Timeline JS` not `TimelineJS3`.
Also in the twitter card we should include `@TimelineJS` since most people reference that account when referring to Timeline.

**Comment by bdin** [comment]
updated the metadata titles

**Comment by zachwise** [comment]
'<meta name="twitter:creator" content="@knightlab">' 
should be 
`<meta name="twitter:creator" content="@TimelineJS">'
and
`<meta name="twitter:description" content="Easy-to-make, beautiful timelines. @TimelineJS">`
should revert to 
`<meta name="twitter:description" content="Easy-to-make, beautiful timelines.">`

**Comment by zachwise** [comment]
The `<meta name="twitter:creator" content="@knightlab">`
should be 
`<meta name="twitter:creator" content="@TimelineJS">`
and
`<meta name="twitter:description" content="Easy-to-make, beautiful timelines. @TimelineJS">`
should revert to 
`<meta name="twitter:description" content="Easy-to-make, beautiful timelines.">`

**Comment by bdin** [comment]
Got it. Just made the updates!
