### ISSUE TITLE
Provide demo that does not rely on Google Drive

### ISSUE THREAD

**Issue by bbodenmiller** [NUKnightLab/TimelineJS3#479]
Some locations block access to Google Drive and as such the demos do not work. Please provide a demo not relying on Google Drive.

**Comment by scott2b** [comment]
Timeline fundamentally depends on Google Drive as it uses Google Spreadsheets for the data store

**Comment by bbodenmiller** [comment]
There is no way to use JSON data? Did only the old version support that?

**Comment by scott2b** [comment]
Yes, JSON is still supported. By demos I assumed you meant the examples hosted on our site which use Google Spreadsheets. We do not host JSON demos, but there are examples here https://github.com/NUKnightLab/TimelineJS3/tree/master/compiled/examples

**Comment by bbodenmiller** [comment]
Right, I meant it'd be nice if one of the JSON examples was hosted on the website.
