### ISSUE TITLE
Keyboard Navigation TimelineJS3

### ISSUE THREAD

**Issue by rubensben** [NUKnightLab/TimelineJS3#480]
Hi all, I realized the keyboard navigation with the left and right arrow disappeared since the first version and I need to put it back, without success, here is what I have added to timeline-min.js : 

```
document.onkeydown = checkKey;
function checkKey(e) {
    e = e || window.event;
    if (e.keyCode == '39') {
$( "nav_previous" );
    }
    else if (e.keyCode == '37') {
$( "nav_next" );
    }
}
```

Any help with that ?

**Comment by scott2b** [comment]
This issue should now be tracked as #502

**Comment by mgifford** [comment]
There's the left/right.  Not sure that's fixed, but let's say it is.  How do folks navigate to other elements within the boxes? Just looking at https://timeline.knightlab.com/
