### ISSUE TITLE
Timeline js is only working with mozilla 

### ISSUE THREAD

**Issue by jiwitesh** [NUKnightLab/TimelineJS3#483]
if we try to open the timeline.js in other browser except mozilla then its showing 
https://cloud.githubusercontent.com/assets/19591103/23643423/b222b1e8-0327-11e7-8080-65b25bd0c2dd.png

this error screens hot i enclosed

**Comment by thehandsomepanther** [comment]
@jiwitesh can you include more information, like a link to your actual timeline and the corresponding spreadsheet/JSON you used to construct it?

**Comment by jiwitesh** [comment]
@thehandsomepanther when i was try it in local system it was only working with mozilla. But when i hosted it on server now its working fine thanks
