### ISSUE TITLE
Timeline Error in Safari

### ISSUE THREAD

**Issue by eegreen** [NUKnightLab/TimelineJS3#487]
My spreadsheet event is from May 1, 2017 - Sept 1, 2017.  It is rendered properly on the timeline in Chrome.  In Safari, it is rendering as May 1, 2017 - January 1, 2017.

Safari Image of Timeline:
![image](https://cloud.githubusercontent.com/assets/26307590/23760882/ed5a66be-04a5-11e7-82ae-6db262a8a07f.png)

Chrome Image of Timeline:
![image](https://cloud.githubusercontent.com/assets/26307590/23761016/49c91eb8-04a6-11e7-8af8-d49724e7ba64.png)

Link to spreasheet (row 20):
https://docs.google.com/spreadsheets/d/15v8uLvrS5ykOJq8GzQjKO7dfg53hsz35r_OtlQ6OLng/edit#gid=0

**Comment by thehandsomepanther** [comment]
@eegreen, can you adjust the share settings on your spreadsheet?

**Comment by eegreen** [comment]
https://docs.google.com/spreadsheets/d/15v8uLvrS5ykOJq8GzQjKO7dfg53hsz35r_OtlQ6OLng/edit?usp=sharing



*From:* Josh Shi [mailto:notifications@github.com]
*Sent:* Thursday, March 09, 2017 9:18 AM
*To:* NUKnightLab/TimelineJS3 <TimelineJS3@noreply.github.com>
*Cc:* eegreen <eegreen@lbl.gov>; Mention <mention@noreply.github.com>
*Subject:* Re: [NUKnightLab/TimelineJS3] Timeline Error in Safari (#487)



@eegreen <https://github.com/eegreen>, can you adjust the share settings on
your spreadsheet?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NUKnightLab/TimelineJS3/issues/487#issuecomment-285417575>,
or mute the thread

**Comment by thehandsomepanther** [comment]
Can you provide more information, like what version of Safari you're using? Also, it looks like you're modifying the timeline a little. Could you send over a link to where you're hosting your timeline?

**Comment by eegreen** [comment]
I am using Safari 5.1.7 for Windows.



http://donnersandbox.lbl.gov/biosciences-annual-events/



*From:* Josh Shi [mailto:notifications@github.com]
*Sent:* Thursday, March 09, 2017 1:24 PM
*To:* NUKnightLab/TimelineJS3 <TimelineJS3@noreply.github.com>
*Cc:* eegreen <eegreen@lbl.gov>; Mention <mention@noreply.github.com>
*Subject:* Re: [NUKnightLab/TimelineJS3] Timeline Error in Safari (#487)



Can you provide more information, like what version of Safari you're using?
Also, it looks like you're modifying the timeline a little. Could you send
over a link to where you're hosting your timeline?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NUKnightLab/TimelineJS3/issues/487#issuecomment-285487775>,
or mute the thread

**Comment by thehandsomepanther** [comment]
@eegreen it seems like Apple stop supporting Safari for Windows in 2012. To be honest I wasn't even aware that Safari for Windows existed, but if Apple isn't interested in supporting it, I don't think we're interested in supporting it either.

**Comment by eegreen** [comment]
Thank you.  I’ll take a look to see if it works properly on a Mac.



Can you take a look at Firefox?  The Timemarker flags are Fading Out, but I
did not change any logic for them to do so.





*From:* Josh Shi [mailto:notifications@github.com]
*Sent:* Thursday, March 09, 2017 2:21 PM
*To:* NUKnightLab/TimelineJS3 <TimelineJS3@noreply.github.com>
*Cc:* eegreen <eegreen@lbl.gov>; Mention <mention@noreply.github.com>
*Subject:* Re: [NUKnightLab/TimelineJS3] Timeline Error in Safari (#487)



@eegreen <https://github.com/eegreen> it seems like Apple stop supporting
Safari for Windows in 2012. To be honest I wasn't even aware that Safari
for Windows existed, but if Apple isn't interested in supporting it, I
don't think we're interested in supporting it either.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/NUKnightLab/TimelineJS3/issues/487#issuecomment-285502318>,
or mute the thread
