### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by brandonprudent** [NUKnightLab/TimelineJS3#488]
Is there a more standard way to watch for changes to source/ and rebuild the project? It says to rerun fab build periodically, but that's a bit of a pain isn't it? I've found

fswatch -o source | xargs -n1 -I{} fab build

To be helpful on my setup (OSX). Perhaps that could be mentioned to save others some trouble?

**Comment by scott2b** [comment]
general build management is a known issue across several of our projects that we would like to address someday. No guarantees this will be done soon, but it is something that we want to address

Outside scope of current gitHub issue tracking
