### ISSUE TITLE
CSS files

### ISSUE THREAD

**Issue by clairetsai818** [NUKnightLab/TimelineJS3#490]
Hi! I'm a member of [CDNJS](https://github.com/cdnjs/cdnjs).
We'd like to add your lib on our CDN, but we found that the `compiled/css/timeline.css`between 3.1.10 and 3.4.6 look like all comments. Do we need to host it?
related issue: https://github.com/cdnjs/cdnjs/pull/10698

**Comment by JoeGermuska** [comment]
What do you mean "look like all comments"?

**Comment by clairetsai818** [comment]
like this https://github.com/NUKnightLab/TimelineJS3/blob/3.1.10/compiled/css/timeline.css
All of them are commented out.

**Comment by JoeGermuska** [comment]
There are a few banners in block comments (caused by a build-configuration error at that time) but the last block comment ends on line 19, position 1.  Because it's a block comment and not a line comment, the rest of the line is visible to a CSS processor.

**Comment by clairetsai818** [comment]
Thanks for you reply!

**Comment by JoeGermuska** [comment]
Thanks for helping get us on CDNJS 👍
