### ISSUE TITLE
how to start now ?

### ISSUE THREAD

**Issue by clakech** [NUKnightLab/TimelineJS3#495]
Hi,

I would like to know if possible to start the timeline to the first slide which current date (now) is between its start/end dates ?

Any advice to implement this if you which I contribute to the project by implementing this feature ?

Regards,

**Comment by thehandsomepanther** [comment]
The TimelineJS API allows you to jump to a particular slide by calling `timeline.goTo()` or `timeline.goToId()`, so you should be able to use Javascript to find the slide you want and then to navigate to it.
https://github.com/NUKnightLab/TimelineJS3/blob/master/API.md
