### ISSUE TITLE
Accessibility: Keyboard Navigation

### ISSUE THREAD

**Issue by mazhang2718** [NUKnightLab/TimelineJS3#502]
A couple of Zendesk tickets have requested keyboard navigation for accessibility purposes. There's probably a couple of different things we can do about this, as described [here](https://github.com/NUKnightLab/TimelineJS3/issues/270), but I can start working on a simple 'left/right arrow to navigate between slides' feature for now.

**Comment by rubensben** [comment]
Thx mazhang, you are a savior
