### ISSUE TITLE
Marker set at the wrong time (AM instead of PM) in the Navigation

### ISSUE THREAD

**Issue by MarcusAuer** [NUKnightLab/TimelineJS3#507]
CMS: durpal
Field: Date (Unix timestamp)
View, formatter: date and time
Time display: 24h (correkt Display everywhere within the site)
**Bug:**
The marker for all Events are placed in the morning: 07:10 = 7:10 AM; 15:20 = 3:20 AM
[Example](http://www.cinepoint.at/drupal/zeitleiste)

**Comment by scott2b** [comment]
I am unable to reproduce this problem. 15:20:00 for example is correctly converted for me into 3:20 pm. If this continues to be an issue, please submit a support request to https://knightlab.zendesk.com

Please include both your spreadsheet URL and the pubhtml link (from File > Publish to the web) in your request
