### ISSUE TITLE
Images don't load in IE or Edge

### ISSUE THREAD

**Issue by rosaliechan** [NUKnightLab/TimelineJS3#530]
A Zendesk user pointed out that some images on TimelineJS don't load in Internet Explorer or Microsoft Edge. The user was using IE11. Although the image links work on their own IE/Edge, and the Timeline itself works on IE/Edge, the images aren't loading when they're on the Timeline.

**Comment by scott2b** [comment]
Non-replicable. This may have been due to mixed protocol issues. Not fixing
