### ISSUE TITLE
IE 11 IFrame loading

### ISSUE THREAD

**Issue by admiralsmaster** [NUKnightLab/TimelineJS3#540]
I use [pdf.js](https://github.com/mozilla/pdf.js) to show PDFs without google docs integration.
I load an own json file with the content of my timeline:
```
...
"media": {
    "caption": "",
    "credit": "",
    "url": "/.../pdfjs/web/viewer.html?file=/images/texte/my.pdf",
    "thumbnail": ""
},
...
```

Firefox Chrome and other browsers running correctly and show the HTML file as IFrame.
But IE 11 and Microsoft Edge always try to load the path with Google Docs viewer.

**Comment by scott2b** [comment]
I am not sure what the /.../ path construction means and am surprised this works on any browsers. I would recommend using standard path constructions

In general, please submit support requests to our helpdesk at knightlab.zendesk.com

**Comment by admiralsmaster** [comment]
/.../ is a replacement for the original path. I removed the full URL, this URL is longer.
