### ISSUE TITLE
JSON format

### ISSUE THREAD

**Issue by jaepetto** [NUKnightLab/TimelineJS3#541]
Hi,

when I look at the sample JSON file you provide, the events are described as a list of date:
```
{
  "timeline": {
    "headline": "...",
    "type": "default",
    "startDate": "...",
    "text": "...",
    "asset": {
      "media": "",
      "credit": "",
      "caption": ""
    },
    "date": [
      {
        "startDate": "...",
        "endDate": "...",
        "headline": "...",
        "text": "...",
        "asset": {
          "media": "",
          "credit": "",
          "caption": ""
        }
      }...
```

When I look at the Timeline JS documentation, the JSON format should be a list of "event" (https://timeline.knightlab.com/docs/json-format.html)

However, when I change the `"date": [` to `"events": [`, the timeline won't load.

What is the JSON format you support?

Furthermore, events are supposed to support a group property. When I set it up on a date object, the dates do not get grouped.

Thanks in advance for your help.

**Comment by scott2b** [comment]
events must be a list of events, not dates. Please see this example for format: https://github.com/NUKnightLab/TimelineJS3/blob/master/website/templates/examples/houston/timeline3.json

Please contact support@knightlab.zendesk.com if you have further questions.

Thank you
