### ISSUE TITLE
QUESTION: Submit site as example?

### ISSUE THREAD

**Issue by DaveyJake** [NUKnightLab/TimelineJS3#544]
I work for USA Rugby and [we use TimelineJS](https://www.usarugby.org/about-usa-rugby/#fndtn-History).  Is there a way we can submit our site to hopefully be featured as one of your "examples?"  Please let me know.

Thank you for your time and keep up the great work!

**Comment by scott2b** [comment]
Those examples do not often get updated, but I added your Timeline to our internal notes that we keep on examples available
