### ISSUE TITLE
Is the media link supported?

### ISSUE THREAD

**Issue by dcameron** [NUKnightLab/TimelineJS3#548]
Hi, I'm the maintainer of a Drupal module that integrates with TimelineJS3.  One of my more inquisitive users [discovered that there are two undocumented media properties, link and link_target](https://www.drupal.org/node/2830544#comment-11796819), which supposedly can be used to wrap media with an anchor tag, complete with target attribute.  I checked the TL.Media.js class and verified that this is apparently something that media objects can do.  I've been asked to support these properties, but I'm reluctant to do it for undocumented features.

Will the link and the link_target properties continue to be a feature moving forward?  

Is there anything I should be aware of about these properties?  It looks like it would wrap _any_ media with a link, which I may or may not have to account for.

**Comment by scott2b** [comment]
Unless I am misunderstanding the field in question, this is not an undocumented field. The media field is almost always used in a Timeline

documentation on the media field in the spreadsheet is here: http://timeline.knightlab.com/docs/using-spreadsheets.html#media

for JSON it is here: http://timeline.knightlab.com/docs/json-format.html#json-media

**Comment by dcameron** [comment]
You are misunderstanding, but I will take the blame for that since I could have been slightly more clear in my introductory paragraph.

There are two undocumented _properties_ of media objects, link and link_target, that apparently are functional in TimelineJS.

**Comment by scott2b** [comment]
I have not tried it to verify it, but it appears to be an option to wrap media, such as an image with an anchor tag, and to specify the target.

You will want to verify that it works if you build support for it (open a Zendesk ticket if you have problems) but I don't see any reason why this would go away in the future. I have added documentation here: http://timeline.knightlab.com/docs/json-format.html
