### ISSUE TITLE
Will not exceed 20 slides

### ISSUE THREAD

**Issue by madigan-99** [NUKnightLab/TimelineJS3#550]
The prorgram will not log more than 20 slides. It will cut them off.

**Comment by JoeGermuska** [comment]
This is definitely not the case, as demonstrated by La Nación's [timeline of all the Popes](http://blogs.lanacion.com.ar/data/herramientas/todos-los-papas-en-un-timeline-js/).

The typical case when slides appear to be cut off is a blank row in your Google sheet. This is something outside our control, as Google only sends information up to the first blank line.  Check for that, and if you are still having issues, please use our [online support system](https://knightlab.zendesk.com/hc/en-us/requests/new) and be sure to include a link to your Google sheet.
