### ISSUE TITLE
Labels bug in cosmological.html example

### ISSUE THREAD

**Issue by robertocappa** [NUKnightLab/TimelineJS3#553]
This timeline shows "ago" label for years <0, but also for years > 0, that is not correct.

I've tried changing period_labels.bigdateformats (removing the "years ago" label) and the  messages.era_labels.negative_year, but this second label is never shown.

Any idea?

Thanks.

**Comment by scott2b** [comment]
Timeline does not handle well the mixing of prehistoric dates with newer dates. It is recommended that you do not put these on the same timeline

In general, please submit support requests to our helpdesk at knightlab.zendesk.com
