### ISSUE TITLE
All slides cut off, not displaying, after 3rd slide in Chrome 62, Mac

### ISSUE THREAD

**Issue by dlewand691** [NUKnightLab/TimelineJS3#557]
Updated to Chrome 62 on Mac and now every slide after the 3rd one is not displaying any content. It displays fine in Safari and Firefox. Cannot seem to find where/why it's happening in any of the inspector panels. 

There seems to be something going on with window resizing. If you shrink your window, you'll more of the later slides, but they will eventually cut off.  

<img width="1389" alt="screen shot" src="https://user-images.githubusercontent.com/1159913/32066999-a7f6b5ae-ba4f-11e7-9eec-3c8c547c3712.png">
<img width="1420" alt="screen shot 1" src="https://user-images.githubusercontent.com/1159913/32067000-a80db470-ba4f-11e7-9611-15901974caeb.png">

In action here:

https://www.dannylewandowski.com/_cog-DEV/_PROTOTYPING/build/AI/index.html

Any thoughts? Has anyone else seen this?

**Comment by JoeGermuska** [comment]
After updating to Chrome `Version 62.0.3202.75 (Official Build) (64-bit)`, I don't have any issues with the demonstration timeline on timeline.knightlab.com

When I visit your site, the Timeline CSS doesn't load (404) and there are other errors in the console which don't have any clear connection to timeline. Make sure none of those are impacting things.

I'm going to close this for now, as it doesn't seem to be something specific to TimelineJS. If you find a pattern with other timelines, or if after you address those other errors in the console you are still having issues, let us know.

**Comment by dlewand691** [comment]
It seemed to be a conflict with a couple other plugins that were being used. Thank you for your time and effort!
