### ISSUE TITLE
Add CommonJS or AMD support

### ISSUE THREAD

**Issue by icebox** [NUKnightLab/TimelineJS3#558]
Polluting the global space does not follow best practices. Libraries should be imported. 

`Module not found: Can't resolve 'TL.Timeline' `

**Comment by rexhxiao** [comment]
+1

**Comment by scott2b** [comment]
thanks for the feedback but there is not currently a development roadmap for this

**Comment by scott2b** [comment]
thanks for the feedback but there is not currently a development roadmap for this

**Comment by aantn** [comment]
It is worth pointing out that this is now supported:

```
import { Timeline } from '@knight-lab/timelinejs';
import '@knight-lab/timelinejs/dist/css/timeline.css';
```
