### ISSUE TITLE
TypeError: Unable to get property 'caption' of undefined or null reference<

### ISSUE THREAD

**Issue by eat-sleep-code** [NUKnightLab/TimelineJS3#564]
Why am I getting this error displayed on the screen (no errors in the Console)?

> TypeError: Unable to get property 'caption' of undefined or null reference

According to the documentation "caption" is not a required attribute so it shouldn't be throwing an error if it doesn't find it.

`<script type="text/javascript">
let timelineJSON = {
  "events": [
    {
      "start_date": {
        "year": "1997"
      },
      "text": "Example was founded as a place of beauty and serenity where those with special needs, both human and animal, special could mutually experience kindness and compassion."
    },
    {
      "start_date": {
        "year": "1998"
      },
      "text": "E achieves 501(c)3 status.\n\t\t\tImprovements are made to the property including a guest cabin that sleeps 4, barn and animal habitats.\n\t\t\tThe Ranch begins to welcome guests primarily for day visits, and continues to welcome special animal residents.",
      "media": {
        "url": "/Content/images/gallery/our-history/00002.png"
      }
    },
    {
      "start_date": {
        "year": "1999"
      },
      "text": "E partners with SARRC hosting 3 summer camps for children with autism and their families, with families participating in programs at the Ranch and staying off site in Heber & Payson (a 25-mile drive).\n\t\t\tGroups of individuals including special children from Valley schools enjoy animal interaction and other nature programs during day visits.",
      "media": {
        "url": "/Content/images/gallery/our-history/00007.png"
      }
    },
    {
      "start_date": {
        "year": "2000"
      },
      "text": "SARRC families enjoy second summer at E with five weekend camps."
    },
    {
      "start_date": {
        "year": "2000"
      },
      "text": "Through an alliance with Hospital, children at risk from ethnically related diseases enjoy a four-night stay, sleeping in tents.",
      "media": {
        "url": "/Content/images/gallery/our-history/00005.png"
      }
    },
    {
      "start_date": {
        "year": "2000"
      },
      "text": "Individuals represented by Hospice, Cancer Support Group and 10 other groups come for day visits, interacting with animals and participating in other nature related activities."
    },
    {
      "start_date": {
        "year": "2000"
      },
      "text": "EF begins to explore collaboration with other organizations serving children with special needs."
    },
    {
      "start_date": {
        "year": "2000"
      },
      "text": "Improvements to the property include additional animal habitats and handicap accessible restrooms with showers."
    },
    {
      "start_date": {
        "year": "2001"
      },
      "text": "EF Board of Directors engages example & Co. to perform a feasibility study to determine community support of camp facility for children with chronic illnesses and physical and developmental challenges."
    },
    {
      "start_date": {
        "year": "2001"
      },
      "text": "The Architectural Design Committee begins meetings with partnering organizations to gather information about their camp program, activities and needs unique to the constituency served by each group."
    },
    {
      "start_date": {
        "year": "2001"
      },
      "text": "A site suitability study determines Example is ideal property for a camp and retreat facility for those with special needs."
    },
    {
      "start_date": {
        "year": "2001"
      },
      "text": "U College of Architecture & Environmental Design is engaged for pre-design of the camp including a master site plan and schematic drawings with input from partnering organizations through bi-weekly design sessions.\n\t\t\tA Program Document is completed detailing spatial and programmatic needs for buildings and activity areas , function, spatial adjacency and equipment needs, and reviewed with each organization to ensure the facility would meet the needs of all the special children to be served."
    },
    {
      "start_date": {
        "year": "2002"
      },
      "text": "E continues to serve special needs guests primarily for day visits, and continues to welcome special animal residents.",
      "media": {
        "url": "/Content/images/gallery/our-history/00001.png"
      }
    },
    {
      "start_date": {
        "year": "2002"
      },
      "text": "EF engages K-Group as capital campaign managers and kicks off its capital campaign in November to raise funds for a Phase I expansion."
    },
    {
      "start_date": {
        "year": "2003"
      },
      "text": "EF President, donates the 45-acre site to Example Foundation."
    },
    {
      "start_date": {
        "year": "2003"
      },
      "text": "Studio M and the W Company are selected as the architectural and construction management firms for Phase I construction."
    },
    {
      "start_date": {
        "year": "2004"
      },
      "text": "Design Document Phase completed and groundbreaking for Phase I begins."
    },
    {
      "start_date": {
        "year": "2005"
      },
      "text": "Phase I construction is completed in September with a grand-reopening event at the Ranch.\n\t\t\tThe expanded facilities can accommodate up to 126 campers, caregivers and medical personal per camp or retreat session.",
      "media": {
        "url": "/Content/images/gallery/our-history/00006.png"
      }
    },
    {
      "start_date": {
        "year": "2005"
      },
      "text": "E welcomes groups for weekend retreats within one week of completion."
    },
    {
      "start_date": {
        "year": "2006"
      },
      "text": "E continues to ally with partnering organizations providing retreats for those with special needs of all ages during non-summer months, and holds first year of week-long overnight summer camps for children with special needs.\n\t\t\tEleven new partnering organizations host a camp or retreat at E.",
      "media": {
        "url": "/Content/images/gallery/our-history/00003.png"
      }
    },
    {
      "start_date": {
        "year": "2007"
      },
      "text": "Seven new partnering organizations are added to the EF family.",
      "media": {
        "url": "/Content/images/gallery/our-history/00009.png"
      }
    },
    {
      "start_date": {
        "year": "2008"
      },
      "text": "Ten new partnering organizations are added to the EF family.",
      "media": {
        "url": "/Content/images/gallery/our-history/00008.png"
      }
    },
    {
      "start_date": {
        "year": "2009"
      },
      "text": "Five new partnering organizations are added to the EF family."
    },
    {
      "start_date": {
        "year": "2009"
      },
      "text": "EF achieves Public Charity Status."
    },
    {
      "start_date": {
        "year": "2010"
      },
      "text": "New Partner Organization – <a href=\"/Content/pdf/en-us/2010-youth-evaluation-and-treatment-center.pdf\" target=\"_blank\" title=\"Click here to read a letter of thanks from Evaluation & Treatment Center.\">Evaluation & Treatment Center</a> – hosts two summer camps at E."
    },
    {
      "start_date": {
        "year": "2010"
      },
      "text": "Syndrome Network AZ joins the EF family with a camp for children with Down Syndrome and their families.",
      "media": {
        "url": "/Content/images/gallery/our-history/00004.png"
      }
    },
    {
      "start_date": {
        "year": "2010"
      },
      "text": "Kid’s Camp, serving children ages 6-12 in foster care and group homes, returns to E following a 2-year hiatus for reorganization."
    },
    {
      "start_date": {
        "year": "2011"
      },
      "text": "Studio MA receives <a href=\"/Content/pdf/en-us/2011-american-institute-of-architects-design-awards.pdf\" target=\"_blank\" title=\"Click here to read more about the American Institute of Architects  Design Award\">2011 American Institute of Architects Design Award</a> for the design and planning of Example."
    },
    {
      "start_date": {
        "year": "2011"
      },
      "text": "EF receives a gift from The  Charitable Trust for the establishment of The Center for Interaction, Hope & Healing which will include the Jazz-n-Jets Splash Zone for cooling off on warm summer days, and a new Center for Human-Animal Interaction providing access for even the most severely challenged campers."
    }
  ]
};
timeline = new TL.Timeline('Timeline', timelineJSON);
</script>`

**Comment by scott2b** [comment]
I have deployed a fix for this. Please let me know if this works for you.

Note that you may need to clear your cache to get the latest code from the CDN. Note also, your event text entries should be text data objects, not text fields. See the docs here: http://timeline.knightlab.com/docs/json-format.html#json-text

**Comment by eat-sleep-code** [comment]
I will check this out tonight / this weekend.   Thanks for the pointer on text data objects, i totally missed it.

Has this been deployed to NPM too?

**Comment by scott2b** [comment]
we do not distribute any node packages

**Comment by eat-sleep-code** [comment]
@scott2b Oh there is one out there currently.   https://www.npmjs.com/package/timelinejs3   

PS: You really should if it isn't a gigantic hassle as tons of folks use Node.
