### ISSUE TITLE
media property appears to be required for JSON data

### ISSUE THREAD

**Issue by scott2b** [NUKnightLab/TimelineJS3#565]
raised by #564 

The docs indicate the media property to be optional, and it seems that users should be able to have text-only slides with no media. however, events without a media property will throw a null access error trying to access the caption in the non-existing media

media should be made optional

**Comment by eat-sleep-code** [comment]
Thanks.   In the meantime, is there any quick workaround for this, short of adding an image to every item (which honestly won't work for our case where only about 30% of the items should have images)?

**Comment by scott2b** [comment]
Unfortunately that is the only workaround I can think of at the moment. I will see if I can look at this issue today. I don't expect it to be a difficult fix

**Comment by JoeGermuska** [comment]
The workaround is to include the media element with empty values. I haven't tested this directly from JSON, but one can make a Google-sheets driven timeline with no values in the media / media caption / media credit cells and everything works fine.

**Comment by scott2b** [comment]
I did not think this workaround was working, but just tried it again and yes this should work
