### ISSUE TITLE
Timeline won't load, "Missing start date" 

### ISSUE THREAD

**Issue by apendlet** [NUKnightLab/TimelineJS3#576]
Hi, whenever I make a timeline it doesn't work. This has happened both with my own timelines, and when I just copy and publish the default spreadsheet provided by KnightLab without changing anything. It gives me this message: 

MISSING START DATE. MAKE SURE THE HEADERS OF YOUR GOOGLE SPREADSHEET HAVE NOT BEEN CHANGED.

Is this a known bug? What could I be doing wrong, especially since it happens even with the default spreadsheet with no changes made to it. Thanks for the help. 
![timeline error](https://user-images.githubusercontent.com/38077216/38314773-a4ed4e8e-37ec-11e8-874a-8e2b11ffb4bb.png)

**Comment by JoeLeung32** [comment]
Me too, only success in preview-embed, same spreadsheets url
