### ISSUE TITLE
time reverse

### ISSUE THREAD

**Issue by YYYJJXZ3** [NUKnightLab/TimelineJS3#585]
I want to reverse timeline，i try to change json，not success。

i read json introduce page，not find anything useful information。

**Comment by ckeeney** [comment]
I'm not sure if this issue is clear, but I would like the timeline to be displayed reverse chronologically, with the newest slides being on the left and the oldest on the right.

The use case I have is to default to showing the most recent slide and allow the user to look at older slides while maintaining the traditional left to right reading direction.

**Comment by JoeGermuska** [comment]
We are unlikely to pursue this enhancement request. It seems to open up a lot of complicated questions to have the slides go in one direction but the navigation component to go in the opposite direction -- but I think most people would be quite confused to read a time navigation element in which the past was to the right of the future.

**Comment by ckeeney** [comment]
> to have the slides go in one direction but the navigation component to go in the opposite direction

I agree that would be confusing.  I'm not suggesting that.  In my use case, ideally the timeline would start at the slide with the newest datetime.  On the timeline, left would be newer and right would be older.  Clicking the right navigation button would progress backwards in time to the next slide, and vice versa.

When I use `start_at_end: true`, I want to tell a story reverse chronologically.  

My concern is that users will look for a way to proceed through the story by looking for an arrow on the right, and won't even see the arrow on the left, especially when the first slide has a video.

![image](https://user-images.githubusercontent.com/8799010/45640795-73627e80-ba68-11e8-8f84-13e36c5490a9.png)
