### ISSUE TITLE
Navigation arrows don't appear in MS Edge

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#587]
Reported to us via email:

the navigation arrows don't appear on [this timeline](https://www.lagotronicsprojects.com/en/about-us) in MS Edge.

![image](https://user-images.githubusercontent.com/46313/43964946-9418bca0-9c83-11e8-9900-b9869c55085a.png)
![image](https://user-images.githubusercontent.com/46313/43964958-9ade28b8-9c83-11e8-83bf-0b13375bfb95.png)

Needs verification that it's a broader issue, although given that the timeline there is embedded with iFrame, it's not likely that there's any issue with CSS interactions.

**Comment by fastfasterfastest** [comment]
Perhaps because there are javascript errors on that page.

**Comment by jripmeester** [comment]
The js errors have been fixed. But still no arrow. 
It seems that the icon font doesn't get loaded.

![screen shot 2018-08-31 at 10 50 25](https://user-images.githubusercontent.com/432051/44903025-c2d84900-ad0b-11e8-99c9-40b60c0d87b1.png)

**Comment by scott2b** [comment]
The same issue shows up in StoryMap: https://github.com/NUKnightLab/StoryMapJS/issues/415

woff2 files will be added to both projects to address this issue.
