### ISSUE TITLE
Ensure that events with the same date honor the sort order of the source data

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#59]
This has come up several times in git issues and support tickets. While I still believe that we should sort events based on their date, sometimes people have multiple slides with the same start date. In that case, we should allow them to prioritize.

I think the easiest solution would be to add a sequence number to each item as it's created, and then use that as a tie-breaker when things have the same start date.

**Comment by jywsn** [comment]
This doesn't seem to be an issue anymore.  If someone can recreate the problem, re-open.

**Comment by fernandopagano** [comment]
Hello, 

I have a question related to this issue. Is there a way to create the markers with some property that define the view priority between the markers?. Like in the example below, I would like the marker "Line 6 POD HD500X" to show over the others markers by default.
Thanks.

![image](https://cloud.githubusercontent.com/assets/19935306/16052780/14464500-323c-11e6-9994-57f3144a158a.png)
![image](https://cloud.githubusercontent.com/assets/19935306/16052787/236b1eca-323c-11e6-91e6-f9498c420645.png)

**Comment by JoeGermuska** [comment]
No, this isn't something currently supported. At this time, having never heard a request for it before, my sense is that it adds much complexity for relatively low payback.

One way to control the layout of events is to give them groups. Events in the same group will be in the same row or rows, so you can avoid having an earlier event obscure a later-but-higher-priority event by having them in separate groups. 

You can also use the [`timenav_height`](http://timeline.knightlab.com/docs/options.html#timenav_height), [`timenav_height_percentage`](http://timeline.knightlab.com/docs/options.html#timenav_height_percentage) [`marker_height_min`](http://timeline.knightlab.com/docs/options.html#marker_height_min) and related properties to make your nav bar taller -- Timeline tries to avoid overlapping events at all if there's enough space in the timenav area to lay them out without overlap.

**Comment by fernandopagano** [comment]
Thanks Joe for the advice.

The final purpose is to have a preferred marker view on top when the maximun zoom out is reached.

I will try to workaround it with the Groups, but Can I add a custom event handler to run when the zoom out is triggered?.
