### ISSUE TITLE
Missing variable "time" in each language js file in locale folder to have correct date format in headlines

### ISSUE THREAD

**Issue by comproperty247** [NUKnightLab/TimelineJS3#598]
Hi,
After struggling for a while  to get the correct format date for the date in the headlines, I found out is missing the variable "time" in the language file at folder "locale".
In my case as portuguese, I don't want the date showing as 10H PM but 22H.
The language file \locale\pt.json was loaded correctly but the date was still in "english format".

The solution after all, is to add the missing key  "time" at "dateformats": {  :

This is now my new language file , I paste here the 2 lines missing, they are the 2 at left padding.
For better finished work, the rest of the format should be without "TT" and replace the "h" to "H"

 
    "dateformats": {         
"time": "H:MM:ss' <small>'d mmmm',' yyyy'</small>'",
"time_no_minutes_short": "H",
        "full_long": "mmm d',' yyyy 'at' H:MM", 
        "full_short": "mmm d", 
        "full": "mmmm d',' yyyy", 
        "month_short": "mmm", 
        "time_no_seconds_small_date": "H:MM'<br/><small>'mmmm d',' yyyy'</small>'", 
        "month": "mmmm yyyy", 
        "time_no_seconds_short": "H:MM", 
        "time_short": "H:MM:ss", 
        "year": "yyyy", 
        "full_long_small_date": "H:MM'<br/><small>mmm d',' yyyy'</small>'"
    }

**Comment by JoeGermuska** [comment]
Thank you for suggesting this fix. We've updated the `pt.json` (and `pt-br.json`) files to use 24-hour time. We preserved the "small date" markup which is omitted from your sample code.

The actual tagged release is pending since these are small, and since you have already developed your work-around.
