### ISSUE TITLE
VCO.Media.Website obsolete?

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#60]
When one uses a URL which matches no other media type but begins with `http://`, it is assigned the "VCO.Website" media type.

We no longer use Pagepeeker. In fact, the URL is just presented as a link.

Should we just remove this media type and start to build a mechanism for gracefully handling unrecognized media types?

**Comment by zachwise** [comment]
VCO.Media.Default

**Comment by JoeGermuska** [comment]
@zachwise what is VCO.Media.Default supposed to do?

**Comment by zachwise** [comment]
How about this service from Embedly http://embed.ly/docs/api/extract/endpoints/1/extract

**Comment by zachwise** [comment]
I think we need a Media Default also, to handle anything that doesn't match

**Comment by JoeGermuska** [comment]
If we want to use Embedly, I think this is more appropriate: http://embed.ly/docs/products/cards
