### ISSUE TITLE
Any plans to update NPM version?

### ISSUE THREAD

**Issue by tomisaacmarshall** [NUKnightLab/TimelineJS3#611]
Hi guys

First, thanks very much for the library!

Just wondered, are there any plans to bring the NPM package up to date (and keep it up to date)?

It seems to be on 3.4.0 rather than 3.6.3, with last update 2 years ago

(I see this is touched upon in some other issues e.g. here https://github.com/NUKnightLab/TimelineJS3/issues/589 but not as the primary purpose of the issue)

Cheers!

Tom

**Comment by wickkidd** [comment]
Also there are no exports (commonjs or es6). Exporting es6 modules would make this a viable option for many frontend devs out there, not to mention making it tree-shakable. This would lead to a lot more exposure for the school...wink wink.

**Comment by baohouse** [comment]
I looked at the NPM repo, it was published by a mark.rairdon. But I only see that he has his own fork of timelinejs3 and no other contributions. It's quite possible he created a fork and published timelinejs3 to NPM himself. The version on NPM might not be officially managed. Probably need to reclaim the package name by following the [package naming dispute resolution guide](https://www.npmjs.com/policies/disputes).

**Comment by JoeGermuska** [comment]
For the record, since 3.7.0, Knight Lab is publishing to npm at [@knight-lab/timelinejs](https://www.npmjs.com/package/@knight-lab/timelinejs).
