### ISSUE TITLE
Footer tweaks for TimelineJS 3 Website

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#62]
![feedback on footer](https://cloud.githubusercontent.com/assets/741789/6062876/b4e9acf4-ad18-11e4-92b0-9cf2288f54aa.png)

Center copyright.
Address text 14px. Do we even need the address text in the footer?

**Comment by zachwise** [comment]
I think the copyright text should come down in size too.

**Comment by hbillings** [comment]
Tweaking the font size now. Miranda's instructions to me were to copy the Pitcha footer and add the address.

**Comment by zachwise** [comment]
I think it would look better by adding a 3rd graph to the text saying "The Knight Lab is located at..."

**Comment by hbillings** [comment]
I like the way that looks, but it obscures the address. Suggested fix: 
![screen shot 2015-02-05 at 9 42 32 am](https://cloud.githubusercontent.com/assets/509309/6063253/68d7fc00-ad1b-11e4-8f26-83e2f96cbcd7.png)

**Comment by zachwise** [comment]
Needs a lot more top margin and smaller type size
