### ISSUE TITLE
Timeline doesn't load spreadsheet

### ISSUE THREAD

**Issue by thingsbehindthesun** [NUKnightLab/TimelineJS3#626]
It appears the whole app is broken, it won't load a test spreadsheet I have copied from the loading bar...

**Comment by JoeGermuska** [comment]
TimelineJS3 is functioning normally. There is probably an issue with your test spreadsheet.

Please use [Zendesk](https://knightlab.zendesk.com/hc/requests/new) for support issues rather than GitHub.
