### ISSUE TITLE
Responsive stuff for website

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#63]
The JS moniker is breaking mobile layout with it's offset:
![js break](https://cloud.githubusercontent.com/assets/741789/6063007/a45a84fc-ad19-11e4-8517-11ca594d5cf6.png)

Responsive thumbnails to fill horizontal space:
![responsize size thumbnails](https://cloud.githubusercontent.com/assets/741789/6063013/b442a14c-ad19-11e4-9de8-51431393c999.png)

**Comment by hbillings** [comment]
I didn't realize this until just now, but the viewport meta tag is commented out, with a note that someone needs to fix things in Blueline before it can be uncommented. These mobile styles don't actually render on devices. I don't know what it is that's broken in Blueline -- would it be worth uncommenting that tag to see how it looks?
