### ISSUE TITLE
Fix simple typo: overriden -> overridden

### ISSUE THREAD

**Issue by timgates42** [NUKnightLab/TimelineJS3#634]
# Issue Type

[x] Bug (Typo)

# Steps to Replicate

1. Examine compiled/js/timeline-min.js, compiled/js/timeline.js, source/js/data/TL.Data.js.
2. Search for `overriden`.

# Expected Behaviour

1. Should read `overridden`.

**Comment by JoeGermuska** [comment]
Typo is in inlined Zepto code, which we'd prefer ultimately to remove from TimelineJS, but also, until we do, which we'd prefer not to touch, even if the typos are only in comments.
