### ISSUE TITLE
Timeline won't load; "missing start date"

### ISSUE THREAD

**Issue by angrypanda1** [NUKnightLab/TimelineJS3#638]
When I try to preview the timeline, it says, "Missing start date. Make sure the headers of your google spreadsheet have not been changed." 
This is my spreadsheet.
https://docs.google.com/spreadsheets/d/1xJbCOmS_yx-gorVxrCZxZCROHFT1svImk8d8wsdi250/edit?usp=sharing

**Comment by JoeGermuska** [comment]
This spreadsheet seems to function as expected

https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1xJbCOmS_yx-gorVxrCZxZCROHFT1svImk8d8wsdi250&font=Default&lang=en&initial_zoom=2&height=650

In the future, please direct support requests to support@knightlab.zendesk.com or [use the online form](https://knightlab.zendesk.com/hc/en-us/requests/new).
