### ISSUE TITLE
Error occured reading spreadsheet data

### ISSUE THREAD

**Issue by stumueller** [NUKnightLab/TimelineJS3#639]
Hi
I am currently running TimeLineJS on my windows web sever. I got the files from: https://cdn.knightlab.com/libs/timeline3/latest/timeline3.zip

All works fine.

However when I download the zip file of 3.6.6 from here and extract the compiled directory, replacing my current directories with the ones from compiled I get an error message: An unexpected error occurred trying to read your spreadsheet data [TypeError]

As soon as i go back to my original directories it works fine.

What am I doing wrong?

**Comment by JoeGermuska** [comment]
It's impossible to know without a test case. Please provide the URL to your Google sheet.

Generally, support questions such as this are better handled through our Zendesk system, so unless you want to share your spreadsheet URL here, please re-submit this question via [the form](https://knightlab.zendesk.com/hc/en-us/requests/new).
