### ISSUE TITLE
"Dual arc" idea

### ISSUE THREAD

**Issue by lukerague** [NUKnightLab/TimelineJS3#64]
Minus the css customization, this all seems possible with a little creativity on the user's end. But I would be remiss to not bring the idea to everyone's attention.

As per zendesk ticket 995: "I've been looking for a way to display two "storyline arcs" within a 
timeline. I saw your note on the TimelineJS 3 page about how the 
"flexible row layout is no longer limited to 3/6 rows". I have an idea 
about how you could implement it: 
Allow the user to specify the number of vertical rows of a timelineAllow 
the user to specify a row range for each item to be constrained on. 
For example, if I specify 6 rows vertically for the timeline to have, I 
would like "Arc 1" items I designate to only span across rows 1-3 and 
"Arc 2" items to only span across rows 4-6.

If you want to take it further, it would be nice to be able to color 
code and label the timeline arcs. Or at the very minimum, set a 
background color to "item box" displayed on the timeline.

You can get an idea of the timeline arcs from Aeon Timeline:

http://www.scribblecode.com/videos.html 
(watch "Getting Started" or the "Orient Express" example)

Notice how they label the arcs in Aeon...along the left edge."

**Comment by JoeGermuska** [comment]
In some ways this is similar to how "tags" work in the current TimelineJS, except that events with the same tag are constrained to a single row. Arguably, we could just direct people to use tags for this once #33 is done. And we could consider allowing tagged events to use more than one row as described here, although I'm not sure I'm persuaded that it's something that will be used enough to be worth the effort vs maintaining the one-row-per-tag constraint.

**Comment by lukerague** [comment]
Yeah, it was my thought once the tags are functional, he could break each arc into two or three thematic tags and with some creative flair they would appear as a cohesive unit. I agree that this seems too rare a use-case to build for it.
