### ISSUE TITLE
Non-Chronological Timeline Order 

### ISSUE THREAD

**Issue by bogetwin** [NUKnightLab/TimelineJS3#640]
I would like to create a timeline that uses the TimelineJS interface but presents the events in the timeline through a non-chronological order. In other words, I would like the events to go something like: 1923, 1968, 1783, 1989, 1619, 1679, 1873. Is there a way, maybe through hash_bookmark or gotoID, to input an alternative ordering for the events? I would also like to maintain the user interface so when someone is on the 1968-event and they click the forward button, it launches them "backward" to 1783. If this is confusing I can clarify. Does anyone have ideas for how I could do this?

**Comment by JoeGermuska** [comment]
This is not something which we will do in TimelineJS. It is counter to the design principles for the tool, and seems, frankly, user-hostile.

That said, TimelineJS is open source. You could fork it, and maybe just take out the part where it sorts events according to their dates, and it would probably do something like what you describe. But those details are left as an exercise for the hacker.
