### ISSUE TITLE
ERROR: TypeError: t.appendChild is not a function on Responsive/Mobile Device

### ISSUE THREAD

**Issue by wwbcus** [NUKnightLab/TimelineJS3#642]
![Timeline error on mobile](https://user-images.githubusercontent.com/53305772/87156050-06962500-c28a-11ea-8c80-5b496d7dae57.jpg)

Hi - the timeline is no longer working on mobile devices - however, works fine on desktop. I'm using the latest version of Chrome for Android. The error is:

ERROR: TypeError: t.appendChild is not a function

My webpage: https://www.bullis.org/about/history

However, I'm seeing this error across the board ex: https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html

Will there be a fix for this?

**Comment by larusalka** [comment]
It has already been fixed. I was just going to report it but it's working fine now!
Thank you very much!

**Comment by JoeGermuska** [comment]
Yes, this was fixed with 3.7.1 which was released this morning.

**Comment by wwbcus** [comment]
Wonderful! Thank you.

Thank you for your kindness,
Wendy

[WWBC-logo-2018.fw]
Wendy L. Wheeler, C.A.
Owner | Brand & Marketing Consultant
[one_brand_voice_love.fw]
WWBC.us - Marketing, Brand Identity & Website Development
wendy@wwbc.us<mailto:wendy@wwbc.us>
240.745.5130<tel:2407455130>
www.wwbc.us<http://www.wwbc.us/>
[cid:image003.png@01D65757.73AF7C20]<https://www.facebook.com/wwbc.us/>  [cid:image004.png@01D65757.73AF7C20] <https://twitter.com/WWBCUS>  [cid:image005.png@01D65757.73AF7C20] <https://www.youtube.com/channel/UC0_Pf6FHKExS-fHAD25_tnQ>
look what WWBC.us can do for you!
[A screenshot of a computer  Description generated with very high confidence]<https://youtu.be/FS6DqyjKrfE>
