### ISSUE TITLE
back button "tl-icon-goback" doesn't do anything

### ISSUE THREAD

**Issue by mwangdakota** [NUKnightLab/TimelineJS3#647]
It does not seem that the "go back" button under the magnifying glasses does anything on the main timeline page. https://timeline.knightlab.com/

This is tested in firefox and chrome.

checking the examples, it appears the back button worked in presumably an older version of timeline.js: https://vinepair.com/wine-colonized-world-wine-history/#0

**Comment by JoeGermuska** [comment]
I cannot verify this report. When I try the "Women in Computing" timeline at timeline.knightlab.com on MacOS Firefox, Chrome, and Safari, clicking that button takes me back to the title page, as expected.

**Comment by JoeGermuska** [comment]
Tested on iOS Safari and Chrome as well. Works as expected.
