### ISSUE TITLE
Invisible characters in header cells breaks Google Sheets reading.

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#656]
A [Zendesk user reported](https://knightlab.zendesk.com/agent/tickets/7873) a previously functioning timeline was failing with "Timeline configuration has no events."

Upon closer review, the value of the A1 cell of their Google sheet was `Year\n`; the invisible newline at the end caused Timeline to see no year for any events, and rows with no year which are not 'title' rows are discarded, truly leaving no events.

This was not seen in the past because of how the Google Sheets v3 "feed" API handled converting header row values to data keys.

Given that we know what the headers should be, it should be safe to trim whitespace from them when parsing the CSV.

**Comment by jimmykl** [comment]
@JoeGermuska I suspect it could be a similar thing causing #657 What is the easiest way to debug the header row values?
