### ISSUE TITLE
custom fonts as described in documentation not working

### ISSUE THREAD

**Issue by chsteiner** [NUKnightLab/TimelineJS3#661]
In https://timeline.knightlab.com/docs/instantiate-a-timeline.html you describe how to use one of the fonts that you provide. However, when included the css rules are always overwritten by font.default.css because this is what is set in Load.js:
![image](https://user-images.githubusercontent.com/28706050/95750311-3e53a500-0c9d-11eb-8bd5-4919b503bd8c.png)

I only found out by setting the option script_path: "https://www.google.com/" to test where the default css is coming from.

I think this is a bug as I also couldn't find an option for activating the custom font anywhere else.

**Comment by JoeGermuska** [comment]
Sorry for the documentation inconsistency. This must be something which changed when we [rewrote the core of TimelineJS earlier this year](https://knightlab.northwestern.edu/2020/07/09/timelinejs-update/index.html).

You should be able to override the fonts when instantiating your timeline by setting the `font` option to the fully-qualified URL of your font file.  For example, something like:

```html
          <script type="text/javascript">
            var additionalOptions = {
              font: 'https://example.com/path/to/font.custom.css'
            }

            timeline = new TL.Timeline('timeline-embed',
            'https://docs.google.com/spreadsheets/u/1/d/1xuY4upIooEeszZ_lCmeNx24eSFWe0rHe9ZdqH2xqVNk/pubhtml',
            additionalOptions);
          </script>
```

note that right now, the code requires a fully-qualified URL (beginning with `http` or `https`).  We need some cue about whether of not the value of `font` is one of the set of supported fonts, in which case a path is constructed, or whether it's meant to be loaded as is.  If we heard from users that there's a need to support URL fragments that aren't fully-qualified, we could discuss which specific way we'd loosen that restriction.

So, for now, I'm going to treat this as a documentation bug, unless you find that it doesn't work as described above.

**Comment by chsteiner** [comment]
It works as described by you! Thanks. So definitly a documenation bug, as the option "font" is missing entirely in the documentation: https://timeline.knightlab.com/docs/options.html

**Comment by JoeGermuska** [comment]
This documentation was added some time ago in 9561250cc7defa275b3e7eca9470ed2724abe7c6 and now `font` is the first option documented on https://timeline.knightlab.com/docs/options.html
