### ISSUE TITLE
The anchor part of the url doesn’t change as the user moves through the timeline.

### ISSUE THREAD

**Issue by paul-hammant** [NUKnightLab/TimelineJS3#669]
Each timeline entry has a ID but the url isn't showing it. Nor can a timeline leverage it if the user types it into the url field themselves. It'd be great if this worked

**Comment by JoeGermuska** [comment]
To make this work, set the `hash_bookmark` option to true when instantiating the timeline.

See http://timeline.knightlab.com/docs/options.html for more configuration options.

**Comment by paul-hammant** [comment]
Works a treat, thanks. I'd searched for 'anchor' in doco which is why I missed it
