### ISSUE TITLE
getGroupLabels will allow for a group having more than one row of events

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#67]

**Comment by jywsn** [comment]
@jordan estimate a couple days, mainly because I need to reacquaint myself with how the groups work

**Comment by jywsn** [comment]
I *think* this is working.  I added "groups_test_..." files to the compiled/examples directory.

Deployed to cdn dev

09a76b8dff8af1f9e559212243fb12acf74a6536

**Comment by jywsn** [comment]
Going to be doing more work on the allocation of rows among groups that need them. Removing the 'ready' label for now,

**Comment by jywsn** [comment]
Updated TimeScale to try and distribute extra rows equally among groups that need them, with priority given to groups with the most overlaps.  Deployed to dev cdn.

7b9120902783344652bd87c61b757bc340f02d4d

**Comment by JoeGermuska** [comment]
Verified [This spreadsheet](https://docs.google.com/spreadsheets/d/1a8jYcSMWGXupicLJhtNAhkQfta8Fc5qKinDIJtroOAI/pubhtml) can be used to demonstrate. Note that if the timeline's height is constrained, some groups may still get overlapping events. For example, using the above a default 650 pixel high Timeline only gets four rows, but would need six to have all groups overlap-free. Using a larger height (eg 1000 px), one can see that all of the groups get as many rows as they need.
