### ISSUE TITLE
Deprecation warning : Synchronous XMLHttpRequest on main thread when using language in settings

### ISSUE THREAD

**Issue by andrezube** [NUKnightLab/TimelineJS3#670]
I get the following warning when setting the language in the options object.
`[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.`

TimelineJS is fetching the language from their server, but even if i set the `script_path` option to a json file inside my project i get this warning.

**Comment by JoeGermuska** [comment]
TimelineJS 3.8.12 is released, including this fix.
