### ISSUE TITLE
Youtube videos in the timeline - how to click through to the original YT page

### ISSUE THREAD

**Issue by paul-hammant** [NUKnightLab/TimelineJS3#671]
The timelines plays the embedded video very well. But doing so disable the link to the source. Would TimelineJS3 be better it is also auto-created a link to the origial adjacent to the embed? 

Or is this for the people making the timeline to but <a href=''></a> html in the text field?

**Comment by JoeGermuska** [comment]
We feel that it's not up to us to choose for all timeline creators that they must include a link to their YouTube video in any specific way. It would be exceedingly complex to support configuration disabling such a link, and it's relatively straightforward to use HTML to add links in the caption or credit. Also, while perhaps not all know, the "YouTube" logo in the embedded player is a link to the source video on youtube.com
