### ISSUE TITLE
Reverse timeline order

### ISSUE THREAD

**Issue by rockylhc** [NUKnightLab/TimelineJS3#679]
Is there a way to reverse the order, which display the timeline start from latest?

**Comment by JoeGermuska** [comment]
There is a configuration option to begin presentation of a timeline at the last event, and another to begin at any arbitrary event number, but there is no support for clicking the right side arrow and moving to an earlier event, or for rendering the timenav section such that earlier events appear to the right of later events.

This is an occasionally requested feature which we will not support, given the overwhelming connotation of left/earler -> right/later in all kinds of information presentation.

Remember that TimelineJS is open source, so those who are motivated are welcome to look at changing the code to work that way for their own purposes. Just to be clear, we would not accept a pull request implementing that feature.
