### ISSUE TITLE
Date localization issue when using JSON data

### ISSUE THREAD

**Issue by qubero** [NUKnightLab/TimelineJS3#682]
Faced a localization issue when using JSON data.
I am using the locale option, but it does not apply to all dates.
Dates are incorrect in the timeline and in the titles.
There is no such problem when making a timeline from a Google Spreadsheet.
How can I fix it?
![image](https://user-images.githubusercontent.com/22447973/107624591-2cded180-6c6c-11eb-9fe6-e4d78ee360f1.png)

**Comment by JoeGermuska** [comment]
We'll be able to address this more efficiently if you can provide a link to a timeline which demonstrates the problem, or some other test case. If you're hesitant to post a link on the public Github site, this is probably a better fit for our [online support system](https://knightlab.zendesk.com/hc/en-us/requests/new) anyway.

**Comment by qubero** [comment]
> We'll be able to address this more efficiently if you can provide a link to a timeline which demonstrates the problem, or otherwise provide us with test case rather than leaving us to attempt to reproduce the issue ourselves.
> 
> If you're hesitant to post a link on the public Github site, this is probably a better fit for our [online support system](https://knightlab.zendesk.com/hc/en-us/requests/new) anyway.

Thanks for reply!
[Pen](https://codepen.io/wolsos/pen/zYoowwy) which demonstrates the problem.
As you can see, there is additional option `language: ru`, but it only affects dates in `div .tl-slidenav-description`

**Comment by JoeGermuska** [comment]
Thank you for taking the time to create a pen.  

I think you've flushed out a timing problem, perhaps complicated by the fact that JSON loads much faster than Google Sheets configuration.

I notice that upon first load of the pen, the date under the "next" arrow is formatted using the English localization, although moving off and back to that slide causes that date to later appear in Russian.

I'm not sure when we'll start work on this. Timing problems can be complicated, but perhaps we can just send a "language set" event and have various components re-draw based on the new language...
