### ISSUE TITLE
timeline error, because of locale/en.json

### ISSUE THREAD

**Issue by superpikar** [NUKnightLab/TimelineJS3#683]
Hi, thanks for the great timeline library!

**Description**
I recently encounter an issue timeline is not rendered, the error message is :
```
JSON.parse: expected ',' or '}' after property value in object at line 53 column 27 of the JSON data
```
![timeline-knightlabs-error](https://user-images.githubusercontent.com/2832280/107843840-e8d10580-6e00-11eb-9c3d-deb982019c63.PNG)

**How to reproduce**
- open https://timeline.knightlab.com/
- inspect dev console / network request tab

the json file doesn't support comment, see https://stackoverflow.com/questions/244777/can-comments-be-used-in-json

**Comment by rolbr** [comment]
Just stumbled across this, glad to see this issue has already been opened.

File in question: https://github.com/NUKnightLab/TimelineJS3/blame/master/src/js/language/locale/en.json
The obvious solution would be to remove comments from `en.json`.

However, looking at the commits for that file, I have the feeling that those comments are intended to be there and then be stripped upon build – and **this cleanup** is in fact what's failing.

**Comment by citizenkepler** [comment]
I also have encountered this and while this issue needs to get fixed with the cleanup removing the comments, can we get the CDN version to have the comments removed as a quick stopgap to get timelines working again?

**Comment by JoeGermuska** [comment]
This issue has been resolved. We apologize for the inconvenience.
