### ISSUE TITLE
Add option to disable story container

### ISSUE THREAD

**Issue by andrezube** [NUKnightLab/TimelineJS3#686]
Is there a way to disable to story container? I only need the timenav below the story container. Currently i'm removing the story-container via css. It would be nice if there is an option to disable it, so its not loaded in the background.

**Comment by JoeGermuska** [comment]
TimelineJS is specifically designed for storytelling, so we are not motivated to add further features to disable that part of a timeline, particularly when, as you've found, there is a way to disable it for those who are so motivated.
