### ISSUE TITLE
Navigation with Arrow-Keys

### ISSUE THREAD

**Issue by CKranebitter** [NUKnightLab/TimelineJS3#688]
Hi Timeline-Team,

I think I found a bug when navigating the timeline with Arrow-Keys.
If the last slide is selected and e.g. »Arrow-Left« is pressed (and »GoNext« is called), an error is listet in the console because the last slide is reached.
It would be great to have this error fixed in future releases.

Many thanks.
Best regards.
Christoph.

**Comment by JoeGermuska** [comment]
As of TimelineJS 3.9.0 (released 2022-10-07) this should be addressed.
