### ISSUE TITLE
Pictures in TimelineJS

### ISSUE THREAD

**Issue by akanksha-b14** [NUKnightLab/TimelineJS3#689]
Hi,

I am using the TimelineJS tool to host a timeline. When I add a google drive image URL in the column O, it appears in the timeline but it comes with a grey background and the caption aligned to the left hand side. Sharing a screenshot to give more clarity.

I am not noticing this issue when I load the same image from another site.

Also, I tried adding my images to a public github repo as well. But on giving the github URL they do not load on the timeline page. Are github links not supported for image hosting?

Thank you!

Appreciate the help.
<img width="908" alt="Screenshot" src="https://user-images.githubusercontent.com/77793414/110889327-e347dc00-8328-11eb-9332-79d68e23a39c.png">

**Comment by JoeGermuska** [comment]
First a note: typically we prefer to answer support questions via [our Zendesk system](https://knightlab.zendesk.com/hc/en-us/requests/new) and reserve GitHub issues for software bugs and feature requests.

That said, images stored on Google Drive are not known by TimelineJS to be images; the URL is not distinguishable from a PDF or any other filetype. Therefore, TimelineJS uses Google's "viewer", which is what creates that grey background.

Generally speaking, "cloud drive" services do not want to be used for the kind of image hosting which would not come with the "viewer", and they often are implemented in a way which prevents using them as such, or they change how they work such that they are not reliable.

Here is a statement from Google about the disabling of Google Drive web hosting, which was what, at one point, made it possible to use Google Drive as a direct image source:
 https://gsuite-developers.googleblog.com/2016/07/reminder-turn-down-of-google-drive-web.html

This newer page
https://blog.usejournal.com/host-static-images-for-your-apps-or-website-on-google-drive-hotlink-to-gdrive-images-358d6fcf8ef7
describes a method for using images stored on Google Drive, but this usage is not technically supported, and might stop working without any notice.

**GitHub for image hosting**

TimelineJS has no specific mechanism for recognizing a GitHub URL and treating it distinctly. The recommended way to use GitHub for image hosting would be to use [GitHub Pages](https://pages.github.com/).  It may be possible to use GitHub "raw" URLs, but our understanding is that GitHub prefers (or maybe prohibits in their ToS) this kind of hosting.
