### ISSUE TITLE
imprecise end of time span

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#69]
This is an example from the Mark Twain example in the TimelineJS3 repository. Note the difference between the official end date and where the line intersects the index.

![image](https://www.evernote.com/shard/s5/sh/fc963d09-a637-476f-940b-ced5e9583c8b/36040754d7786e9cba84eda3e8643eb2/deep/0/timeline3_end_date.png)

**Comment by zachwise** [comment]
The timeline display is correct, it should be 1928. The bug must be in VCO.Date `getDisplayDate`
https://github.com/NUKnightLab/TimelineJS3/blob/master/source/js/date/VCO.Date.js#L36

**Comment by zachwise** [comment]
or in `VCO.Language.prototype.formatJSDate `
https://github.com/NUKnightLab/TimelineJS3/blob/master/source/js/language/VCO.Language.js#L109

**Comment by jywsn** [comment]
Yep, appears to be a timezone issue with VCO.Language.prototype.formatJSDate

**Comment by jywsn** [comment]
The problem is VCO.Date._getDateData() is ending up returning a object with 'day' = 0.  So the inner JS Date object (date_obj) ends up pushed back a day into 1927.

**Comment by jywsn** [comment]
5a23f6af997c1f3fd11abb1431024d5c7879e433

pushed to cdn dev version
