### ISSUE TITLE
Issue with Knightlabs TimlineJS3

### ISSUE THREAD

**Issue by dadofdivas** [NUKnightLab/TimelineJS3#695]
When I try and use this, I keep getting an error that my google spreadsheet is not correct, but I followed all of the instructions. The document I was trying to build a timeline for was: https://docs.google.com/spreadsheets/d/e/2PACX-1vSnJnrC1efncOyGORXr2W1sGxNVIdaNEIff5ToaoX37Y4yatyrQYRNPPnNZzixnOU7zmesRBu3R8Wdp/pubhtml?gid=0&single=true

**Comment by JoeGermuska** [comment]
You are using the share URL provided by the "publish to the web" interface. Please revisit [step 2 of the instructions](http://timeline.knightlab.com/#make-step-2) at timeline.knightlab.com for an illustrated guide to where to find the correct URL to use in this circumstance.
