### ISSUE TITLE
Looking to hire someone to do some customization of the Timeline. 

### ISSUE THREAD

**Issue by rangewide** [NUKnightLab/TimelineJS3#703]
We are building a timeline and would like to adjust some of the components. Some of our requests are likely doable with tweaks to the CSS which are simply beyond our abilities.  The others might not be possible at all. We are looking to hire a developer with familiarity with KnightLab Timeline. 

To all of you, could you give me feedback on this list of requests from our Director. Which are possible? 

- Title/header: shrink font.
- Body text: up the font by one point. 
- Media Caption: up the font a few points.  
- In the mobile version the media caption seems to want to hide underneath the timeline bar. Fix? 
- Timeline flags: Would like the timeline flags and pins (marking each event) to be modestly more distinct (or not quite as greyed out but still contrasting with the selected event).
- Timeline dates: Increase font size of the millennial dates and make them bold, make the century marks bigger and black but not bold. For both it would be good if the ruler marks for dates was a little darker. 
- Timeline spectrum:  End  the timeline at something like 2150.

**Comment by JoeGermuska** [comment]
Closing, as this is not an "issue" with TimelineJS software.

See [this page from TimelineJS documentation](http://timeline.knightlab.com/docs/overriding-styles.html) for more about overriding presentation styles.

**Comment by rangewide** [comment]
Can you advise if there is an appropriate spot to list such an opportunity for your developer community?

On May 17, 2021, at 11:47 AM, Joe Germuska ***@***.******@***.***>> wrote:



Closed #703<https://github.com/NUKnightLab/TimelineJS3/issues/703>.
