### ISSUE TITLE
Having only an icon as flag, without text

### ISSUE THREAD

**Issue by thierryPopay** [NUKnightLab/TimelineJS3#71]
Would it be possible to have only an icon as flag-marker, without showing the Headline text next to it? (or is it already possible, out of the box?)

The media-thumb image could eventually be used to represent the icon-marker, but the marker should also be styled so that only the icon is shown, without empty space right of the marker.

**Comment by zachwise** [comment]
You could add the following css to achieve your goal:
```
.vco-timemarker .vco-timemarker-content-container .vco-timemarker-content .vco-timemarker-text h2.vco-headline { display:none; }
```

**Comment by thierryPopay** [comment]
Adding the proposed line was hiding the text, but the marker was still 100px wide. This seems to come from the .vco-timemarker-content-container level, where the width is set in stone.

Adding .vco-timemarker-content-container { width: 30px !important; } overwrote the 100px setting, but should this not be a dynamic setting, to support better all devices?


![image](https://cloud.githubusercontent.com/assets/11560767/7215107/afa39880-e5c7-11e4-855f-2f171a9bbfc1.png)
![image](https://cloud.githubusercontent.com/assets/11560767/7215109/cd602f50-e5c7-11e4-9b8b-56487b0e332a.png)
