### ISSUE TITLE
Dropbox audio links don't work without changing URL

### ISSUE THREAD

**Issue by JoyMonteiro** [NUKnightLab/TimelineJS3#719]
I tried using a dropbox link to play an mp3 file, but it did not work until I replaced `dropbox.com` with `dl.dropbox...` as mentioned in https://github.com/NUKnightLab/TimelineJS3/issues/312

Would it be possible to use this replacement automatically for audio content as well?

**Comment by amm266** [comment]
can you give me a code example?
i am not a member of team but i want to solve this issue.
thanks.
