### ISSUE TITLE
Functionality to change group colors.

### ISSUE THREAD

**Issue by Emmetion** [NUKnightLab/TimelineJS3#731]
Here's a screenshot of what I'm trying to change, https://imgur.com/VhwD2rF. I want to change it to a black-ish color instead of the given gray one. Any way that I could go about doing that?

**Comment by Emmetion** [comment]
Thanks for the response, sorry for reopening this issue, but I can't get the style to work on my webpage. 

`<iframe src="https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1UQc4ZYIK05u6Dg4JklQoNPEPek1GKuOxFSHHnWvy7vc&font=Default&lang=en&initial_zoom=2&height=650&style=https://raw.githubusercontent.com/EmmetSp/Timeline-HN/main/test-timeline.css" title="W3Schools Free Online Web Tutorials" width=100% height=100%></iframe>
` - My Current Embed.

I'm trying to change the color of the groups but It's not cooperating. 

The style tag holds the URL: https://raw.githubusercontent.com/EmmetSp/Timeline-HN/main/test-timeline.css

Nothing seems to update on my end, I also tried using the timeline.css hosted in the CDN, modifying the class .tl-timegroup-message, but still nothing.

Anyway you could help me out? Again, sorry for reopening this issue.

**Comment by JoeGermuska** [comment]
the URL parameter for a user provided CSS is `theme` not `style` (cf the "Other CSS presentation" section of the [Overriding Styles](http://timeline.knightlab.com/docs/overriding-styles.html) doc.)

I did a quick test to verify that the value of theme can be specified as a fully-qualified URL, using
https://cdn.knightlab.com/libs/timeline3/latest/css/themes/timeline.theme.dark.css

I then tried your URL on a local setup, and did not see any effect. A quick look in the inspector suggested that your selectors may not be specific enough, despite anything I may have said before.

Hopefully this helps you get further.

**Comment by Emmetion** [comment]
This is strange, I used your given timeline.theme.dark.css URL and it worked just fine, but when copying it into a GitHub repo and getting the raw text, nothing changes. Here are the URL's I've tried:

Dark Theme CSS file: `https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1UQc4ZYIK05u6Dg4JklQoNPEPek1GKuOxFSHHnWvy7vc&font=Default&lang=en&initial_zoom=2&height=650&theme=https://raw.githubusercontent.com/EmmetSp/Timeline-HN/231f5f2c7ff20cc71f2226bc918244dc24949307/test-timeline.css`

"Custom" CSS file: `https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1UQc4ZYIK05u6Dg4JklQoNPEPek1GKuOxFSHHnWvy7vc&font=Default&lang=en&initial_zoom=2&height=650&theme=https://cdn.knightlab.com/libs/timeline3/latest/css/themes/timeline.theme.dark.css`

**Comment by JoeGermuska** [comment]
It's my understanding that GitHub does not want "raw" URLs to be used as a shortcut to web serving, so it may be that something in how the request is handled in this case makes it invalid.

One solution would be to put the CSS file directly on whatever server you're using to embed the iframe; another would be to use [GitHub Pages](https://pages.github.com/) to serve the file using GitHub's preferred path for web publishing.
