### ISSUE TITLE
`Reset.less` isn't used by the library

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [NUKnightLab/TimelineJS3#734]
In the source code, there is the [`Reset.less`](https://github.com/NUKnightLab/TimelineJS3/blob/master/src/less/core/Reset.less) style exists. This file is getting imported into the [`TL.Timeline.Base.less`](https://github.com/NUKnightLab/TimelineJS3/blob/57a9525500c97fef6568c04e282b0ddbe17fecec/src/less/TL.Timeline.Base.less#L16). 
The **problem** is that the `Reset.less` styles are applied only to the [`.tl-storyjs`](https://github.com/NUKnightLab/TimelineJS3/blob/57a9525500c97fef6568c04e282b0ddbe17fecec/src/less/core/Reset.less#L4), but this class is never mentioned again the source code and doesn't exist in the resulting component!
![image](https://user-images.githubusercontent.com/68850090/170065434-e15c8eec-68d7-49f7-ad38-615d57dee15e.png)
![image](https://user-images.githubusercontent.com/68850090/170065565-d03a9013-fef8-4e38-8071-e4cbbaa0a6b2.png)

Should the `tl-storyjs` be changed to the top-level class `tl-storyslider`?

**Comment by JoeGermuska** [comment]
There's no shortage of cruft in the TimelineJS code base, it's true.

I think it would be better to remove it than move it, since moving it could impact existing timelines, and there isn't, as far as I know, anything about existing timelines that moving it would fix.

Thanks for pointing this out.

**Comment by oleksandr-danylchenko** [comment]
Thanks for the feeback! I could create a PR that removes the unused `Reset.css`

**Comment by JoeGermuska** [comment]
Thanks for the PR
