### ISSUE TITLE
Slide screenreaders reading order improvements

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [NUKnightLab/TimelineJS3#745]
Our a11y tester noted that the current reading order of the Timeline `Slide` can be a bit confusing for the visually impaired users.

Now it reads as:
![CopyQ IvipAY](https://user-images.githubusercontent.com/68850090/174115079-461a4c2e-dac1-4fd8-8c02-1ebb686ab097.png) 

https://user-images.githubusercontent.com/68850090/174115109-04acb76c-303d-41c7-a284-3831feed5506.mp4

The images have descriptions, but the images and their metadata come before both the `<h3>` and `<h2>` headings that they support. Also, the use of `<h3>` for the date and `<h2>` for the slide title could be disorienting, causing students to associate the date with the event before the item that the year is intended to label.

Solution: Change the DOM tree order to get a better reading order but use CSS to position elements in their current places

*I've already started to work on this issue and then I'll do the PR

**Comment by oleksandr-danylchenko** [comment]
> we would prefer not to change them

That's what I kept in mind before starting this :ok_hand:

**Comment by oleksandr-danylchenko** [comment]
Also, some the TL users may depend on the existence of specific tags, like `h2` for titles & `h3` for dates. Because they are navigatable with the SRs with 1-6 number presses. So I'm hesitant to change 'em too

**Comment by JoeGermuska** [comment]
fixed with #747
