### ISSUE TITLE
Accessible sideways arrow buttons

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [NUKnightLab/TimelineJS3#748]
Users may expect to be able to tab to the left and right arrows that are shown on the screen:
![image](https://user-images.githubusercontent.com/68850090/174609696-7ec80a2c-66b8-4366-9d0e-b17586696273.png)
Without being able to tab to the left and right arrows, you don’t get to see the rollover text, and some understanding of the order of the timeline might be less apparent. **Unfortunately, now the area of the arrows is not accessible from the keyboard.**

**Solution:** Use a button role, through the <button> tag or through a role attribute.

---

Moreover, the previous and next buttons are labeled only by their detailed text and don't have labels that tell the purpose of the controls and without a role.
![image](https://user-images.githubusercontent.com/68850090/174612750-f47c408a-d029-4d08-9f52-d95d429a2bf7.png) ![image](https://user-images.githubusercontent.com/68850090/174612767-243e5be3-34eb-4602-b305-1b0c63d85bdb.png)
**Solution:** Begin the label with something like “Previous, ” or “Next, ”, and also include the details text inside the label. This can be done through aria-label or as content text. Using a comma after Previous or Next can create a nice pause. Some users will press without waiting for the screen reader to finish reading the control label.

**Comment by JoeGermuska** [comment]
fixed with 7808fd6
