### ISSUE TITLE
Add tab stop that encompasses the full timeline

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [NUKnightLab/TimelineJS3#753]
**The timeline itself does not receive focus**, instead, one element of the timeline gets focus and then the arrow keys move focus between the items. The one element gets focused at the beginning of the focus order for the timeline. In other words, it is the first tab stop within the timeline. **But, when that one element gets focus, the element is not necessarily scrolled into view, and for this reason, there is no visible focus indication.**

Solution: **Provide a focus indicator that outlines the full rectangle for the timeline**
1. Create a tab stop that encompasses the full timeline (`tabindex=”0”` on `div`, for example)
2. Ensure that landing on this tab stop causes the timeline to be scrolled into view (should happen through default browser functionality)
3. Provide a focus indicator that outlines the full rectangle for the timeline

**Comment by JoeGermuska** [comment]
Fixed with [30f8907](https://github.com/NUKnightLab/TimelineJS3/commit/30f890791cc2c4c817196a52d5f0bc4cb53bf43f)
