### ISSUE TITLE
Accessible `TimeMarker` elements

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [NUKnightLab/TimelineJS3#767]
The `TimeMarker`s don't have roles or an alternative text that tells their function.

For example, the Louisiana Purchase item is read as a clickable image, with part of the file name used as the accessible name, followed by a heading level 2 with the item label as the heading text.
![CopyQ gLDJfb](https://user-images.githubusercontent.com/68850090/174816967-2801fccf-0e5b-4ac7-8b3a-33780919808f.png) ![CopyQ hLrMmF](https://user-images.githubusercontent.com/68850090/174816782-6212516e-0334-4482-bba6-6227f13a2065.png)

_**Solution:**_ To imitate the visual ability to navigate  by event label and date, consider providing a slider that lists the event label first and then a date `[<event_label>,  <date>]`

**Comment by JoeGermuska** [comment]
fixed in 3d5ff2b
