### ISSUE TITLE
State-based `aria-label`s for the `MenuBar` buttons

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [NUKnightLab/TimelineJS3#769]
![image](https://user-images.githubusercontent.com/68850090/174844926-69956d82-2cd6-4805-9bd3-c0138b4c2bec.png) ![image](https://user-images.githubusercontent.com/68850090/174844941-0d8177cf-8b07-4135-a46a-e306695001a6.png) ![image](https://user-images.githubusercontent.com/68850090/174844955-bc541be4-1adb-43ab-bc3d-7771b47afb12.png)

It would be amazing to provide the currently displayed timeline years in the alternative text for the `MenuBar` buttons so that the screen reader can understand what is being shown without having to go over to the timeline.

A rather reliable approach would be to provide the same info as the average user can see and for each of the buttons:
- “zoom in, to show less than 1783 to 1823”
- “zoom out, to show more than 1783 to 1823”

**Comment by JoeGermuska** [comment]
fixed with dda45e9
