### ISSUE TITLE
Fix appearing of the `Slidenav` arrows on mobile

### ISSUE THREAD

**Issue by oleksandr-danylchenko** [NUKnightLab/TimelineJS3#773]
The component navigation elements behave funky when a user changes the display orientation from a portrait to the landscape and back.

https://user-images.githubusercontent.com/68850090/177153423-df265d18-ed14-4ee6-a1b1-a914b515db0f.mp4

1) When a page is initially rendered in the portrait mode, the sideways arrows **are not displayed**. On the JS side, it's handled [here](https://github.com/NUKnightLab/TimelineJS3/blob/master/src/js/timeline/Timeline.js#L579-L583), and on the CSS side [here](https://github.com/NUKnightLab/TimelineJS3/blob/master/src/less/slider/TL.SlideNav.less#L239-L243). But it seems like mobile styles are not applied if a user rotated their phone into a landscape mode. Moreover, when a user rotates a phone back to portrait mode, the styles are not reverted.
2) When a user clicks on the arrows they unexpectedly jump and don't restore their initial positions.

The same behavior can be reproduced on the official examples page -https://timeline.knightlab.com/examples/user-interface/index.html

**Comment by oleksandr-danylchenko** [comment]
Feedback from one of our testers:

> **Issues:** 
> - Too small slide - content view area.
> - Chevrons appear in the landscape view. (On the first load they are not visible (Portrait view))
> - Chevron right - Navigation doesn't work. (Screen record attached)
> - Chevron left - Navigation has odd animation. (Screen record attached)
> [Screen_Recording_20220630-152844_Soomo Reader (1).mp4](https://height-files.storage.googleapis.com/9e8e8713-5adb-4a46-bb68-2ec2aaa6c3d1.mp4) 
> 
> I added this issue to this task because this issue happens after the landscape view:
>  - After flipping a phone to landscape view and back to portrait, chevrons appear.
> ![Screen Shot 2022-06-30 at 4.48.32 PM.png](https://height-files.storage.googleapis.com/13c94de1-edda-4a88-9ee8-e7a50ea13cd0.png)

**Comment by oleksandr-danylchenko** [comment]
Even if the sideways arrow is displayed in the `tl-mobile` that sets `display: none;`, the inline styles overrides it
![image](https://user-images.githubusercontent.com/68850090/177163655-7ebdd907-e13b-4f8a-9428-02ceb0e354bd.png)

**Comment by JoeGermuska** [comment]
fixed in 29e17fb
