### ISSUE TITLE
How can I use this tool offline?

### ISSUE THREAD

**Issue by sannyii** [NUKnightLab/TimelineJS3#777]
First ,this is a wonderful TOOL.
Love it. 
BUT, I am a Chinese Developer, you know the web-is-blocked problem.
How can I use this tool offline?
Thanks very much

**Comment by oleksandr-danylchenko** [comment]
We develop an offline-first mobile application with `TimelineJS` library. Unfortunately, there's no built-in switch in the `TimelineJS` itself. 

**_Firstly_**, you won't be able to use CDN. So you'll need to use the [@knight-lab/timelinejs](https://www.npmjs.com/package/@knight-lab/timelinejs) package to import the `TimelineJS` from there. Also, you'll need a bundler like Webpack or Rollbar which will bundle JS code with the CSS styles.

Here's a very simplified copy of our `TL` component wrapper in React:
```tsx
import { Timeline } from '/@knight-lab/timelinejs';
import  '@knight-lab/timelinejs/dist/css/timeline.css';

const WebtextTimeline = (props) => {
	const { data, options } = props;

	const timelineElementRef = useRef();
	const timelineInstanceRef = useRef();

	useLayoutEffect(() => {
		// Prevents duplicated Timeline instances on rerenders
		const { current: timelineInstance } = timelineInstanceRef;
		if (timelineInstance) return;

		const { current: timelineElement } = timelineElementRef;
		const timeline = new Timeline(timelineElement, data, options);
		timelineInstanceRef.current = timeline;
	}, [data, options, onSlideChange]);

	return (
           <div ref={timelineElementRef} style={{ width: '100%' }} />
	);
};
```

**_Secondly_**, before showing any content we download the documents with all the slides. Then we parse it to get every used image URL. Download that images and store them on the disk. In the example above you can see that we pass the `data` prop to the `WebtextTimeline` component (its structure described [here](http://timeline.knightlab.com/docs/json-format.html)). The `data.title` and `data.events` ** don't contain the image URLs that lead to the network**. They are replaced with **URLs that point to locally stored images**.

--- 

In that way, we're able to use `TimelineJS` offline in our app. Feel free to leave more questions in the thread :raised_hands:

**Comment by sannyii** [comment]
THAT is a lot helpppp!
BUT I only write vue and now I use vue3, ALSO I can learn React now!
If you can give me a  VUE3 Version Code , I would much appreicaite!
PS.  this is amazing!  Thank you again.

`<template>
  <div id="timelineweb">
    
  </div>
</template>

<script setup lang="ts">
import { Timeline } from "@knight-lab/timelinejs";
import "@knight-lab/timelinejs/dist/css/timeline.css";
import timelinedata from './timeline.json'

// Create new Timeline object
var timeline = new Timeline("timelineweb");

// Set event handlers
// event_name = string, name of the event, e.g. "change"
// data = JavaScript object containing event-specific properties listed below
// timeline.on(event_name, function(timelinedata) {
//     // handle event
// });

</script>

<style></style>
`
this is my demo.

**Comment by oleksandr-danylchenko** [comment]
> If you can give me a VUE3 Version Code

Unfortunately, I wrote Vue only for one project at university 2 years ago. So I don't think that I'm proficient enough to provide the code for the component :sweat_smile:.

But _that template looks correct_ at the first glance. Also, it does pretty much the same thing my React component does. So it's definitely worth a try :+1:

**Comment by sannyii** [comment]
YES!!! 
Let me learn React and Try.
Thanks again and Appreciate your time~~~

**Comment by oleksandr-danylchenko** [comment]
You're welcome :raised_hands:

**Comment by sannyii** [comment]
Success!!!
![image](https://user-images.githubusercontent.com/34569814/180948263-7f4adb93-f9d3-4bc9-a0ae-47c6a69c1096.png)
I got it on my web programe! 
Wow!!!
I also want to  know can I get this click movement under control?
For Example , I click the red one and trigger my event!

**Comment by oleksandr-danylchenko** [comment]
Do you mean that you want to intercept the click on the `Marker`s? `Timeline` has a bunch of event you can listen to - https://github.com/NUKnightLab/TimelineJS3/blob/master/API.md#events

Personally, I listen to the `change` event to react on the currently displayed slide: `timeline.on('change', ({ unique_id }) => onSlideChange?.(unique_id));`

**Comment by sannyii** [comment]
YES!!!
YOUR Efforts is remarkable!!

**Comment by sannyii** [comment]
Sorry again!
How can make these into Chinese?
![image](https://user-images.githubusercontent.com/34569814/180965228-52aea92b-672d-4a28-8cb0-42922ce6c7eb.png)

**Comment by oleksandr-danylchenko** [comment]
You're welcome :wink:. And thank you for the wishes :hugs:

**Comment by zhehenyuhang** [comment]
Hello, have you ever used json to transfer data?  The new json is customized through zh-cn.json.  I don't understand the data attributes.

If you have used it, can you tell me how to use it?
