### ISSUE TITLE
Add responsive views to preview

### ISSUE THREAD

**Issue by thejordan** [NUKnightLab/TimelineJS3#78]

**Comment by JoeGermuska** [comment]
proposed: use javascript to resize the iframe container to phone and desktop sizes, maybe others. Investigate pym.js to help make sure the frame contents redraw when the iframe container changes size.

**Comment by hbillings** [comment]
Resizing the iframe doesn't result in something that looks like what is available on mobile. This functionality is in the code but is commented out for now until we figure out what the right thing to do is.
![screen shot 2015-07-31 at 10 48 07 am](https://cloud.githubusercontent.com/assets/509309/9011870/fa8bba30-3775-11e5-90ca-9abeb0313dac.png)
