### ISSUE TITLE
Feature proposal: Adding a navigation button to quickly navigate to the last timeline entry

### ISSUE THREAD

**Issue by jeweljohnsonj** [NUKnightLab/TimelineJS3#788]
First of all, thank you for this wonderful tool! 

I use `TimelineJS` in my blog to showcase the [timeline](https://one-carat-blog.netlify.app/) of the posts I wrote. There is a quick navigation button which immediately sends the user to the first entry in the timeline. It would be nice if there was a similar button which would send the user to the last entry in the timeline.

**Comment by oleksandr-danylchenko** [comment]
This makes sense to me :thinking: 

Also, I relatively recently added a feature that allows navigating to the first slide with the "Home" button and to the last one with the "End" button. 

So the "hardest" part will be to fit the 4th button into the `NavBar`. Maybe the other 3 buttons can be decreased a bit and the 4th will fit right into :thinking:

**Comment by oleksandr-danylchenko** [comment]
@jeweljohnsonj 
Also there's an option `start_at_end` which allows you to display the timeline starting from the end

**Comment by oleksandr-danylchenko** [comment]
@JoeGermuska 
Could you please extend the `tl-font` with another [IcoMoon](https://icomoon.io/app) icon and name it `tl-goforward`?
![image](https://user-images.githubusercontent.com/68850090/187772153-249e56e9-aa99-49bb-b186-78424e30446d.png)

There's already a perfectly matching button called redo on IcoMoon site.

**Comment by oleksandr-danylchenko** [comment]
Here's what I did but I just lack the icon :pray: 
https://user-images.githubusercontent.com/68850090/187772611-09092f7b-f8f5-4c28-84b4-f3d3b3677ebc.mp4

**Comment by jeweljohnsonj** [comment]
> Here's what I did:
> 2022-08-31.23-08-44.mp4
> 
> But I just lack an icon for the go forward button and asked @JoeGermuska about in the PR below

Oh, this is exactly what I wanted! Thank you so much for taking the time to implement this.

**Comment by jeweljohnsonj** [comment]
@oleksandr-danylchenko 

Yes! That is another thing which I wanted to have.

I have tried to change the `TL` to a dark theme before. Since I am using `iframe` embeds, I first tried to include `&theme=dark` in the `src` and I got the following timeline which has the time frame in the dark theme but not the picture frame above the timeline.

The `iframe` embed I used;
```
<iframe src='https://cdn.knightlab.com/libs/timeline3/latest/embed/index.html?source=1x140XobOdXwflXTyN53o_0udhJAOW8SVnPgRX5iXtxE&font=Default&lang=en&initial_zoom=2&height=650&theme=dark' width='100%' height='650' webkitallowfullscreen mozallowfullscreen allowfullscreen frameborder='0'></iframe>
```

![Screenshot 2022-09-02 101927](https://user-images.githubusercontent.com/74355965/188061408-742582b0-bd0a-4d86-952b-935e0af575ec.png)

The heading and the hyperlinked text are also blanked out, so I did not know how to fix it. Also, I am not skilled enough to directly change the default CSS files to alter the timeline properties, so I did not try pursuing it further.

But you seem to do it effortlessly! Where did you exactly input the `theme: 'dark'`, like did you have to change the `css` file?

**Comment by oleksandr-danylchenko** [comment]
Hmm, that's weird :thinking: 
The dark theme should work properly out of the box with the titles of your slide and there are no other CSS manipulations should be required.
I can look at this issue after work today or tomorrow morning :raised_hands:

**Comment by JoeGermuska** [comment]
weird. I wrote a function to walk through the `.tl-storyslider` and its children, and the white is set on `.tl-slider-background` element, not via CSS.  I haven't yet reconstructed when that happens, although when loading the timeline, there's a perceptible transition from the normal 'dark' to the white.  

In case I need it later, here's the code I used to find children which didn't have a dark background. I admit that I don't totally understand the runtime relationship between `background` and `background-color` but in any case, running this only reveals `tl-slider-background`

```javascript
x = {
    'background': [],
    'background-color': []
}

function walk(el) {
    for (let i = 0; i < el.childElementCount; i++) {
        walk(el.children[i])
    }
    if (!(el.classList.contains('tl-loading-icon'))) {
        let background = getComputedStyle(el)['background']
        if (background.indexOf('rgba(0, 0, 0, 0)') == -1) {
            x['background'].push([background, el])
        }
        let bgcolor = getComputedStyle(el)['background-color']
        if (bgcolor != "rgba(0, 0, 0, 0)") {
            x['background-color'].push([bgcolor, el])
        }
    }
}

walk(document.querySelector('.tl-storyslider'))
```

**Comment by oleksandr-danylchenko** [comment]
> weird. I wrote a function to walk through the `.tl-storyslider` and its children, and the white is set on `.tl-slider-background` element, not via CSS. I haven't yet reconstructed when that happens, although when loading the timeline, there's a perceptible transition from the normal 'dark' to the white.
> 
> In case I need it later, here's the code I used to find children which didn't have a dark background. I admit that I don't totally understand the runtime relationship between `background` and `background-color` but in any case, running this only reveals `tl-slider-background`
> 
> ```js
> x = {
>     'background': [],
>     'background-color': []
> }
> 
> function walk(el) {
>     for (let i = 0; i < el.childElementCount; i++) {
>         walk(el.children[i])
>     }
>     if (!(el.classList.contains('tl-loading-icon'))) {
>         let background = getComputedStyle(el)['background']
>         if (background.indexOf('rgba(0, 0, 0, 0)') == -1) {
>             x['background'].push([background, el])
>         }
>         let bgcolor = getComputedStyle(el)['background-color']
>         if (bgcolor != "rgba(0, 0, 0, 0)") {
>             x['background-color'].push([bgcolor, el])
>         }
>     }
> }
> 
> walk(document.querySelector('.tl-storyslider'))
> ```

Thanks for providing this code snipper. I can start working from it

**Comment by oleksandr-danylchenko** [comment]
@JoeGermuska, then I have a question? 
Was the new contrast theme with a11y fixed deployed to the CDN? :sweat_smile:

**Comment by jeweljohnsonj** [comment]
Thank you for adding the requested feature. I also see that the changes have been merged into the master. But I don't know how to use this feature, do I have to change or add anything to the code of the timeline to enable the back button?

**Comment by JoeGermuska** [comment]
We have not yet released a version of TimelineJS that makes these changes available. We've just started the school year at Northwestern, so my focus got pulled away. I will try to cut a release this week.

**Comment by JoeGermuska** [comment]
Looks like this will be slightly delayed, see [this note](https://github.com/NUKnightLab/TimelineJS3/pull/794#issuecomment-1269009900) on the PR that tried to fix the background color issue. Maybe we can still get it sorted this week 🤞

**Comment by JoeGermuska** [comment]
I guess this needn't delay the release; the bug is really with themes... still, not today now

**Comment by jeweljohnsonj** [comment]
> We have not yet released a version of TimelineJS that makes these changes available. We've just started the school year at Northwestern, so my focus got pulled away. I will try to cut a release this week.

Oh no worries, I am just really happy that you are helping me. Please take your time.

**Comment by JoeGermuska** [comment]
This feature was introduced in version 3.9.0 (2022-10-07) but this issue was not closed.
