### ISSUE TITLE
Build out api and events for developers.

### ISSUE THREAD

**Issue by zachwise** [NUKnightLab/TimelineJS3#8]
We need to make a list of things developers might want and make sure we document it.

**Comment by JoeGermuska** [comment]
@zachwise what is a 'marker' in this context? Something on the nav? would that be separate from a corresponding slide? If not, I'd say it should be called "addSlide" instead.

**Comment by jywsn** [comment]
Added API.md at the root of the repo.  You can add comments/suggestions here or in the doc itself.

**Comment by zachwise** [comment]
Can we close this issue @JoeGermuska ?
