### ISSUE TITLE
apply CSS change to groups

### ISSUE THREAD

**Issue by thejordan** [NUKnightLab/TimelineJS3#80]
see #67 
style it up pretty

**Comment by zachwise** [comment]
I'm not sure what this is or what needs changed.

**Comment by thejordan** [comment]
Checking the work on #67 and making everything looks correct when using groups

**Comment by thejordan** [comment]
Right now I have two different groups: excavations and history
They do not appear any different when I preview the timeline

Link to spreadsheet: https://docs.google.com/spreadsheets/d/1Q3qQzRQSCBPsf9x46aVjMX2SGCTkSRABlQd7xprqynM/pubhtml

**Comment by zachwise** [comment]
Must be a spreadsheet issue.

**Comment by JoeGermuska** [comment]
This was fixed in bc46786e9dd3f9c2aba7c2fcf8b4e336f02d9818
