### ISSUE TITLE
Error:  TypeError: can't assign to property "date_obj" on "1390-01-01T00:00:00.000Z": not an object

### ISSUE THREAD

**Issue by CommandLord** [NUKnightLab/TimelineJS3#805]
I only get this error message when opening a timeline with Firefox on MacOS. The date varies on different timelines.

I tested it on Chromium and it did work. I have not tested it on other devices. The error may result by my configuration of firefox but I am not shure.

The Error is displayed on the site and not in the console.

**Comment by JoeGermuska** [comment]
Sorry, I missed this coming through. Can you provide a link to the Google Sheets configuration, and/or to the timeline itself?

Note that, in general, we're more prompt in responding to support requests sent via [our support system](https://knightlab.zendesk.com/hc/en-us/requests/new).
