### ISSUE TITLE
Icons in `../../css/icons` not resolving when building with Vite 3.2.3 and later

### ISSUE THREAD

**Issue by jxjj** [NUKnightLab/TimelineJS3#831]
Hello there – we love TimelineJS. Thank you for all your hard work on it.

We use vite for building assets and noticed after updating vite timelinejs produces errors when trying to resolve icons:

```console
../../css/icons/tl-icons.eot referenced in node_modules/@knight-lab/timelinejs/src/less/TL.Timeline.less didn't resolve at build time, it will remain unchanged to be resolved at runtime
```

Here's a repo with an example test case:
https://github.com/jxjj/timelinejs-testcase-icon-resolution

Vite version `3.2.2` and prior builds show no issue. Errors start occurring in `3.2.3` up to the latest version `4.3.9`.

**Comment by JoeGermuska** [comment]
Thanks for reporting this. We don't do a lot with Vite, so it would be great to have some community help on this. (But also, we have made very few changes in that timeframe, so not sure it ultimately is an issue for us to solve.)

In any case, your report is a flag for others who run into the problem, and if we're able to put some research time into it, we will as soon as possible -- but again, maybe more active Vite users (or even developers) can lend a hand?

**Comment by jxjj** [comment]
I'm happy to take a look and report back

**Comment by jxjj** [comment]
It looks like this is a known issue when building less files with relative urls using Vite. 
Discussed here: https://github.com/vitejs/vite/issues/11382

The suggested workaround in the thread (set `css.preprocessorOptions.less.rewrites` to `all`) seems to have resolved the issue for us.

This is an example vite config if it helps anyone else:
```js
// vite.config.js
export default {
  css: {
    preprocessorOptions: {
      less: {
        rewriteUrls: 'all',
      }
    }
  }
}
```

**Comment by JoeGermuska** [comment]
Oh great, thank you.  I regret that this becomes kind of a mystery to be solved by Vite users, but i don't know how we could change those to non-relative URLs. Thanks for documenting it here, at least.
