### ISSUE TITLE
VCO is not defined

### ISSUE THREAD

**Issue by AdamGerthel** [NUKnightLab/TimelineJS3#84]
I'm having major trouble using timeline.js. I dare say more trouble than I've ever had with any script. So I'm probably missing something thats *extremely* obvious that I'm just not seeing. 

I can't for the life of me get the most simple example to work. I keep getting the follow error:

> Referenceerror: VCO is not defined

I've tried:

- With and without jQuery
- With timeline.js and/or story-embed.js
- With Google Docs and with basic JSONP
- With different order to load JS in

I've gotten past the error when I've used VMM (which I noticed existed) instead of VCO when initiating the timeline, but no timeline is created either way.

I've created a fiddle to recreate the issue: http://jsfiddle.net/insats/n053oc83/4
As you can see, that basic example also causes the error.

What am I missing?

**Comment by JoeGermuska** [comment]
Your external JS resource is from the [original TimelineJS](/NUKnightLab/TimelineJS), not TimelineJS3, which is a ground-up rewrite. 

For the new version of the project, you should use https://cdn.knightlab.com/libs/timeline3/latest/js/timeline.js

You must also load the CSS: https://cdn.knightlab.com/libs/timeline3/latest/css/timeline.css

More generally, this page is a guide to the kind of thing you're trying to do: http://timeline3.knightlab.com/hands-on.html

**Comment by AdamGerthel** [comment]
... thank you for that explanation.. That was so not obvious :) 

I had tried several CDNs for timeline.js as well as the version that's available via Bower, and they all caused the error. So the readme on this repo is outdated? Or is it the other way around?

**Comment by JoeGermuska** [comment]
The README on this repo is outdated.

**Comment by JoeGermuska** [comment]
@AdamGerthel  I should clarify. The README on this repo was not outdated. It is correct for TimelineJS 3. I have added material clarifying that TimelineJS 3 is a ground-up rewrite of TimelineJS which will "do the same things"

**Comment by AdamGerthel** [comment]
Thanks for the clarification.
