### ISSUE TITLE
important 

### ISSUE THREAD

**Issue by epaz2** [NUKnightLab/TimelineJS3#851]
Hi, today I was opening my timeline to edit it and I got an error, I can't open the document and I want to know if I can recover it.

**Comment by JoeGermuska** [comment]
Without a link to the timeline or the Google Sheets document used to create it, there's not much more support we can provide.

It is sometimes the case that people delete the Google Sheets document which configures the timeline, without realizing that the timeline reads the spreadsheet every time it is loaded. If this might be the case, you may be able to restore the Sheets document from your Google Drive "trash"

If that's not it… we typically prefer this kind of request to come through our [online support desk](https://knightlab.zendesk.com/hc/en-us/requests/new), but whether here or there, if you'd like us to look more closely, please send one or both of those URLs.
