### ISSUE TITLE
documentation site fixes

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#88]
**Make a timeline section**

*Step 2:* the modal after choosing "publish to the web" doesn't reflect the current Google Sheets design. Let's use this one.

![image](https://cloud.githubusercontent.com/assets/46313/7939645/97d86e48-0911-11e5-9d86-6df3867feaa3.png)

*Step 3:*
Remove WordPress plugin section. Not sure what our plan for that will be. not actually sure what that does now, TBH!

**Comment by hbillings** [comment]
The WordPress plugin choice changes the embed code from an iframe to a WP shortcode. Commented out for now!
