### ISSUE TITLE
Implement 'options' for embeds

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#89]
* Language
* fonts
* map type (options may be different than before)
* Start at end
* Hash bookmarks (may not be implemented in core Timeline either)
* debug
* default zoom
* default start slide (we should consider linking this to "start at end" option, so they are a single user widget)

**Comment by zachwise** [comment]
Hash bookmarks is not implemented in this version

**Comment by zachwise** [comment]
`Start at end` may not be either.
`default zoom` may be different than before

**Comment by hbillings** [comment]
Removed:
- hash bookmark
- WP embed

Done:
- fonts
- default start slide
- debug mode

Not working:
- start at end
- default zoom
- language (always English)

Questions:
- what are map types supposed to change?
- how do I know if start at end and default zoom are actually implemented and just need to be tweaked to work, or if they have not been implemented? Where is that code?

**Comment by hbillings** [comment]
In `Embed.js` there are a whole bunch of fonts defined in `font_presets`. They refer to the old fonts. Should these be updated or removed?

**Comment by zachwise** [comment]
Removed

**Comment by hbillings** [comment]
Okay, languages are giving me a headache. They get passed to Embed.LoadLib.js, then to LazyLoad.js. The problem is that they aren't JS any more, so when the browser tries to load them, it gets hung up on the first colon and throws a SyntaxError. I'm unable to figure out what the best approach for loading languages is, so I think I'm going to wait for @JoeGermuska to return to pair with me on it.

**Comment by zachwise** [comment]
Just need the two+ letter name in the options for init:
https://github.com/NUKnightLab/TimelineJS3#options

**Comment by hbillings** [comment]
It's fetching the right language file, but it's not able to load it.

**Comment by zachwise** [comment]
I see. I don't think we ever hooked it up. Definitely a @JoeGermuska issue.

**Comment by JoeGermuska** [comment]
Languages fixed in 4ba73d3fc23b2e3d447b728fae2f86847df9be29
