### ISSUE TITLE
Timeline shows default end date of Jan. 1, 1900 when no end date is specified (screenshot)

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/TimelineJS3#93]
![screen shot 2015-06-04 at 11 24 57 am](https://cloud.githubusercontent.com/assets/509309/7989075/b6d5fdb4-0aac-11e5-8a84-1868330db070.png)

**Comment by zachwise** [comment]
But it's not showing an end date. I don't understand the bug.

**Comment by hbillings** [comment]
It's not showing in the timeline itself, but it's showing above the headline.

**Comment by zachwise** [comment]
Is this from a spreadsheet? I can't replicate the bug from json.

**Comment by hbillings** [comment]
si. Only the start year is populated.

**Comment by zachwise** [comment]
I haven't pulled since 4373c9b515bc1b1da9c7c31880cb75fecac2989d which works fine so maybe it's a bug that was introduced since then.

**Comment by JoeGermuska** [comment]
I doubt that it's a bug in anything but the code which reads from the spreadsheet. I'll take a look.
