### ISSUE TITLE
handle null 'max_rows' when computing row positions

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#96]
Unit tests [12(http://localhost:5000/unit-tests.html?testNumber=12) and [13](http://localhost:5000/unit-tests.html?testNumber=13) have errors because `max_rows` is null (the default value).

We should have defined behavior when max_rows is null. I'd propose allowing as many rows as necessary to have all events with no overlap. This may look strange, but it seems semantically more correct than enforcing a default.

Jenny, I'm assigning this to you because you implemented the recent changes to handle groups. I was looking at it, but admittedly, I found the `_computePositionInfo` function hard to read. It's quite long. If you can see any ways to decompose it into functions to make the flow easier to trace, that would be great. Or if nothing else, add comments to help lay out what's going on.

**Comment by jywsn** [comment]
Fixed.  Deployed to cdn dev
