### ISSUE TITLE
Spreadsheet template uses invalid maps.google.com URL

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/TimelineJS3#97]
We should have only working default content in the spreadsheet template.

**Comment by hbillings** [comment]
The spreadsheet template is owned by Zach and I can't edit.

The revised URL from the preview example is https://www.google.com/maps/place/Medill+School+of+Journalism,+Media,+Integrated+Marketing+Communications+Office+of+Dean/@42.0509363,-87.6737809,18z/data=!4m2!3m1!1s0x0000000000000000:0x683bff755fbf8f0c

**Comment by zachwise** [comment]
I think I just updated the correct one. Let me know if that works.

**Comment by hbillings** [comment]
Looks right to me!
